### ISSUE TITLE
Malpedia integration

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#10]
We should add an analyzer to scan a given file against all the yara rules available in Malpedia.

https://malpedia.caad.fkie.fraunhofer.de/usage/api#apiscanbinary

**Comment by Eshaan7** [comment]
The `POST /api/scan/binary` endpoint you mentioned requires an API token(i.e. registered account ). However, on the Malpedia [website](https://malpedia.caad.fkie.fraunhofer.de/login) it says "Please note that Malpedia does not feature open registration. It is operated as an invite-only trust group."

What do you suggest ?

**Comment by mlodic** [comment]
You could ask for an invitation.

If you really are into giving something to the Threat Intelligence Community, you should try to join different groups or projects and bring your efforts where it is needed. Malpedia is one of the greatest sharing projects in this community.

If you do not manage to join the project, you can still contribute to Intel Owl with another analyzer. Check existing issue or bring your own idea! Everything is welcome!
