### ISSUE TITLE
OpenCTI Connector Issue

### ISSUE THREAD

**Issue by sercuz** [intelowlproject/IntelOwl#1011]
Hello Team,

I would like to thank you for your efforts on this project. 
My issue is when I configured the OpenCTI secrets and other stuff, the connector still not configured. I think I've missed something that I don't know about it. Can you please tell me what to change in the opencti.py and any other things to be changed?
NOTE: I have added my OpenCTI URL and the API Key.

![image](https://user-images.githubusercontent.com/62757007/169655153-c0db93f9-ae4b-4c2d-a278-2142040af2f4.png)

Best Regards,

**Comment by sercuz** [comment]
I've solved the issue by re-installing the project

**Comment by mlodic** [comment]
hey! thanks for your interest in the project! 

Just to let you know, we are working on allowing the user to make such configuration directly from the GUI without the need to re-start the project. Otherwise, right now, when you change the secrets, you have to re-start the application.
