### ISSUE TITLE
Django Admin Panel: 503 Unavailable

### ISSUE THREAD

**Issue by OpalSec** [intelowlproject/IntelOwl#1012]
I'm on a fresh install and have created and logged in as the superuser, but when I try to click through to the Django Admin panel I get a 503 error:
![image](https://user-images.githubusercontent.com/33176069/169680409-77cbd60f-b289-4e6b-b72e-25bc6aad1c24.png)

As far as I can see I didn't miss any steps in setting it up, and I'm able to start and log into it fine as the super user.

**Comment by mlodic** [comment]
hey! thanks for your interest in the project!

that is pretty strange and it does work in normal deployments and we cannot replicate that issue. It is probably something related to your own environment. Are you accessing to the application from the same machine or from the outside? Maybe something blocks the connection on the network? It could also be just temporary.

I maybe could help more but I would need access to logs that you can find in `/var/lib/docker/volumes/intelowlproject_*/*`. If you like you can send them to me here stripped by personal data.

**Comment by OpalSec** [comment]
Of course when I bounce it before trying again before replying - it works, hahah.

I don't know what went wrong but I can get to it now. It gave me a 503 again when I modified and saved changes to a user account, but came good again after a few seconds. Seems like it's an issue with my VM rather than IntelOwl itself, so I'll look into it on my end.

Thanks for your response, and thanks for making such a great project!
