### ISSUE TITLE
[React New Frontend] Add Retry button on Job Result page

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1026]
In case an user would like to try the same analysis again for whatever reason, we could add a "retry" button by leveraging the same component we already use for the "retry" button of the single analyzer (see image)
![image](https://user-images.githubusercontent.com/30625432/171179467-16859094-b9e6-4dea-96da-eb4c11631709.png)

We could add it in the top section of the result page, together with the other action buttons:
![image](https://user-images.githubusercontent.com/30625432/171179614-d4ae294b-49c3-4f50-acf1-9f39cccf0311.png)

Note: it should be remembered that, in that case, the analysis should be "forced" with the appropriate flag. Otherwise, if the actual analysis result is not failed, it would not be re-executed.

**Comment by abheektripathy** [comment]
would like to work on this.
