### ISSUE TITLE
WARNING/MainProcess] Soft time limit (60s) exceeded for intel_owl.tasks.tor_updater[0ede0609-c244-4409-9436-efad3675af22]

### ISSUE THREAD

**Issue by zhefox** [intelowlproject/IntelOwl#1030]
## Environment
1. OS:ubuntu18.04
2. IntelOwl version:latest

##  What did you expect to happen
installing use python3 start.py prod up，The installation detection script detects that it is normal, but the installation times an error，maybe i should iIgnore this warning？
## How to reproduce your issue
just  python3 start.py prod up
## Error messages and logs
intelowl_celery_worker_default | [2022-06-02 05:10:00,114: INFO/ForkPoolWorker-8] Task intel_owl.tasks.check_stuck_analysis[e52588e3-388f-4996-86fd-21f2daa296a5] succeeded in 0.030428823999955057s: None
intelowl_celery_worker_default | [2022-06-02 05:11:00,081: WARNING/MainProcess] Soft time limit (60s) exceeded for intel_owl.tasks.tor_updater[e9cacc21-f59b-4785-8afe-c4deac291422]
intelowl_celery_worker_default | Traceback (most recent call last):
intelowl_celery_worker_default |   File "/opt/deploy/intel_owl/api_app/analyzers_manager/observable_analyzers/tor.py", line 41, in updater
intelowl_celery_worker_default |     r = requests.get(url)
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
intelowl_celery_worker_default |     return request('get', url, params=params, **kwargs)
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
intelowl_celery_worker_default |     return session.request(method=method, url=url, **kwargs)
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
intelowl_celery_worker_default |     resp = self.send(prep, **send_kwargs)
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
intelowl_celery_worker_default |     r = adapter.send(request, **kwargs)
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
intelowl_celery_worker_default |     resp = conn.urlopen(
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
intelowl_celery_worker_default |     httplib_response = self._make_request(
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
intelowl_celery_worker_default |     self._validate_conn(conn)
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
intelowl_celery_worker_default |     conn.connect()
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
intelowl_celery_worker_default |     self.sock = conn = self._new_conn()
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
intelowl_celery_worker_default |     conn = connection.create_connection(
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
intelowl_celery_worker_default |     sock.connect(sa)
intelowl_celery_worker_default |   File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 229, in soft_timeout_sighandler
intelowl_celery_worker_default |     raise SoftTimeLimitExceeded()
intelowl_celery_worker_default | billiard.exceptions.SoftTimeLimitExceeded: SoftTimeLimitExceeded()
![image](https://user-images.githubusercontent.com/77232781/171558716-00252855-d6b1-4488-9dd2-9e219e6925d3.png)

![image](https://user-images.githubusercontent.com/77232781/171558652-25047ed6-4369-41e0-a5c0-30fccef02992.png)

**Comment by mlodic** [comment]
hey, thanks for your interest in the project!

yeah, well it is not something critical. It can happen. Basically, there is a cronjob that tries to update the local DB of the Tor Exit Nodes so you can use the "Tor" analyzers for IP addresses. If that cron jobs lasts too much time, it would be killed. That is what happened and that could be due to networks errors of whatever reason (your connection, Tor service server problems etc). Nothing to worry about. You can enjoy IntelOwl without any problem.

**Comment by zhefox** [comment]
Thank you for your patient reply. pro！



| |
ZHEFOX
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 06/06/2022 21:59 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [intelowlproject/IntelOwl] WARNING/MainProcess] Soft time limit (60s) exceeded for intel_owl.tasks.tor_updater[0ede0609-c244-4409-9436-efad3675af22] (Issue #1030) |

hey, thanks for your interest in the project!

yeah, well it is not something critical. It can happen. Basically, there is a cronjob that tries to update the local DB of the Tor Exit Nodes so you can use the "Tor" analyzers for IP addresses. If that cron jobs lasts too much time, it would be killed. That is what happened and that could be due to networks errors of whatever reason (your connection, Tor service server problems etc). Nothing to worry about. You can enjoy IntelOwl without any problem.
