### ISSUE TITLE
IP search with MISP always return empty response

### ISSUE THREAD

**Issue by Sp-TT** [intelowlproject/IntelOwl#1033]
## Environment
1. OS: Redhat
2. IntelOwl version: latest version

##  What did you expect to happen
Search IP observable with calling [Analyzer MISP]

When searching IP/URL with connected MISP, always return empty response. Other types (domain, hash) ioc working well.

**Comment by mlodic** [comment]
hey, are you sure you got the latest version? that bug should have be solved with this PR (https://github.com/intelowlproject/IntelOwl/pull/979) 2 releases ago

**Comment by Sp-TT** [comment]
> hey, are you sure you got the latest version? that bug should have be solved with this PR (#979) 2 releases ago.
> 
> Could you also tell us an example of a MISP event that you think the search would find? So we can maybe understand whether there is another problem or not

My bad, latest version fixed this issue, please help to close it.
