### ISSUE TITLE
[React new Frontend]  Review using httpOnly flagged cookie for authentication on the frontend.

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1059]
Extracted from #856

**Comment by aryan-bhokare** [comment]
Hi @mlodic hope you're doing great! I have researched about this feature. I wanted to ask can i work on this ?

**Comment by mlodic** [comment]
Yep but first can you please illustrate me which is your plan? Thanks :)

**Comment by aryan-bhokare** [comment]
from what I have seen, from the backend the cookie is always httpOnly (it is default,  but we have also explicitly mentioned it as `CSRF_COOKIE_HTTPONLY = True` ) in `security.py` so we only have the manage the axios requests from the frontend i think we can do it by using `withCredentials: true` in our axios request and the cors options are already http only.
am i going wrong please suggest.

**Comment by mlodic** [comment]
the problem is much more complex because we don't use Django session tokens for classic authentication, we use them only to authenticate to the Django Admin page.

The goal would be to remove the token from the Local Storage and use a cookie instead

**Comment by aryan-bhokare** [comment]
Hi @mlodic @0ssigeno I would like to work on this. With the help of [Read](https://blog.stackademic.com/django-react-secure-authentication-using-http-only-cookie-ac718f0a2797#:~:text=When%20it%20comes%20to%20user,such%20as%20CSRF%20and%20XSS.) and [Watch](https://www.youtube.com/watch?v=sovAIX4doOE&t=108s) I have taken a grasp of what and how exactly httpOnly cookie works however I think this is a  little bit difficult for me but I really wanna work on this as this would be a good contribution. So if @0ssigeno and @mlodic could guide me how should I start and a few things that would really help.

**Comment by mlodic** [comment]
@drosetti  is already working on this

**Comment by aryan-bhokare** [comment]
> @drosetti is already working on this

Oh okay then. I would be glad to do help if needed.
