### ISSUE TITLE
[Discussion Thread] Manual Deployment Methods & Instructions

### ISSUE THREAD

**Issue by cvdsouza** [intelowlproject/IntelOwl#108]
Hi , 
I'm looking to deploy IntelOwl manually in Google Cloud. I want to see what technologies of GCP i can leverage to make it a scalable deployment. Do you have any instructions for manual deployment ?

**Comment by Eshaan7** [comment]
Hi. Thank you for your interest. IMHO, there's 2 ways to go about this.

1. If you are not a GCP and/or django expert and you want to do it fast, you could create a new VM instance, clone the [v1.0.0](https://github.com/intelowlproject/IntelOwl/releases/tag/1.0.0) release, follow the [Installation.md](https://intelowl.readthedocs.io/en/latest/Installation.html) steps and just do `docker-compose up`. The application is built to be efficient in a way that this should be enough in more cases.

2. For a more scalable and efficient deployment, you could leverage different GCP products. Here's an overview:
 - The main (a) django application along with (b) celery and (c) rabbit-mq running in docker via the `docker-compose.yml` file.
 - [Cloud SQL](https://cloud.google.com/sql) for a PostgreSQL database which is used by the main django application.
 - [Cloud Storage Buckets](https://cloud.google.com/storage/docs/creating-buckets) for static files (frontend pages), which will serve as a CDN.
- Use nginx for reverse proxies on the host VM instance. There's already configured nginx config files available under `configuration/` folder.
- And finally let's encrypt for SSL. 

This is very well laid out in details on [GCP's django guide](https://cloud.google.com/python/django). 

We will leave this thread open as a _discussion_ so others could benefit from this too or better yet if someone has ideas regarding this, feel free to join this discussion.

**Comment by Eshaan7** [comment]
Moved to #285.
