### ISSUE TITLE
[React New Frontend] Process time in minutes

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1096]
![image](https://user-images.githubusercontent.com/30625432/178518452-612d88b3-e660-401b-b977-691f631362cd.png)

Visualize minutes when the time reaches over 1 minute. This is the "Job History" page

**Comment by abheektripathy** [comment]
would like to work on this.

**Comment by 0x0elliot** [comment]
let me know if you need any help, friend.
