### ISSUE TITLE
OpenCTI connector

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#11]
IntelOwl was designed to be integrated with other security tools very easily.
In particular, it is a perfect fit for Threat Intelligence Platforms because it can enrich the data available in those platform and can be customized on its own needs.

So, in order to help the community to achieve this result, we should add new connectors for the most used open source TIPs, for example: [OpenCTI](https://github.com/OpenCTI-Platform)

We should study their project and add a relative connector to integrate IntelOwl with OpenCTI. A related issue was already opened: https://github.com/OpenCTI-Platform/connectors/issues/43.
We should leverage the official [IntelOwl client](https://github.com/mlodic/pyintelowl) for this purpose

**Comment by Shailja1806** [comment]
I would like to work on this. plz ,guide me.

**Comment by mlodic** [comment]
This work should be done only after having solved a larger architectural problem in IntelOwl. See #249
