### ISSUE TITLE
Dashboard dates bug 

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1109]
![image](https://user-images.githubusercontent.com/30625432/179526862-bbd05c5e-43bd-4649-96d9-224e85920ff6.png)

![image](https://user-images.githubusercontent.com/30625432/179526931-fd4af75c-42a5-4104-a370-fdcb1e7de2da.png)

It could be a problem with some updates on dependencies.

It could be possible that this is reproducible. Maybe only in certain cases (empty dashboard?) it happens

**Comment by carellamartina** [comment]
![Schermata del 2023-11-16 16-23-58](https://github.com/intelowlproject/IntelOwl/assets/72437046/31c0ccf4-14e5-4cf5-83fe-6b1b85250484)

Already fixed in certego-ui

**Comment by carellamartina** [comment]
![Schermata del 2023-11-16 16-23-58](https://github.com/intelowlproject/IntelOwl/assets/72437046/06c32694-7d65-448e-8a70-c9f7f972ef7a)

Already fixed in certego-ui
