### ISSUE TITLE
[React New Frontend] Configuration of "disabled" value from the GUI

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1117]
Connectors are disabled by default. This was a design choice to avoid to enable dangerous unexpected behavior.

However it is not so clear how to enable them. There is no help at all in the GUI and people would need to find the documentation [here](https://intelowl.readthedocs.io/en/latest/Usage.html#connectors-customization). Same problem exists for the analyzers that are disabled by default.

For this reason, I think that we should:

- [ ] at least add some helpers in the GUI in case the analyzer is disabled. A message that explains what is happening and how to enable it.
- [ ] then, resolve the problem at the core: allow the user to change the `disabled` value directly from the GUI, instead of forcing them to change it from the JSON files. To do that, we would need to wait for this issue to be solved: #433

**Comment by AshirRashid** [comment]
I want to work on this issue, can I be assigned?
I have fixed a similar (but less complicated) issue regarding the disabled property: https://github.com/intelowlproject/IntelOwl/pull/1453.
