### ISSUE TITLE
Can't access Django Admin Interface

### ISSUE THREAD

**Issue by LumberJohn6** [intelowlproject/IntelOwl#1130]
## What happened
So I followed this guide (https://intelowl.readthedocs.io/en/latest/Installation.html) to do a fresh installation of IntelOwl. I followed the steps and everything worked fine I think. I've altered the files env_file_app and env_file_postgres, and I've double-checked that the credentials are exactly the same on both files. I've set some API keys, maybe a bit to soon, but everything worked fine.
After deployment I've created the superuser using the provided command, but here's the issue, after login in to the application I can't go to the Django Admin Interface.

## Environment
1. OS: Ubuntu 22.04 LTS
2. IntelOwl version: 4.0.1

##  What did you expect to happen
I expected to go to the Django Admin Interface without problems and create a user.

## How to reproduce your issue
Fresh install of IntelOwl, follow the install steps on docs and create a superuser. Then click on the Django Admin Interface button and the error should (or maybe shouldn't) occur.

## Error messages and logs
To be honest I need a bit of help here too. I don't know where the logs are to check the errors.

Thank you very much for any help and feel free to ask for more info.

**Comment by LumberJohn6** [comment]
I'm not sure if this counts as logs, but I think it's better than no info at all.

Attaching to intelowl_postgres, intelowl_uwsgi, intelowl_celery_worker_default, intelowl_nginx, intelowl_celery_beat
intelowl_celery_beat     | Waiting for db and UWSGI to be ready...
intelowl_celery_worker_default | Waiting for db and UWSGI to be ready...
intelowl_nginx           | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
intelowl_nginx           | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
intelowl_nginx           | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
intelowl_nginx           | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
intelowl_nginx           | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
intelowl_nginx           | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
intelowl_nginx           | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
intelowl_postgres        |
intelowl_postgres        | PostgreSQL Database directory appears to contain a database; Skipping initialization
intelowl_postgres        |
intelowl_postgres        | 2022-08-01 15:54:55.795 UTC [1] LOG:  starting PostgreSQL 12.11 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
intelowl_postgres        | 2022-08-01 15:54:55.795 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
intelowl_postgres        | 2022-08-01 15:54:55.795 UTC [1] LOG:  listening on IPv6 address "::", port 5432
intelowl_postgres        | 2022-08-01 15:54:55.832 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
intelowl_postgres        | 2022-08-01 15:54:55.969 UTC [21] LOG:  database system was shut down at 2022-08-01 15:54:51 UTC
intelowl_nginx           | /docker-entrypoint.sh: Configuration complete; ready for start up
intelowl_postgres        | 2022-08-01 15:54:56.034 UTC [1] LOG:  database system is ready to accept connections
intelowl_uwsgi           | Waiting for db to be ready...
intelowl_uwsgi           | Migrations for 'durin':
intelowl_uwsgi           |   /usr/local/lib/python3.9/site-packages/durin/migrations/0003_auto_20220801_1555.py
intelowl_uwsgi           |     - Alter field token on authtoken
intelowl_uwsgi           |     - Alter field token_ttl on client
intelowl_uwsgi           | Operations to perform:
intelowl_uwsgi           |   Apply all migrations: admin, analyzers_manager, api_app, auth, certego_saas_notifications, certego_saas_organization, certego_saas_user, connectors_manager, contenttypes, django_celery_results, durin, sessions
intelowl_uwsgi           | Running migrations:
intelowl_uwsgi           |   Applying durin.0003_auto_20220801_1555... OK
intelowl_uwsgi           |
intelowl_uwsgi           | 0 static files copied to '/opt/deploy/intel_owl/static', 230 unmodified.
intelowl_uwsgi           | ------------------------------
intelowl_uwsgi           | DEBUG:  True
intelowl_uwsgi           | DJANGO_TEST_SERVER:
intelowl_uwsgi           | ------------------------------
intelowl_celery_beat     | celery beat v5.2.2 (dawn-chorus) is starting.
intelowl_celery_worker_default | [2022-08-01 15:55:05,845: DEBUG/MainProcess] | Worker: Preparing bootsteps.
intelowl_celery_worker_default | [2022-08-01 15:55:05,847: DEBUG/MainProcess] | Worker: Building graph...
intelowl_celery_worker_default | [2022-08-01 15:55:05,848: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, StateDB, Beat, Consumer}
intelowl_celery_worker_default | [2022-08-01 15:55:05,855: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
intelowl_celery_worker_default | [2022-08-01 15:55:05,855: DEBUG/MainProcess] | Consumer: Building graph...
intelowl_celery_worker_default | [2022-08-01 15:55:05,892: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Tasks, Control, Gossip, Agent, Heart, event loop}
intelowl_celery_worker_default |
intelowl_celery_worker_default |  -------------- celery@worker_default v5.2.2 (dawn-chorus)
intelowl_celery_worker_default | --- ***** -----
intelowl_celery_worker_default | -- ******* ---- Linux-5.15.0-43-generic-x86_64-with-glibc2.28 2022-08-01 15:55:05
intelowl_celery_worker_default | - *** --- * ---
intelowl_celery_worker_default | - ** ---------- [config]
intelowl_celery_worker_default | - ** ---------- .> app:         intel_owl:0x7fae47956040
intelowl_celery_worker_default | - ** ---------- .> transport:   amqp://**:**@rabbitmq:5672//
intelowl_celery_worker_default | - ** ---------- .> results:
intelowl_celery_worker_default | - *** --- * --- .> concurrency: 4 (prefork)
intelowl_celery_worker_default | -- ******* ---- .> task events: ON
intelowl_celery_worker_default | --- ***** -----
intelowl_celery_worker_default |  -------------- [queues]
intelowl_celery_worker_default |                 .> default          exchange=default(direct) key=default
intelowl_celery_worker_default |
intelowl_celery_worker_default |
intelowl_celery_worker_default | [2022-08-01 15:55:05,913: DEBUG/MainProcess] | Worker: Starting Hub
intelowl_celery_worker_default | [2022-08-01 15:55:05,913: DEBUG/MainProcess] ^-- substep ok
intelowl_celery_worker_default | [2022-08-01 15:55:05,913: DEBUG/MainProcess] | Worker: Starting Pool
intelowl_celery_beat     | __    -    ... __   -        _
intelowl_celery_beat     | LocalTime -> 2022-08-01 15:55:06
intelowl_celery_beat     | Configuration ->
intelowl_celery_beat     |     . broker -> amqp://**:**@rabbitmq:5672//
intelowl_celery_beat     |     . loader -> celery.loaders.app.AppLoader
intelowl_celery_beat     |     . scheduler -> celery.beat.PersistentScheduler
intelowl_celery_beat     |     . db -> /tmp/celerybeat-schedule
intelowl_celery_beat     |     . logfile -> [stderr]@%WARNING
intelowl_celery_beat     |     . maxinterval -> 5.00 minutes (300s)
intelowl_uwsgi           | Version 4.0.1
intelowl_celery_beat     | [2022-08-01 15:55:06,185: DEBUG/MainProcess] Setting default socket timeout to 30
intelowl_celery_beat     | [2022-08-01 15:55:06,186: INFO/MainProcess] beat: Starting...
intelowl_uwsgi           | Notification already exists for version 4.0.1
intelowl_uwsgi           | Version 4.0.0
intelowl_uwsgi           | Notification already exists for version 4.0.0
intelowl_uwsgi           | Version 3.4.1
intelowl_uwsgi           | Notification already exists for version 3.4.1
intelowl_celery_beat     | [2022-08-01 15:55:06,265: DEBUG/MainProcess] Current schedule:
intelowl_celery_beat     | <ScheduleEntry: maxmind_updater intel_owl.tasks.maxmind_updater() <crontab: 0 1 3 * * (m/h/d/dM/MY)>
intelowl_celery_beat     | <ScheduleEntry: check_stuck_analysis intel_owl.tasks.check_stuck_analysis() <crontab: */5 * * * * (m/h/d/dM/MY)>
intelowl_celery_beat     | <ScheduleEntry: remove_old_jobs intel_owl.tasks.remove_old_jobs() <crontab: 10 2 * * * (m/h/d/dM/MY)>
intelowl_celery_beat     | <ScheduleEntry: yara_updater intel_owl.tasks.yara_updater() <crontab: 0 0 * * * (m/h/d/dM/MY)>
intelowl_celery_beat     | <ScheduleEntry: talos_updater intel_owl.tasks.talos_updater() <crontab: 5 */6 * * * (m/h/d/dM/MY)>
intelowl_celery_beat     | <ScheduleEntry: tor_updater intel_owl.tasks.tor_updater() <crontab: */10 * * * * (m/h/d/dM/MY)>
intelowl_celery_beat     | <ScheduleEntry: celery.backend_cleanup celery.backend_cleanup() <crontab: 0 4 * * * (m/h/d/dM/MY)>
intelowl_celery_beat     | [2022-08-01 15:55:06,265: DEBUG/MainProcess] beat: Ticking with max interval->5.00 minutes
intelowl_celery_beat     | [2022-08-01 15:55:06,270: DEBUG/MainProcess] beat: Waking up in 4.90 minutes.
intelowl_uwsgi           | [uWSGI] getting INI configuration from /etc/uwsgi/sites/intel_owl.ini
intelowl_celery_worker_default | [2022-08-01 15:55:06,594: DEBUG/MainProcess] ^-- substep ok
intelowl_celery_worker_default | [2022-08-01 15:55:06,596: DEBUG/MainProcess] | Worker: Starting Consumer
intelowl_celery_worker_default | [2022-08-01 15:55:06,596: DEBUG/MainProcess] | Consumer: Starting Connection
intelowl_celery_worker_default | [2022-08-01 15:55:06,607: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq:5672//
intelowl_celery_worker_default | [2022-08-01 15:55:06,607: DEBUG/MainProcess] ^-- substep ok
intelowl_celery_worker_default | [2022-08-01 15:55:06,608: DEBUG/MainProcess] | Consumer: Starting Events
intelowl_celery_worker_default | [2022-08-01 15:55:06,613: DEBUG/MainProcess] ^-- substep ok
intelowl_celery_worker_default | [2022-08-01 15:55:06,614: DEBUG/MainProcess] | Consumer: Starting Mingle
intelowl_celery_worker_default | [2022-08-01 15:55:06,614: INFO/MainProcess] mingle: searching for neighbors
intelowl_celery_worker_default | [2022-08-01 15:55:07,651: INFO/MainProcess] mingle: all alone
intelowl_celery_worker_default | [2022-08-01 15:55:07,652: DEBUG/MainProcess] ^-- substep ok
intelowl_celery_worker_default | [2022-08-01 15:55:07,652: DEBUG/MainProcess] | Consumer: Starting Tasks
intelowl_celery_worker_default | [2022-08-01 15:55:07,700: DEBUG/MainProcess] ^-- substep ok
intelowl_celery_worker_default | [2022-08-01 15:55:07,700: DEBUG/MainProcess] | Consumer: Starting Control
intelowl_celery_worker_default | [2022-08-01 15:55:07,713: DEBUG/MainProcess] ^-- substep ok
intelowl_celery_worker_default | [2022-08-01 15:55:07,713: DEBUG/MainProcess] | Consumer: Starting Gossip
intelowl_celery_worker_default | [2022-08-01 15:55:07,731: DEBUG/MainProcess] ^-- substep ok
intelowl_celery_worker_default | [2022-08-01 15:55:07,731: DEBUG/MainProcess] | Consumer: Starting Heart
intelowl_celery_worker_default | [2022-08-01 15:55:07,734: DEBUG/MainProcess] ^-- substep ok
intelowl_celery_worker_default | [2022-08-01 15:55:07,734: DEBUG/MainProcess] | Consumer: Starting event loop
intelowl_celery_worker_default | [2022-08-01 15:55:07,735: DEBUG/MainProcess] | Worker: Hub.register Pool...
intelowl_celery_worker_default | [2022-08-01 15:55:07,739: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
intelowl_celery_worker_default |             leak, never use this setting in production environments!
intelowl_celery_worker_default |   warnings.warn('''Using settings.DEBUG leads to a memory
intelowl_celery_worker_default |
intelowl_celery_worker_default | [2022-08-01 15:55:07,739: INFO/MainProcess] celery@worker_default ready.

**Comment by 0ssigeno** [comment]
Hi!
 Sorry for the late response, but unfortunately i'm not able to reproduce your error on my end.
What error does the webpage at `/admin/` returns to you? Do you see the page and you are unable to login? Or you don't see the page at all?

The logs that you send are about the application startup, and i see no issue inside them. Can you try to post the logs that are created when you try to login in the admin page (or when you try to reach it)?

**Comment by mlodic** [comment]
closing this because inactive and because we can't replicate the issue
