### ISSUE TITLE
Cache configuration not invalidated when adding environment key

### ISSUE THREAD

**Issue by 0ssigeno** [intelowlproject/IntelOwl#1143]
## What happened
Bring up application, the environment key of Analyzer X is not set
Check that X is not configured on the GUI
Bring down the application 
Add the env_key of X
Bring up the application
X is still not configured on the GUI

##  What did you expect to happen

X is configured on the GUI

## Why it happens

The configuration is cached, the env_key is retrieved only when the configuration cache is invalidated. Changing the env_key does not cause the cache to be invalidated, meaning that the application does not retrieve the new key and the GUI does not show it

**Comment by mlodic** [comment]
should be solved, env_keys are also deprecated
