### ISSUE TITLE
error in file (env_file_app) environment variable name 'MOCK_CONNECTIONS 

### ISSUE THREAD

**Issue by ibrahim3pf** [intelowlproject/IntelOwl#116]
Hello,
When I excute "docker-compose up" I receive this error.

> ERROR: In file IntelOwl/env_file_app: environment variable name 'MOCK_CONNECTIONS ' may not contain whitespace.

Thanks.

**Comment by Eshaan7** [comment]
Please make the change given here: https://github.com/intelowlproject/IntelOwl/pull/113/files#diff-ec42129bc4570b65f98290a629d63961
Just remove the whitespace around the variable.

We will be releasing a new version with this fix soon!

**Comment by ibrahim3pf** [comment]
Thanks Eshaan7
