### ISSUE TITLE
[Analyzer] Update GreyNoise to use SDK and Remove Alpha

### ISSUE THREAD

**Issue by bradchiappetta** [intelowlproject/IntelOwl#1192]
## Name:
GreyNoise

## Link: 
greynoise.io

## Type of analyzer
**this can be observable, file, and docker**
Observable

## Why should we use it
This is just a recommended update to use our SDK and remove the no longer available Alpha API

## Possible implementation

**Comment by bradchiappetta** [comment]
I am happy to work on this to integrate the GreyNoise SDK and make the updates I've listed.

**Comment by mlodic** [comment]
Thank you for listing out the updates to do. Feel free to open a PR with the updates! It would be appreciated!

**Comment by bradchiappetta** [comment]
Hi @mlodic : I saw the updated PR merged into the `develop` branch.  Does that indicate everything was resolved and you could accept the update?  If so, just curious what your release process is for when that is available.  I have a client that I'd like to notify when they can use it.

**Comment by mlodic** [comment]
We have no scheduled release right now because we are independent in that sense and we strongly rely on voluntarily help so it depends on when we get enough updates that justify a new release.

I am also very busy right now and Docker Hub deleted my autobuild configuration so that would require some time that I don't know when I will be able to invest. Please follow the project updates and you'll get the notification on the new release.

**Comment by mlodic** [comment]
Obviously if Greynoise would choose to support the project for a donation, I can speed up the process :P Thank you for your understanding

**Comment by mlodic** [comment]
closing because will be merged in the next release

**Comment by mlodic** [comment]
> Obviously if Greynoise would choose to support the project for a donation, I can speed up the process :P Thank you for your understanding

well, considered that I helped you finish this task and basically that addition did not bring anything really valuable in the platform, I could at least deserve an answer. @bradchiappetta

**Comment by mlodic** [comment]
and your release is available, you can freely gain money out of this open source project
