### ISSUE TITLE
MISP

### ISSUE THREAD

**Issue by BlAd373** [intelowlproject/IntelOwl#1199]
Sorry my ignorance 
How i connect misp and configure scan onionsearch darksearch ?
Misp work in remote server i have ip etc already add ip in /configuration/connector_conf.json

![Screenshot 2022-09-13 120443](https://user-images.githubusercontent.com/22465921/189951655-4a7c0b41-5027-498d-a209-10788f2f8fc6.png)

**Comment by mlodic** [comment]
please read the docs https://intelowl.readthedocs.io/en/latest/

**Comment by BlAd373** [comment]
ty already read it 
but probably i do something wrong 
changed analyzer_config.json
 "MISP": {
    "type": "observable",
    "python_module": "misp.MISP",
    "description": "scan an observable on a custom MISP instance",
    "disabled": false,
    "external_service": true,
    "leaks_info": false,
    "observable_supported": ["ip", "domain", "url", "hash", "generic"],
    "config": {
      "soft_time_limit": 30,
      "queue": "default"
    },
    "secrets": {
      "api_key_name": {
        "env_var_key": "my misp key",
        "description": "",
        "required": true
      },
      "url_key_name": {
        "env_var_key": "my misp url",
        "description": "",
        "required": true

changed connector_config.json
"MISP": {
    "disabled": false,
    "description": "Automatically creates an event on your MISP instance, linking the successful analysis on IntelOwl",
    "python_module": "misp.MISP",
    "maximum_tlp": "WHITE",
    "config": {
      "soft_time_limit": 30,
      "queue": "default"
    },
    "secrets": {
      "api_key_name": {
        "env_var_key": "my_MISP_KEY",
        "description": "API key for your MISP instance",
        "required": true
      },
      "url_key_name": {
        "env_var_key": "my _MISP_URL",
        "description": "URL of your MISP instance",
        "required": true
shut down and restart 
i think i lost something

**Comment by mlodic** [comment]
you should not change the `env_var_key` there, you should populate the env variables in the env file. please read the docs

**Comment by BlAd373** [comment]
ty i continue to read but not find where i have populate it
