### ISSUE TITLE
Adding Playbook Cache Feature

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1226]
From @0x0elliot 's GSoC plan:

After every scan which uses more than one Analyzer and Connectors, We would
present the user with a pop-up that would say “Do you want to save this scan as a
Playbook?”

If the user agrees to this, The configuration would be sent to the backend where it would
be saved “lazily” in the database. The database model for each entry would somewhat
look like this:

```
class CachedPlaybook(models.Model):
name = models.Charfield(max_length=225)

class CachedPlaybookEntries(models.Model):
playbook = models.ForeignKey(to=CachedPlaybook, on_delete=models.CASCADE)
type = models.CharField(max_length=50) # analyzer/connector
name = models.CharField(max_length=225)
active = models.BooleanField()
# ^ if False, then it means that analyzer/connector
# has been altered
```

This would be in the `models.py`.

The result of the cached playbooks would be appended to the JSON returned by
`/api/playbook/playbook_configuration`.

Some further technical support would be required to be added internally for the other
endpoints so that we would be looking for the playbook information in both the playbook
JSON file and the cached database entries.

If the playbook entry has an analyzer/connector then we would be marking the cached
playbook entry as False so that the entry is ignored.

**Comment by 0x0elliot** [comment]
this is a feature concerning my code, would love to finish it myself. i would start tackling this issue by the evening (it's currently the afternoon for me :))

**Comment by 0x0elliot** [comment]
might want to delay contributing this week. apologies.

**Comment by mlodic** [comment]
there is no need to apologize man :) have a great week! :)

**Comment by 0x0elliot** [comment]
i have gotten a bit busier this month. i am leaving this issue for the community for the time being. would come back to this when i am free.

**Comment by 0x0elliot** [comment]
got some time. will slowly wrap this up.

**Comment by 0x0elliot** [comment]
To-dos:

- [ ] Finish serializers and models.
- [ ] Make sure that every new playbook that is created is unique 
- [ ] And the one in the JSON file is given more priority if the same named one is ever added back again.
- [ ] Make the endpoints work
- [ ] Finish frontend changes.


Quite the list.
