### ISSUE TITLE
[Analyzer] CriminalIP

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1240]
https://www.criminalip.io/developer/api/post-user-me

**Comment by g4ze** [comment]
Hey! @mlodic  would you like to specify some more details as there a lot of things the api provides. Thanks!

**Comment by mlodic** [comment]
I would probably create 2 different analyzers for 2 different use cases:
The first one could be an analyzer which performs just simple and fast reputation checks, without any active scan. That would support IP addresses and domains.

for IP addresses I would allow all of these endpoints:
![image](https://github.com/user-attachments/assets/85e27ecc-b0a9-4b62-a1de-44cb4b59e52d)
I expect that the default would be to just query the most important of them (/v1/feature/ip/malicious-info), to avoid useless quota burn.
Anyway, that should be configurable via a paremeter like you already did for other similar cases

For domains, I would implement the quick view only: /v1/domain/quick/hash/view.

Then. I would create a "CriminalIP_Scan" or something like that, that would leverage the 2 POST options, for domains only. That would work differently from the previous case cause we would need to perform a polling to the status APIs and then retrieve the result once available, like we do for other "scan-based" analyzers that we have

**Comment by g4ze** [comment]
yep, makes sense!
