### ISSUE TITLE
[Analyzer] Vulners

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1257]
## Name
Vulners

## Link
https://vulners.com/

## Type of analyzer
Generic: https://vulners.com/docs/API_wrapper/api/
maybe other use cases?

## Why should we use it
Free API usage

**Comment by g4ze** [comment]
@mlodic  How exactly do we plan on implementing this one?
They offer a ton of search strategies: https://vulners.com/docs/api_reference/search_strategies/
Implementing all strategies might make it very complex to use.
I suggest implementing [search-in-database](https://vulners.com/docs/api_reference/search_strategies/#search-in-database) , [score-any-vulnerability-with-vulners-ai](https://vulners.com/docs/api_reference/search_strategies/#score-any-vulnerability-with-vulners-ai) as they can cover most of the functionality...?

**Comment by mlodic** [comment]
Agreed
