### ISSUE TITLE
[Analyzer] Netlas.io

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1258]
## Name
Netlas.io

## Link
https://netlas.io/api

## Type of analyzer
* IP/domains search
* Generic search for other endpoints?

## Why should we use it
Free service with 2.5k requests per month. https://netlas.io/api
It is also possible to participate to their reward program here: https://netlas.io/alpha_release

**Comment by deep-poharkar** [comment]
can i have this? would love to contribute.

**Comment by deep-poharkar** [comment]
highly sorry to abandon this issue. I had some code ready but was caught up with university exams. Can I retake this? I will get the draft by today
