### ISSUE TITLE
[Analyzer] BinaryEdge

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1259]
## Name
BinaryEdge

## Link
https://www.binaryedge.io/

## Type of analyzer
IP: https://docs.binaryedge.io/api-v2/#v2queryiptarget and https://docs.binaryedge.io/api-v2/#v2querysearch
Domains: several, starting from https://docs.binaryedge.io/api-v2/#v2querydomainssubdomaintarget

## Why should we use it
Free API up to 250 requests at month

**Comment by shivam-Purohit** [comment]
Hey @mlodic can I work on this?

**Comment by mlodic** [comment]
released
