### ISSUE TITLE
[Analyzer] IP API

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1260]
## Name
ipapi

## Link
https://ip-api.com/

## Type of analyzer
IP-based. 2 possible endpoints:
* https://ip-api.com/docs/api:batch
* https://ip-api.com/docs/dns

## Why should we use it
free endpoint with plain HTTP and max 45 requests/minute

**Comment by shivam-Purohit** [comment]
@mlodic Can I work on this analyzer?

**Comment by mlodic** [comment]
hey, you still have a pending PR to be finished. The repo rules explicitly say that we cannot assign another task if there is another one pending.

**Comment by shivam-Purohit** [comment]
@mlodic Can I take this now ?, I will be more cautious this time.

**Comment by mlodic** [comment]
closed with v4.2.0
