### ISSUE TITLE
[Analyzer] CheckPhish

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1261]
## Name
CheckPhish

## Link
https://checkphish.ai/

## Type of analyzer
IP/Domain/URL: https://checkphish.ai/checkphish-api/

## Why should we use it
https://checkphish.ai/pricing/ 250 scans/month free usage

**Comment by AshirRashid** [comment]
I want to work on adding this analyzer

**Comment by AshirRashid** [comment]
The pull request addressing this issue did not include the closes keyword. Please do close the issue if you think the issue has been adequately addressed.

**Comment by mlodic** [comment]
you are right, closed by #1395
