### ISSUE TITLE
[Analyzer] Orkl search engine

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1274]
## Name
Orkl

## Link
https://orkl.eu

## Type of analyzer
* search hash
* generic search
https://orkl.eu/api/v1/doc/index.html#/

## Why should we use it
Search engine with free requests with API

**Comment by samrath-sudesh-acharya** [comment]
@mlodic  I would like to take up this issue. Please assign it to me

**Comment by samrath-sudesh-acharya** [comment]
@mlodic could you reassign it to me, I am working on this issue, got personnel things in my way that was delaying it. 😞

**Comment by samrath-sudesh-acharya** [comment]
@mlodic  please unassign me, I don't think I can complete it in the coming weeks, got a lot of work to get sorted out 😥
