### ISSUE TITLE
Add chance to change/reset the password of the account

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1285]
We could add an additional section for the user where it is possible to change/reset their password. The "API access" section could be used for inspiration

**Comment by 0x0elliot** [comment]
do you want to make it so that the user has permission to do the same if they are logged in? or, do you want to make it so that there is a proper URL with a token sent to the user's email over this? honestly, that would be pretty cool and would definitely complete IntelOwl neatly and make it even more well-suited for deployment.

**Comment by mlodic** [comment]
yeah basically the issue that I notice is that there is neither chance for the user to change their password, nor to reset it in case they forget.

So they are 2 different but related problems.

The first can be solved by following my and your first suggestion.
The second

**Comment by 0x0elliot** [comment]
very much! would leave this issue open for the community to handle till i have the bandwidth for this one as well.

**Comment by mlodic** [comment]
Password reset feature was added at time of addition of Registration page. Password change feature still needs to be added

**Comment by shivam-Purohit** [comment]
@mlodic I have pushed some initial frontend changes to the authentication branch
I used the login component, suggest me some changes you want. I will try to align the component in the middle.
for the logic part I may try to use the same logic used for login to verify the old password and some registration logic to setup new
I have few doubts though
- do we need the forgot password button( i think it would make sense to keep it there)
- do we need email verification button

**Comment by mlodic** [comment]
please open a draft PR with the changes.

About the doubts: those 2 features are already implemented and those buttons are already available in the Login Page. Here we need to provide the users the chance to change their password if they remember it while they have been logged.

**Comment by shivam-Purohit** [comment]
> About the doubts: those 2 features are already implemented and those buttons are already available in the Login Page. Here we need to provide the users the chance to change their password if they remember it while they have been logged.

My bad. I thought about it then forgot. I will remove the buttons
