### ISSUE TITLE
SHA256 Hash not accepted in Observable SCAN form

### ISSUE THREAD

**Issue by ameygat** [intelowlproject/IntelOwl#129]
Input Hash:
99b24003e4d5a19430653760db6492d920dfda94194ba8aaa9e82d2949aab740

Selected Run All available analyzers

Error:
```
Scan Request Failed!
backend returned: serializer validation failed: {'observable_name': [ErrorDetail(string='Ensure this field has no more than 50 characters.', code='max_length')]} (400: Bad Request)
```

**Comment by Eshaan7** [comment]
Hi. Thank you for your report !

We are about to make a release with version `v1.2.0`. Will push a fix for this in the same.

**Comment by Eshaan7** [comment]
Fixed was released in [https://github.com/intelowlproject/IntelOwl/releases/tag/v1.2.0](v1.2.0).
