### ISSUE TITLE
Script to automate release on LinkedIn

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1299]
It would be super cool to have a Github Action that we could use and also share with the community to share a linkedin post after a release. https://www.linkedin.com/company/86657205

**Comment by tinaoberoi** [comment]
Hi @mlodic 
This seems like an interesting issue, would love to work on this.

**Comment by abheektripathy** [comment]
would like to pick this up @mlodic

**Comment by mlodic** [comment]
abandoned after the try from issue #1672
