### ISSUE TITLE
Improve the web interface

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#13]
At the moment, IntelOwl can be used mainly via APIs because its major intent is to be integrated with other security tools.
So now we can find only a very basic interface that allow the users:
- to authenticate
- to query the database for analysis results
- to view the results via a JSON file

We should start improving the web interface to allow the project to be more user friendly:
- [ ] Add the chance to analyze an observable from the web interface
- [ ] Add the chance to view the analyzer configuration and to change it
- [ ] etc...more ideas are welcome

**Comment by Eshaan7** [comment]
Working on this. Here's a demo I have made: https://intelowlclient.firebaseapp.com/ - Backend integration, authentication and all would be added soon :)

**Comment by Eshaan7** [comment]
**Update**:

New web client for Intel Owl built with angular 9: https://github.com/intelowlproject/intelowl-ng
