### ISSUE TITLE
GitHub actions to automatically generate schema and open a PR automatically after a push to the folders with API views

### ISSUE THREAD

**Issue by 0x0elliot** [intelowlproject/IntelOwl#1302]
We can use something like [this](https://github.com/ArgusOSS/Eye/blob/master/.github/workflows/generate-api-schema.yml). However, I would recommend that we focus on opening a PR bit. It would be way more stable.

**Comment by h4shk4t** [comment]
I would like to work on this issue

**Comment by mlodic** [comment]
you're welcome

**Comment by tinaoberoi** [comment]
This seems like an interesting issue and something would help me get started. @h4shk4t are you working towards it? Else I would love to take this up.

**Comment by mlodic** [comment]
there is an open PR regarding this: https://github.com/intelowlproject/IntelOwl/pull/1375 

if @h4shk4t is not up in a week, we could drop it for inactivity

**Comment by h4shk4t** [comment]
Sorry, was out of station... Will get this up ASAP.

**Comment by tinaoberoi** [comment]
Hi @mlodic, @h4shk4t any updates on this?

**Comment by mlodic** [comment]
ReDoc will be removed
