### ISSUE TITLE
[Analyzer] Criminalip Suggestion

### ISSUE THREAD

**Issue by parkjunmin** [intelowlproject/IntelOwl#1313]
## ## Name
Criminalip

## ## Link
https://www.criminalip.io/

## ## Type of analyzer
**this can be observable, file, and docker**
Shodan, Censys == Cyber Threat Intelligence Platform

## ## Why should we use it
The Criminalip service includes IP Asset Search and Domain Search, which enables analysts or developers to work more accurately and faster using the API in this feature

## ## Possible implementation

**Comment by mlodic** [comment]
thank you! I close this because this is a duplicate! #1240
