### ISSUE TITLE
[Analyzer] HIBP

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1322]
## Name
HIBP

## Link
https://haveibeenpwned.com/

## Type of analyzer
observable -> generic, lookup for this API only: "Getting all breaches for an account"

## Why should we use it
HaveIBeenPwned API are public

## Possible implementation
see doc: https://haveibeenpwned.com/API/v3

**Comment by 0xquark** [comment]
Hey @mlodic! I'd like to work on this

**Comment by mlodic** [comment]
closed with v4.2.0
