### ISSUE TITLE
[Analyzer] Koodus

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1323]
## Name
Koodus

## Link
koodous.com

## Type of analyzer
observable -> hash -> https://docs.koodous.com/api/apks.html#get--apks-(str-sha256)- and https://docs.koodous.com/api/apks.html#get--apks-(str-sha256)-analysis-

## Why should we use it
get information about Android malware. Free quota usage

## Possible implementation
Docs: https://docs.koodous.com/api/

**Comment by shivam-Purohit** [comment]
Hey @mlodic , I am new here . Can you please explain what exactly we are doing here?

**Comment by mlodic** [comment]
https://intelowl.readthedocs.io/en/latest/Contribute.html

**Comment by shivam-Purohit** [comment]
Hey, @mlodic I went through the documentation and installation. Can I take on this?
