### ISSUE TITLE
Quark Engine analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#134]
https://github.com/quark-engine/quark-engine

This tool can be used to assess Android applications.

At a first glance, the problem could be that it is created only for CLI so it could require some work to properly integrate it.

**Comment by Eshaan7** [comment]
Can get started on this as soon as they complete [adding support for JSON output](https://github.com/quark-engine/quark-engine/pull/68).

**Comment by mlodic** [comment]
They completed it with the latest release!!! :rocket: 

https://quark-engine.readthedocs.io/en/latest/integration.html

We can integrate is a simple analyzer
