### ISSUE TITLE
Valid Domains with Second Level domains showing as Invalid

### ISSUE THREAD

**Issue by kinnairdt** [intelowlproject/IntelOwl#136]
When testing some domain submissions i have notice any domain with a second level domain reports as invalid
Tested with:
.co.uk
.co.nz

{
  "is_sample": false,
  "observable_classification": "domain",
  "observable_name": "google.co.uk",
  "analyzers_requested": [],
  "force_privacy": false,
  "disable_external_analyzers": false,
  "running_only": false,
  "run_all_available_analyzers": true,
  "tags_id": []
}

**Comment by Eshaan7** [comment]
Please see https://github.com/intelowlproject/IntelOwl-ng/issues/44
