### ISSUE TITLE
[Analyzer] AdGuard DNS

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1361]
## Name
AdGuard

## Link
https://adguard-dns.io/kb/it/general/dns-providers/

## Type of analyzer
this should be used as domain/url analyzer

## Why should we use it
We can get DNS resolution + whether the analyzed observable is something that the ADGuard service would block or not

## Possible implementation
First analyzer would just be classic dns resolution, without filters: https://unfiltered.adguard-dns.com/dns-query
Second analyzer would be used to detect malicious behavior, use https://dns.adguard-dns.com/dns-query and check for null responses

**Comment by g4ze** [comment]
hwy! @mlodic , are what should the approach be? do we need to imitate ` curl "https://unfiltered.adguard-dns.com/dns=example.com"` ?

**Comment by mlodic** [comment]
that's similar to what we do with Quad9 [here](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/analyzers_manager/observable_analyzers/dns/dns_malicious_detectors/quad9_malicious_detector.py). If the domain can be resolved but the DNS filter filter it, then it means that it's blocked by AdGuard
