### ISSUE TITLE
New plugin subtype: Scanners

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1393]
Inheriting from issue #814 there was the temptation to add active scanners to IntelOwl.

IntelOwl framework allows to easily add external integrations and calls to external services. 
So some people suggested to add active scanners to this project too.
At first we avoided to add those because the goal was different. However right now the tool is ready to accept another form of [plugin](https://intelowl.readthedocs.io/en/latest/Usage.html#plugins), that we could call "scanner" and categorize them differently from the other already existing plugins.

Just to be as accurate as possible. Analyzers plugins would differ from scanners plugins based only on the fact that the first would **NEVER** contact the network observables they analyze, while the other would **ALWAYS** contact the network observables they analyze.
Considering the various implications regarding contacting possible malicious infrastructure, it makes sense to separate them from each other.

The contributor who would take this task would need to touch several parts of the applications to provide everything that is required to have this new plugin to run correctly.

Consequence of this change:
* `rendertron` and `Thug_URL_Info` analyzers are the only active ones ATM and would require to be moved to the "scanner" type

**Comment by mlodic** [comment]
thinking about this again and given the complexity of such customization, we decided to opt out from this option and implement scanners like normal analyzers.

**Comment by moonpatel** [comment]
Hey @mlodic, is there any work for scanners started ?

**Comment by TEMHITHORPHE** [comment]
> thinking about this again and given the complexity of such customization, we decided to opt out from this option and implement scanners like normal analyzers.

Soo . . . should https://github.com/intelowlproject/IntelOwl/issues/1393#issuecomment-1372453230 be disregarded ?
