### ISSUE TITLE
Add Scorecard as Github action

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1414]
reference here: https://github.com/ossf/scorecard-action

Once done, we can:
* open new issues to fix detected problems
* add the badge in the ReadMe

**Comment by 0xquark** [comment]
Hi, this project caught my eye and I'm really interested in working on it. I went ahead and created a draft PR with the workflow setup. My bad for not assigning the task first, I didn't realize it until when I read the contributing guidelines while making the PR.

**Comment by mlodic** [comment]
yeh, exactly, you should ask to be assigned first but we can consider this as an exception. I'll check your PR
