### ISSUE TITLE
[Analyzer] Knock

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1418]
## Name
Knock

## Link

https://github.com/guelfoweb/knock

## Type of scanner
observable: https://github.com/guelfoweb/knock#module

## Why should we use it
It is a useful reconnaissance tool

## Possible implementation
see: https://github.com/guelfoweb/knock#module

**Comment by tinaoberoi** [comment]
Hi @mlodic
I am interested in working on this issue. I am new here, could you explain a bit more about the purpose for adding knock here?
And if we should add knock in the package file?

**Comment by mlodic** [comment]
this issue required another issue (#1393) to be completed
