### ISSUE TITLE
Triage analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#142]
We could create a file analyzers that leverages Triage Sandbox. https://tria.ge
Recently, they added the chance to request a free "researcher" account that can leverage their API to programmatically start sandbox analysis and retrieve results. https://tria.ge/docs/cloud-api/

**Comment by m0mosenpai** [comment]
I would like to work on this issue. Anything I should keep in mind?

**Comment by mlodic** [comment]
Hey @m0mosenpai, I have just assigned you!

Some tips:
* we should give the option to specify if the user wants to leverage the public API or the private one (they are different URLs). I would put the public one as default.
* we could implement 2 different analyzers:
    * one for the "search" option to give the users the chance to look for observables (https://tria.ge/docs/cloud-api/search/). This would be an observable analyzer
    * one for the "analysis" option to give the users the chance to analyze a submitted file (https://tria.ge/docs/cloud-api/samples/#post-samples) and retrieve the results once the analysis is finished. This would be a file analyzer

Please check how much API requests you can perform with the free license. At a first glance I did not find this information.

**Comment by m0mosenpai** [comment]
I messaged their support to ask about the request limit since I couldn't find that info on their website either. They said from a few hundred to a few thousand per day (whatever we think is reasonable).

**Comment by m0mosenpai** [comment]
The `/samples` endpoint also allows submitting a sample via a URL. Would that be a part of the observable analyzer too? If so, maybe I could add that as an `additional_config_params`, whether to submit a sample via URL or search for one?

**Comment by mlodic** [comment]
1 - I agree. If you can, try to reuse the code from the file analyzer for that case.

2 - IntelOwl allows to pivot only IPs, URLs, domains and hashes ATM. This means that the analyzer should change the query based on what is requested: `url:{url}` for instance
