### ISSUE TITLE
Search Engine on Report Results

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1438]
Right now IntelOwl lacks of advanced search capabilities. The users can only lookup for basic fields in the reports from the "Job History" table:

![image](https://user-images.githubusercontent.com/30625432/213743297-90efce9b-b119-4e47-97ae-7ede397ebcba.png)

If an user would like to do "threat hunting" on the performed analysis there is nothing in the application by default that helps in that manner.

The only chance available is to spin up ElasticSearch together with IntelOwl:
https://intelowl.readthedocs.io/en/latest/Advanced-Usage.html#elastic-search

However, right now, that integration leverages Kibana which is another frontend application that would need to be supported.

It would be cool to have an additional input field in the "Job History" page where the Elastic Query Language is supported and would do lookups against the ElasticSearch backend instead of the PostgreSQL DB. (something similar was implemented in [MwDB](https://mwdb.cert.pl/))

Considering that ElasticSearch is not a "soft" addition in terms of resources, we would need to keep it _not_ installed by default and explicitly say in the documentation and in the application that this feature would require ElasticSearch installation.

**Comment by siddhanthrathod** [comment]
Can I try this ?

**Comment by 0ssigeno** [comment]
Another compromise, without having to use ElasticSearch, is to use [postgresql text search](https://www.postgresql.org/docs/current/textsearch.html). [Django](https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/search/) already implements this.
The scoring system should be a little worse than ElasticSearch, but it could be a good compromise.

**Comment by mlodic** [comment]
merged with 6.2.0
