### ISSUE TITLE
Integration/connectors for other threat intel projects

### ISSUE THREAD

**Issue by pynixadm** [intelowlproject/IntelOwl#144]
Suggestions from this comment:
https://www.reddit.com/r/blueteamsec/comments/i6j6ur/tool_intel_owl_free_and_open_source_threat/g10ucax/

1. - [ ] Add a section for possible resolved urls/hostnames in an IP lookup (reverse ip lookups, etc)

2. - [x] Is there a way to remove the max character limit when looking up a URL (128 chars)? The first spam url lookup I did hit it. (Added in #147)

3. - [x] Add a way to configure analyzers in the GUI. (#111)

4. - [ ] Add a splunk integration (or Graylog), not sure how you'd work this though as the lookup would vary quite a bit depending on the environment

5. - [ ] See if any SIEM or SOAR projects will work with you to add integration to their projects. (Related discussion on #176)

**Comment by mlodic** [comment]
Issue n.1) Reverse IP lookups should have worked with the `ActiveDNS_Classic` analyzer but I just noticed that it is bugged. We will push the fix in the next release. Also, the other 2 analyzers that performs DNS requests via HTTPS (`ActiveDNS_CloudFlare` and `ActiveDNS_Google`) do not support reverse lookups at the moment but, in the future, they will. I will update this issue as soon as we make changes. 
Moreover you could possibly be interested in passive DNS records. Those kind of data can be extracted from other (already available) different analyzers that integrate external services like VirusTotal, OTX AlienVault, SecurityTrails, DNSDB, etc

Issue n.2) resolved by @Eshaan7 in v 1.3.0

Issue n.3) This is a good idea but would require some work. In my opinion, at the moment, it is pretty simple and fast to configure the analyzers, even without the GUI. Therefore I think we could plan this for later.

Issue n.4) We are interested to learn more about that and your use cases. We are not splunk or graylog experts so, a help in this would be really appreciated. If you prefer a more direct conversation you can DM me on Twitter at any time

Issue n.5) IMHO, our main focus should be to integrate our project with other full OS projects before performing integration with vendors. In this way, the community would benefit more from our work. Therefore I think that we can plan this for later or we can ask them for help for the previous issue if we do not resolve issue n.4 by our own

**Comment by Eshaan7** [comment]
Hey, @pynixadm. Regarding point #3, You can checkout the latest [**v1.5.0**](https://github.com/intelowlproject/IntelOwl/releases/tag/v1.5.0) release. We have added a way to change analyzers configuration when requesting scan.

**Comment by un-fuf-a-doo** [comment]
I can help with number 4, I know Graylog inside and out in regards to setting it up and bringing in data. It wouldn't be that different than what you did for Elastic, except Graylog accepts a long list of input types, including raw JSON. Think of it like outputting to an external syslog.

**Comment by mlodic** [comment]
thanks for your proposal @un-fuf-a-doo. As mentioned, we do not know well those technologies so we would need a thorough external help to complete that feature. Also, we would like to understand the use cases of such integration so we can analyze the benefits that it would provide to IntelOwl.

Are you interested in contributing with code/configuration?

**Comment by mlodic** [comment]
closing until new resources/sponsorship come to implement such integrations
