### ISSUE TITLE
Playbooks should not break if an analyzer is deleted

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1454]
This is an edge case. If an analyzer available in a playbook is deleted in any way, that playbook becomes broken.

The correct thing should be to have the playbook shown as it was disabled

**Comment by 0x0elliot** [comment]
hey, are you still working on this @0ssigeno? i can help out here if you like.

**Comment by 0ssigeno** [comment]
In the `visualizer` branch the delete is doable via API if you are an administrator.
We can develop the feature (once we merged that branch) in this way:
- add a GUI button (or something) to allow the deletion
- add an `user` to each Playbook model
- only the owner of the playbook is allowed to delete its playbook
- at this moment, the playbooks are still global, meaning that every user see every playbook ( we can develop further this point in a second moment)
