### ISSUE TITLE
Add chance to delete a created Playbook from the GUI

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1455]
Right now there is no chance to delete a created Playbook. We should add a trash button in the "Plugins" section where it is possible to delete the Playbook, after a confirmation request.

**Comment by shivam-Purohit** [comment]
hey can I work on this?

**Comment by 0x0elliot** [comment]
let me know if you need help here @shivam-Purohit

**Comment by mlodic** [comment]
This has been addressed with proper buttons
