### ISSUE TITLE
Subdomain not valid

### ISSUE THREAD

**Issue by soelkongen** [intelowlproject/IntelOwl#146]
When I input a subdomain for scanning, it will give the error "Invalid domain".

**Comment by Eshaan7** [comment]
Thankyou for your report. Are you using the web interface or the CLI client ?

**Comment by soelkongen** [comment]
> Thankyou for your report. Are you using the web interface or the CLI client ?

Web interface

**Comment by Eshaan7** [comment]
The same issue was reported earlier https://github.com/intelowlproject/IntelOwl-ng/issues/47 and the fix will be released very soon as part of `v1.3.0` release.
