### ISSUE TITLE
Adjust Yara and Quark rules update for cluster deployments

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1474]
The problem is that, right now, the rules are written to the disk and read from there. This obviously doesn't work in cluster deployments (that we are about to add support) because we would need to update that repo in all of the machines of the cluster.

We need to find a way to save these rules in a centralized point and use them from there.
The problem is shared by all the analyzers that leverage MEDIA_ROOT as a shared folder.

A possible idea from @0ssigeno :

> We should save in the s3 bucket every yara repo and the hash commit of it.
The cron will update them directly on the bucket, exactly like it is done now.
The yara analyzer will verify the local hash commit with the remote one. If there is a discrepancy, then the rules are downloaded from s3.

**Comment by mlodic** [comment]
closed with #1522

**Comment by 0ssigeno** [comment]
#1531 manage update using a broadcast approach
