### ISSUE TITLE
[Analyzer]CyCat

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1479]
## Name
CyCat

## Link
https://cycat.org/about/

## Type of analyzer
generic analyzer:
* if a UUID is submitted, perform UUID lookup
* else perform full text search and then UUID lookups of the results

## Why should we use it
Encyclopedia of cyber security resources

## Possible implementation
follow docs here:https://cycat.org/services/

**Comment by g4ze** [comment]
Can I be assigned this issue as well?

**Comment by g4ze** [comment]
Great! All clear :)
