### ISSUE TITLE
[Analyzer] Crowdsec

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1509]
## Link
https://app.crowdsec.net/cti

## Type of analyzer
observable -> ip address only

## Why should we use it
open source intelligence

## Possible implementation
ex: https://cti.api.crowdsec.net/v2/smoke/185.7.214.104
https://doc.crowdsec.net/docs/next/cti_api/intro/

**Comment by LaurenceJJones** [comment]
Hey @mlodic just a FYI we have released a free CTI key to all community plans today. This should allow all users to use the analyzer and benefit from the CTI data we have.

**Comment by mlodic** [comment]
I have added the analyzer. See #1558 . At the next release it will be available to the public. I'll ping you once that happen :)

**Comment by mlodic** [comment]
solved in v4.2.2
