### ISSUE TITLE
[Analyzer] MalProb

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1521]
## Name
 Malprob

## Link
https://malprob.io

## Type of analyzer
observable (hash) analyzer: hash check: https://malprob.io/api#tag/Searching
and
file analyzer: send file for scan in case the hash is not available: https://malprob.io/api#tag/Scanning/operation/scan_create. Otherwise perform a rescan

## Why should we use it
AI sandbox

## Possible implementation
https://malprob.io/api

**Comment by moonpatel** [comment]
New API docs link:
- observable (hash) analyzer: hash check: https://malprob.io/openapi#tag/Searching
- file analyzer: https://malprob.io/openapi#tag/Scanning

**Comment by g4ze** [comment]
Hey! @mlodic we want to peeform arescan everytime after a file scan?
We have to create two different analyzers? one for observable hash, one for file?

**Comment by mlodic** [comment]
> We have to create two different analyzers? one for observable hash, one for file?

yes, you can copy similar approach we had with Triage or Virustotal for instance.

We want to avoid to do useless file uploads if the hash has already been analyzed in the service. Plus, only with TLP:CLEAR a file should be uploaded

Plus, if we have an hash only, we would like analyze that only.

**Comment by g4ze** [comment]
So we make two different modules and analyzers? One which is for observable hash and one for file?
