### ISSUE TITLE
[Analyzer] SURBL & Spamhaus DBL

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1526]
## Name
1 - SURBL_Malicious_Detector
2 - Spamhaus_DBL_Malicious_Detector

## Link
https://www.spamhaus.org/faq/section/Spamhaus%20DBL#271

## Type of analyzer
observable -> domain only
We can check whether a domain is blocked or not by their DNS

## Why should we use it
it is an easy way to check whether a domain is listed in those services as malicious or not.

## Possible implementation
Should be similar to the other DNS-based malicious detectors

**Comment by g4ze** [comment]
Hey! @mlodic  i was going through their site and came across the signup form. Here again, it requires me to have my own email server. 
![image](https://github.com/intelowlproject/IntelOwl/assets/102874321/704a3791-2b3e-4a78-87ab-09dd0a1c68a7)

**Comment by mlodic** [comment]
what they want to do here is to avoid abuse cause they expect you to use these blacklists on your own servers for protection. If you check the [terms of usage](https://www.spamhaus.com/terms-of-use-fair-use-policy-for-free-data-query-service/), there's no actual limit or real imposition that impede you to register and flag that checkbox anyway. We are not doing a bad thing by leveraging this service.

**Comment by g4ze** [comment]
hey! i can see [here](https://docs.spamhaus.com/datasets/docs/source/70-access-methods/web-query-service/080-examples.html) that we can also lookup ip observables as well. Why don't we implement that too?

**Comment by g4ze** [comment]
> 1 - SURBL_Malicious_Detector
> 2 - Spamhaus_DBL_Malicious_Detector

These are two different analyzers or just name options? if two different analyzers then what does SURBL does?

**Comment by mlodic** [comment]
I think things has changed since the time I wrote this issue. Feel free to follow their docs and the actual available options, like you suggested

**Comment by g4ze** [comment]
[here](https://docs.spamhaus.com/sia/docs/source/01-intro/what-is-sia.html) is another interesting service they provide with their SIA api. It's more of a reputation score provider for domains and ips. I think this can be completely another analyzer if required, as it contains a lot of useful endpoints. It gives us 5000 queries/mo

**Comment by mlodic** [comment]
agree!
