### ISSUE TITLE
[Analyzer] Hunter.how

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1528]
## Name
Hunter_How (we should rename the other "Hunter" into "Hunter_Io" to distinguish between them 

## Link
https://hunter.how

## Type of analyzer
generic -> free text queries

## Why should we use it
Alternative to Shodan. Basic free API access

## Possible implementation
https://hunter.how/search-api
We should support all the available parameters

**Comment by shivam-Purohit** [comment]
@mlodic can I work on this?

**Comment by mlodic** [comment]
solved in v4.2.2
