### ISSUE TITLE
Analyzer Healtcheck and Update should be visible only if the requester is a superuser

### ISSUE THREAD

**Issue by 0ssigeno** [intelowlproject/IntelOwl#1532]
At the moment, every user is able to click on the `Healtcheck` button, while the backend accept only superuser. 
![image](https://user-images.githubusercontent.com/30528879/219079731-41c0a808-e61f-48d7-971b-17e6c3f7c719.png)
We should change the frontend to allow only superuser to see the `healtcheck` action.
Moreover, we should implement the `Update`, using the `AnalyzerUpdateAPI view` implemented in #1531, clustering them together in a single column called `Actions` or something

**Comment by shivam-Purohit** [comment]
@mlodic I was not able to complete it last time can i try this one more time?

**Comment by mlodic** [comment]
that has been already solved.
