### ISSUE TITLE
Secrets can only be added in JSON-Format

### ISSUE THREAD

**Issue by ClaudioWayne** [intelowlproject/IntelOwl#1541]
## What happened

I have to instances of IntelOwl

First one : 4.2.0 (Commit 792348efdd58cd7bc02efb69bb9e69888af9e51b)

I tried to add a secret for an Analyser via a normal string (note the question marks in value-field) and i got a 400 Bad Request.

![notWorking1](https://user-images.githubusercontent.com/35531629/219630690-161d4487-20e5-400f-9b7a-7c9481c7c3c3.png)
![notWorking2](https://user-images.githubusercontent.com/35531629/219630957-ffd0ec65-1c43-4bb6-a7c6-22695abc0a62.png)

--------------------------------------------------------------------------------------------------------

So i tried it via Django Admin Interface and i got the error: Enter invalid JSON

![notWorking3](https://user-images.githubusercontent.com/35531629/219630444-f64c8fa3-57c4-409c-b28c-5d6f7b2e4f51.png)

--------------------------------------------------------------------------------------------------------

If i enter Secret in JSON Format it works via Django Admin and via GUI

![notWorking5](https://user-images.githubusercontent.com/35531629/219632215-98bfff47-3e32-4071-a5b0-f1c7c9084ee2.png)
![notWorking7](https://user-images.githubusercontent.com/35531629/219631830-4003cfb5-8362-419c-8991-8ffeb71cd215.png)
![Screenshot from 2023-02-17 10-45-44](https://user-images.githubusercontent.com/35531629/219633260-9be6eb6f-7eea-423d-b3ce-1a755b6d9a9e.png)
![working2](https://user-images.githubusercontent.com/35531629/219635668-9b8798c2-227a-465b-a555-35a62eb11e66.png)

--------------------------------------------------------------------------------------------------------

Second One: 4.1.5 (Commit d6aa61be3bc8535d89c4de616f35675ed9eaf921)

Everything works with normal strings (there is string in the value-field instead of question marks)
![working1](https://user-images.githubusercontent.com/35531629/219635825-81eec100-6ced-4d74-b9c4-a2ecdbca9ad6.png)
![working2](https://user-images.githubusercontent.com/35531629/219635888-955b90d3-fccb-410f-a993-a0c0cc46fad1.png)

--------------------------------------------------------------------------------------------------------
Am I missing something? Or can someone help me out?

## Environment
1. OS: Ubuntu 22.04.1 LTS
2. IntelOwl version: 4.2.0 (Commit 792348efdd58cd7bc02efb69bb9e69888af9e51b)

##  What did you expect to happen

add a Secret via normal string

## How to reproduce your issue

git clone https://github.com/intelowlproject/IntelOwl
cd IntelOwl/

cd docker/
cp env_file_app_template env_file_app
cp env_file_postgres_template env_file_postgres
cp env_file_integrations_template env_file_integrations

cd ..
./initialize.sh

python3 start.py prod up

docker exec -ti intelowl_uwsgi python3 manage.py createsuperuser

login via superuser

add secret for VirusTotal_v3_Get_Observable

## Error messages and logs

400 Bad Request
Enter a valid JSON

**Comment by mlodic** [comment]
thank you for the extremely detailed report!

We are already aware of the problem and I have already fixed it. I have already opened a PR #1540 

 We did some refactor and that may have broken that feature.

We'll push a fix release within today if we can.

**Comment by ClaudioWayne** [comment]
yaw
thx for quick reply,fix and the whole project.
