### ISSUE TITLE
[Analyzer] AILTypoSquatting

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1545]
## Name
AILTypoSquatting

## Link

https://github.com/ail-project/ail-typo-squatting

## Type of analyzer
observable -> domain

## Why should we use it
Project similar to DNStwist, it allows to extract potential typosquatted domains with several algorithms

## Possible implementation
see: https://github.com/ail-project/ail-typo-squatting

**Comment by 0xquark** [comment]
Hi @mlodic! I'd like to take this issue
