### ISSUE TITLE
Add PeFrame

### ISSUE THREAD

**Issue by vxsh4d0w** [intelowlproject/IntelOwl#157]
Adding Peframe to IntelOwl could be a gret improvement in order to extract quickly and well formatted info about a pe file.

**Comment by Eshaan7** [comment]
PEframe is already integrated :smile: 

Please look at the (Advanced-Usage.html)[https://intelowl.readthedocs.io/en/develop/Advanced-Usage.html#optional-analyzers] in the documentation.

**Comment by vxsh4d0w** [comment]
You're right...I didn't notice it. :D 👍
