### ISSUE TITLE
[Analyzer] DetectItEasy

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1590]
## Name

DetectItEasy

## Link

https://github.com/horsicq/Detect-It-Easy

## Type of analyzer
Docker analyzer to be integrated in the malware_analysis_tools container.
Supports only executable files

## Why should we use it
Very famous tools to detect packers, compilers, linkers, etc

## Possible implementation
the command line version allows the JSON output with the option `--json`

**Comment by abheektripathy** [comment]
@mlodic would like to pick this up next.

**Comment by g4ze** [comment]
Hey! I'd like to work on this.
