### ISSUE TITLE
[improved Analyzer] Add dotnetfile to PE_Info

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1592]
We could add .NET written files in PE_Info and, in case it matches, we could run the package `dotnetfile`  (https://github.com/pan-unit42/dotnetfile) to extract static info from it

**Comment by g4ze** [comment]
hey! @mlodic  The approach we want here is to check the file type  [here](https://github.com/intelowlproject/IntelOwl/blob/42f874fdd5dd084556be6e038068e38cc9dae601/api_app/analyzers_manager/file_analyzers/pe_info.py#L48), if the file was assembled from .net then we run `dotnetfile` . what informations should we dump in the results?

**Comment by mlodic** [comment]
yes. To understand whether a it is a .net file or not there are many tricks, one of those is 
```
            file_type = magic.from_buffer(self.binary)
            if ".Net" in file_type:
``` 

Then, from the dotnetfile you can create a dictionary of results based on the suggestions made here by the creator himself:
https://github.com/pan-unit42/dotnetfile/blob/c7ce2c58657ebfca44a27bd464e093af427301d8/examples/dotnetfile_dump.py#L24
Just take the "general information" that are extracted in those prints.

Does it make sense ?

**Comment by g4ze** [comment]
yes, makes sense.

**Comment by g4ze** [comment]
is there someway I can get a safe sample file to test, without having to compile some project?
