### ISSUE TITLE
Add chance to add comments to Jobs

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1611]
Right now there is no chance to add any comment to the jobs results. It would be cool to add this opportunity to enable people to collaborate better directly inside the platform

**Comment by 0x0elliot** [comment]
can i help with this feature?

**Comment by 0x0elliot** [comment]
i am assigning myself to this

**Comment by mlodic** [comment]
sure man :)

**Comment by eshaan7** [comment]
Should we support markdown in these notes/comments?

**Comment by mlodic** [comment]
that would be cool

**Comment by mlodic** [comment]
this has been recently merged in `develop`. We consider addressed the issue
