### ISSUE TITLE
External Observable Sources

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#165]
I see that Spiderfoot [integrates different analyzers](https://www.spiderfoot.net/documentation/#api) most of which we already have. What we could do is scan their list of analyzers and see the ones which could be useful to Intel Owl.
_Originally posted by @Eshaan7 in https://github.com/intelowlproject/IntelOwl/issues/110#issuecomment-656270374_

**Comment by subhashissuara** [comment]
Hello @Eshaan7, I am interested to work on this issue. Can you help me with more details? Thank you

**Comment by Eshaan7** [comment]
> Hello @Eshaan7, I am interested to work on this issue. Can you help me with more details? Thank you

We want to see what analyzers spiderfoot has that IntelOwl doesn't but could be useful to IntelOwl too. You will see that many analyzers/sources would be same in both projects since the projects have some similar functionalities.

If you find a analyzer/source/service (whether it's part of spiderfoot or no) that you feel could be an useful addition to IntelOwl, create an issue mentioning it. If it gets approved, you are more than welcome to raise a PR for it!
