### ISSUE TITLE
Jobs is not proceeding from Pending

### ISSUE THREAD

**Issue by mrrobotnl** [intelowlproject/IntelOwl#1652]
## What happened
Hey Community, 

I tried to start a new job with the regular playbook (FREE_TO_USE_ANALYZERS) but my job is stuck at pending. I also tried after 1,5 hours to start another job to confirm that it does not work, and I got the same result over there. 
## Environment
1. OS: Ubuntu 22.04 Desktop edition 
2. IntelOwl version: Version 2.3.4 (Most recent) 

## How to reproduce your issue
I setup a regular job to scan a domain, I used both the default playbook that I mentioned above and the regular Analyzer. 

## Error messages and logs
Schedular: Sending due task tor_updater(intel_owl.tasks.tor.updater)
Schedular: Sending due task tor_updater(intel_owl.tasks.check_stuck_analysis)

**Comment by mlodic** [comment]
Could you please share the stack trace you get in your application?

**Comment by mlodic** [comment]
you can ignore the errors for the `intelowl_cache` for now. That caching mechanism will be also removed in the next release.

Could you please tell me if any other possible job remains in `pending` status? If that is the case, it is possible that there is something wrong in your local configuration.

Are the containers running correctly? Output of `sudo docker ps`?

Also logs from `/var/lib/docker/volumes/intel_owl_generic_logs/_data/django/` could be useful

**Comment by mrrobotnl** [comment]
**Docker logs from sudo docker ps**
6c89fdd8bb8   intelowlproject/intelowl:v4.2.3         "./docker/entrypoint…"   3 hours ago    Up 3 hours                                                                   intelowl_celery_beat
aeaa9856dff4   intelowlproject/intelowl:v4.2.3         "./docker/entrypoint…"   3 hours ago    Up 3 hours (healthy)   8001/tcp                                              intelowl_uwsgi
24b2051c279b   intelowlproject/intelowl_nginx:v4.2.3   "/docker-entrypoint.…"   20 hours ago   Up 3 hours (healthy)   0.0.0.0:80->80/tcp, :::80->80/tcp                     intelowl_nginx
ac6647448619   postgres:12-alpine                      "docker-entrypoint.s…"   20 hours ago   Up 20 hours            5432/tcp                                              intelowl_postgres
febc852c94fc   rabbitmq:3.11-alpine                    "docker-entrypoint.s…"   20 hours ago   Up 3 hours             4369/tcp, 5671-5672/tcp, 15691-15692/tcp, 25672/tcp   intelowl_rabbitmq

I am going to restart the system perhaps this will help

**Comment by mlodic** [comment]
an important container is missing in the count:
`intelowl_celery_worker_default`. That is the reason why jobs are still in pending.

with `docker container ls -a` you can see all the containers and you should get the error of that container which did not work

**Comment by mrrobotnl** [comment]
Hey Mlodic, I do not know what I did but after reinstalling the framework and restarting it did worked. Thanks for the help
