### ISSUE TITLE
[Analyzer] Abusix

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1663]
## Name
Abusix

## Link
https://abusix.com/contact-db/

## Type of analyzer
observable -> IP address only. This could leverage some code already used for other DNS-based analyzers. Otherwise you could use the python library

## Why should we use it
get abuse contacts easily and for free

## Possible implementation
https://docs.abusix.com/abuse-contact-db/5BScLdS3SxHV1giQYpXpKm/getting-started/rGzH6UQZpzjXBhqtjNqRee

**Comment by moonpatel** [comment]
Please assign me this issue @mlodic !
