### ISSUE TITLE
401 Error 

### ISSUE THREAD

**Issue by mrrobotnl** [intelowlproject/IntelOwl#1670]
## What happened
I am trying to setup a stable version of IntelOwl for my prototype for a while now but I always seeing to run against an error that I can’t explain. 
It do recure when the framework is up for a day or two and I really need to fix this issue. When I log in the framework I am greeted with the following error code: 
401 | Unautorized 
Invalid token 

I also see the following error code 
Error! 
500 | Internal server error

Any ideas? 
## Environment
1. OS: Ubuntu 22.04 
2. IntelOwl version: 4.2.3 
##  What did you expect to happen
Every time I setup the framework I get the same error (look in the picture in the previous chapter.)
## How to reproduce your issue
Just set up the framework, I did connect it with an external elasticsearch and kibana (as described in the advance use docs)
## Error messages and logs
celery_worker_default | [2023-04-26 06:25:00,089: INFO/MainProcess] Task intel_owl.tasks.check_stuck_analysis[94745ca1-ba02-48f1-bc92-4c2c42fa8c27] received
intelowl_celery_worker_default | [2023-04-26 06:25:00,091: INFO/ForkPoolWorker-1] started check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:25:00,092: INFO/ForkPoolWorker-1] checking if 0 jobs are stuck
intelowl_celery_worker_default | [2023-04-26 06:25:00,092: INFO/ForkPoolWorker-1] finished check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:25:00,100: INFO/ForkPoolWorker-1] Task intel_owl.tasks.check_stuck_analysis[94745ca1-ba02-48f1-bc92-4c2c42fa8c27] succeeded in 0.00909993400273379s: None
intelowl_celery_beat     | [2023-04-26 06:30:00,094: INFO/MainProcess] Scheduler: Sending due task tor_updater (intel_owl.tasks.tor_updater)
intelowl_celery_beat     | [2023-04-26 06:30:00,095: INFO/MainProcess] Scheduler: Sending due task check_stuck_analysis (intel_owl.tasks.check_stuck_analysis)
intelowl_celery_worker_default | [2023-04-26 06:30:00,096: INFO/MainProcess] Task intel_owl.tasks.tor_updater[58b8b663-477a-4866-b531-f167577623cc] received
intelowl_celery_worker_default | [2023-04-26 06:30:00,098: INFO/MainProcess] Task intel_owl.tasks.check_stuck_analysis[bd852be2-05de-4648-82ff-f25ba2cb3560] received
intelowl_celery_worker_default | [2023-04-26 06:30:00,099: INFO/ForkPoolWorker-2] started check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:30:00,101: INFO/ForkPoolWorker-2] checking if 0 jobs are stuck
intelowl_celery_worker_default | [2023-04-26 06:30:00,101: INFO/ForkPoolWorker-2] finished check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:30:00,112: INFO/ForkPoolWorker-2] Task intel_owl.tasks.check_stuck_analysis[bd852be2-05de-4648-82ff-f25ba2cb3560] succeeded in 0.012880203998065554s: None
intelowl_celery_worker_default | [2023-04-26 06:30:00,357: INFO/ForkPoolWorker-1] about to send broadcast to queue default for plugin TorProject
intelowl_celery_worker_default | [2023-04-26 06:30:00,359: INFO/ForkPoolWorker-1] sent broadcast to queue default for plugin TorProject
intelowl_celery_worker_default | [2023-04-26 06:30:00,368: INFO/ForkPoolWorker-1] Task intel_owl.tasks.tor_updater[58b8b663-477a-4866-b531-f167577623cc] succeeded in 0.27020831299887504s: None
intelowl_celery_worker_default | [2023-04-26 06:30:00,370: INFO/MainProcess] starting download of db from tor project
intelowl_celery_worker_default | [2023-04-26 06:30:00,521: INFO/MainProcess] ended download of db from tor project
intelowl_celery_beat     | [2023-04-26 06:35:00,093: INFO/MainProcess] Scheduler: Sending due task check_stuck_analysis (intel_owl.tasks.check_stuck_analysis)
intelowl_celery_worker_default | [2023-04-26 06:35:00,095: INFO/MainProcess] Task intel_owl.tasks.check_stuck_analysis[2af3d177-7be4-491c-9646-9dcf28550078] received
intelowl_celery_worker_default | [2023-04-26 06:35:00,096: INFO/ForkPoolWorker-1] started check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:35:00,098: INFO/ForkPoolWorker-1] checking if 0 jobs are stuck
intelowl_celery_worker_default | [2023-04-26 06:35:00,099: INFO/ForkPoolWorker-1] finished check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:35:00,104: INFO/ForkPoolWorker-1] Task intel_owl.tasks.check_stuck_analysis[2af3d177-7be4-491c-9646-9dcf28550078] succeeded in 0.007685221004066989s: None
intelowl_celery_beat     | [2023-04-26 06:40:00,088: INFO/MainProcess] Scheduler: Sending due task check_stuck_analysis (intel_owl.tasks.check_stuck_analysis)
intelowl_celery_beat     | [2023-04-26 06:40:00,089: INFO/MainProcess] Scheduler: Sending due task tor_updater (intel_owl.tasks.tor_updater)
intelowl_celery_worker_default | [2023-04-26 06:40:00,091: INFO/MainProcess] Task intel_owl.tasks.check_stuck_analysis[6df6edd2-300c-4529-9914-114fbd3bf6fe] received
intelowl_celery_worker_default | [2023-04-26 06:40:00,092: INFO/ForkPoolWorker-1] started check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:40:00,094: INFO/ForkPoolWorker-1] checking if 0 jobs are stuck
intelowl_celery_worker_default | [2023-04-26 06:40:00,094: INFO/ForkPoolWorker-1] finished check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:40:00,095: INFO/MainProcess] Task intel_owl.tasks.tor_updater[c868b388-4318-4b74-ba08-4870e5b5460f] received
intelowl_celery_worker_default | [2023-04-26 06:40:00,103: INFO/ForkPoolWorker-1] Task intel_owl.tasks.check_stuck_analysis[6df6edd2-300c-4529-9914-114fbd3bf6fe] succeeded in 0.010881294001592323s: None
intelowl_celery_worker_default | [2023-04-26 06:40:00,103: INFO/ForkPoolWorker-2] about to send broadcast to queue default for plugin TorProject
intelowl_celery_worker_default | [2023-04-26 06:40:00,113: INFO/ForkPoolWorker-2] sent broadcast to queue default for plugin TorProject
intelowl_celery_worker_default | [2023-04-26 06:40:00,118: INFO/ForkPoolWorker-2] Task intel_owl.tasks.tor_updater[c868b388-4318-4b74-ba08-4870e5b5460f] succeeded in 0.02198042300005909s: None
intelowl_celery_worker_default | [2023-04-26 06:40:00,124: INFO/MainProcess] starting download of db from tor project
intelowl_celery_worker_default | [2023-04-26 06:40:00,254: INFO/MainProcess] ended download of db from tor project
intelowl_celery_beat     | [2023-04-26 06:45:00,085: INFO/MainProcess] Scheduler: Sending due task check_stuck_analysis (intel_owl.tasks.check_stuck_analysis)
intelowl_celery_worker_default | [2023-04-26 06:45:00,087: INFO/MainProcess] Task intel_owl.tasks.check_stuck_analysis[0d28dbe3-39e0-4f44-9a63-b4c4254f3b32] received
intelowl_celery_worker_default | [2023-04-26 06:45:00,089: INFO/ForkPoolWorker-1] started check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:45:00,091: INFO/ForkPoolWorker-1] checking if 0 jobs are stuck
intelowl_celery_worker_default | [2023-04-26 06:45:00,091: INFO/ForkPoolWorker-1] finished check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:45:00,097: INFO/ForkPoolWorker-1] Task intel_owl.tasks.check_stuck_analysis[0d28dbe3-39e0-4f44-9a63-b4c4254f3b32] succeeded in 0.007899275995441712s: None
intelowl_celery_beat     | [2023-04-26 06:50:00,131: INFO/MainProcess] Scheduler: Sending due task tor_updater (intel_owl.tasks.tor_updater)
intelowl_celery_worker_default | [2023-04-26 06:50:00,133: INFO/MainProcess] Task intel_owl.tasks.tor_updater[20464e58-efbe-46c1-aba4-479e1ab4522f] received
intelowl_celery_beat     | [2023-04-26 06:50:00,132: INFO/MainProcess] Scheduler: Sending due task check_stuck_analysis (intel_owl.tasks.check_stuck_analysis)
intelowl_celery_worker_default | [2023-04-26 06:50:00,135: INFO/MainProcess] Task intel_owl.tasks.check_stuck_analysis[25246695-7e3c-4e1c-8e64-9432a4de4313] received
intelowl_celery_worker_default | [2023-04-26 06:50:00,137: INFO/ForkPoolWorker-2] started check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:50:00,139: INFO/ForkPoolWorker-2] checking if 0 jobs are stuck
intelowl_celery_worker_default | [2023-04-26 06:50:00,139: INFO/ForkPoolWorker-2] finished check_stuck_analysis
intelowl_celery_worker_default | [2023-04-26 06:50:00,145: INFO/ForkPoolWorker-1] about to send broadcast to queue default for plugin TorProject
intelowl_celery_worker_default | [2023-04-26 06:50:00,147: INFO/ForkPoolWorker-1] sent broadcast to queue default for plugin TorProject
intelowl_celery_worker_default | [2023-04-26 06:50:00,157: INFO/ForkPoolWorker-2] Task intel_owl.tasks.check_stuck_analysis[25246695-7e3c-4e1c-8e64-9432a4de4313] succeeded in 0.020288478990551084s: None
intelowl_celery_worker_default | [2023-04-26 06:50:00,159: INFO/ForkPoolWorker-1] Task intel_owl.tasks.tor_updater[20464e58-efbe-46c1-aba4-479e1ab4522f] succeeded in 0.025296787003753707s: None
intelowl_celery_worker_default | [2023-04-26 06:50:00,164: INFO/MainProcess] starting download of db from tor project
intelowl_celery_worker_default | [2023-04-26 06:50:00,313: INFO/MainProcess] ended download of db from tor project

**Comment by mlodic** [comment]
@mrrobotnl did you solve the problem? if yes, could you please tell us what it was? it could be helpful for other users facing the same error. ty

**Comment by mrrobotnl** [comment]
Yes, I have no clue. After restarting a couple of times it seemed to work after that. Now I do turn the framework of every weekend with the hope I solve the problem like that. But I do have another issue / question that you may help me with @mlodic mlodic. 
It is about the question #1671 that is open for a couple of days and it is the only part for my prototype that I need to get working.
