### ISSUE TITLE
Enhance job page URL

### ISSUE THREAD

**Issue by drosetti** [intelowlproject/IntelOwl#1680]
The job section is divided into "visualizers" and "raw data" then each subsection is divided into a list of visualizers or plugins (analyzers/connectors/visualizers). Each plugins is a list of elements.
It could be usefult to change the URL to something like:
`.../jobs/<id>/<section>/<subsection>/<plugin_name>` (ex: `.../jobs/<1/raw/analyzers/classic_dns`).

In this way the pivoting from the visualizers is easier: in case a list has too many entries and we don't want to list them we can add a link to the raw data. Ex: a DNS resolution has 10 entries, we could show only 4 in a VList and and a 5th element to with the link of the raw data.

**Comment by mlodic** [comment]
won't do
