### ISSUE TITLE
[Analyzer] HFinger

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1698]
## Name
Hfinger

## Link
https://github.com/CERT-Polska/hfinger

## Type of analyzer
file analyzer, supports for PCAPs only

## Why should we use it
It is a cool tool to create fingerprints of malware HTTPS requests

## Possible implementation
it can be imported as python module: https://github.com/CERT-Polska/hfinger

**Comment by moonpatel** [comment]
Please assign me this issue @mlodic

**Comment by mlodic** [comment]
first we need to finish the other pending tasks
