### ISSUE TITLE
[Analyzer] Permhash

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1699]
## Name
Permhash

## Link
https://www.mandiant.com/resources/blog/permhash-no-curls-necessary

## Type of analyzer
file based

## Why should we use it
it could be used for hunting purposes on apk and chrome extensions

## Possible implementation
https://github.com/google/permhash

**Comment by moonpatel** [comment]
Hey, @mlodic please assign me this issue
