### ISSUE TITLE
Errors during initial run

### ISSUE THREAD

**Issue by ccw2777** [intelowlproject/IntelOwl#1708]
Hello!  Could really use some help.  When running intelowl for the first time we get the error and I'm not sure why as all inital configuration steps were followed.  

django.core.exeptions.improperlyconfigured:settings RECAPTCHA_SECRET_KEY must be set.  

We are also getting 
![16849707384286019400863304020857](https://github.com/intelowlproject/IntelOwl/assets/10868403/2612140d-e576-45d0-9ac4-c7aa0349f44f)

Any help would be great!

**Comment by mlodic** [comment]
please refer to this solution: https://github.com/intelowlproject/IntelOwl/issues/1665
