### ISSUE TITLE
DJANGO password authentication failed

### ISSUE THREAD

**Issue by AntoninHL** [intelowlproject/IntelOwl#171]
Hi,

I tried to start IntelOWL but I always have the same error:
`django.db.utils.OperationalError: FATAL:  password authentication failed for user "user"`

`env_file_app` and `env_file_postgres` are modified with key and passwords...

Is there anything else to do?

Thanks

**Comment by mlodic** [comment]
Hi @AntoninHL, just some questions to understand the problem.

did you use the most recent version (1.4.0)?
did you upgrade from an old version?
did you follow the steps here? https://intelowl.readthedocs.io/en/latest/Installation.html#after-deployment
How did you create that user?

**Comment by mlodic** [comment]
If you changed `env_file_postgres` after you have launched IntelOwl the first time, the Database had already set up the DB credentials to the ones they were written in that file. This means that:

- either you reset the password value in `env_file_postgres` to the previous one and relaunch the application

- or you completely drop the DB (`docker-compose down **-v**) and relaunch the application

**Comment by AntoninHL** [comment]
> If you changed `env_file_postgres` after you have launched IntelOwl the first time, the Database had already set up the DB credentials to the ones they were written in that file. This means that:
> 
> * either you reset the password value in `env_file_postgres` to the previous one and relaunch the application
> * or you completely drop the DB (`docker-compose down **-v**) and relaunch the application
> 
> Edit: be sure that `DB_HOST`, `DB_PASSWORD` values in `env_file_app` are the same of `POSTGRES_USER`, `POSTGRES_PASSWORD` values in `env_file_postgres` at the first time you launch the application.

Many thanks!
I change the password just after the first launch!
Now it's started. But no access to http... :-(

Many thanks again

**Comment by Eshaan7** [comment]
Glad that it works. The web interface is at http://localhost:80/
