### ISSUE TITLE
Error while initial run

### ISSUE THREAD

**Issue by ccw2777** [intelowlproject/IntelOwl#1710]
When attempting to run intelowl for the first time it appears to hang on "Task intel_owl.tasks.check_stuck_analysis[be17545d-a109-4001-8dc7-cb08e9626979] succeeded in 0.0158641804s: None"

I am also seeing the message "requests.exceptions.ConnectionError: ('Connection aborted.' ConnectionResetError(104 connection reset by peer)". 

Can this be troubleshot further and fixed,  or is there a way to purge intelowl and re-install/rerun everything?  Thank you!! 
- The "./initialize.sh" was already run successfully prior. 

![screenshot1](https://github.com/intelowlproject/IntelOwl/assets/10868403/37697fcc-736a-4ff8-b6a3-50aa4dfd9fb2)

**Comment by ccw2777** [comment]
![Capture2](https://github.com/intelowlproject/IntelOwl/assets/10868403/91589492-0b9c-4239-bf24-86494b81ceb4)

Working on providing more details

**Comment by ccw2777** [comment]
What happened,
So I followed the intelOwl config guide to do a fresh installation of IntelOwl. I followed every step including altered the files env_file_app and env_file_postgres, and I've double-checked that the credentials are exactly the same. 
When trying to deploy it hangs for a while at the below screenshotted area (INI configuration) and then after 5-10 minutes it goes to the previously screenshotted intel_owl.tasks.check_stuck_analysis line and hangs there. 

Environment
OS: Ubuntu
IntelOwl version: newest

How to reproduce your issue
Fresh install of IntelOwl on Ubuntu, follow the install steps on docs

Error messages and logs
Could use help on being told what logs I should be providing. 
Thank you very much for any help!

at the end of the day if this fails to be resolved is there a way to fully uninstall/cleanup and do a fresh pull request and install? 
![3](https://github.com/intelowlproject/IntelOwl/assets/10868403/3307c424-7ce7-4e9e-b296-482859621279)

**Comment by ccw2777** [comment]
![4](https://github.com/intelowlproject/IntelOwl/assets/10868403/cae76c9f-230f-4d77-a6f4-7ed4385b79d5)
It will also hang at the reoccurring line "Connection reset by peer" as previously mentioned.

**Comment by ccw2777** [comment]
Completed a complete rebuild and it hangs at "getting INI configuration from /etc/uwsgi/sites/intel_owl.ini" for a while before moving forward and hanging at the above screenshot again.  

Possible causes.  Running python version 3.1 with 3.9 also installed, 

UNABLE to locate the folder "uwsgi".  Attempting to find the path etc/uwsgi/sites/" found nothing created at this point.

**Comment by ccw2777** [comment]
What creates the file "intel_owl.ini"?  Its nowhere within the host after trying to install intelowl

**Comment by mlodic** [comment]
that's the application server (uwsgi) configuration. 

Have you tried to use the application from the GUI? Did you face any error there?

Then, you should extract the errors from the log files in the paths stated by the doc: https://intelowl.readthedocs.io/en/latest/Contribute.html#debug-application-problems

Anyway, I am not sure even if there is actually a problem here. Please do more efforts and try to use the application... only then provide feedback there. ty

**Comment by 0ssigeno** [comment]
> ![Capture2](https://user-images.githubusercontent.com/10868403/240985656-91589492-0b9c-4239-bf24-86494b81ceb4.PNG)
> 
> Working on providing more details
From this it seems like the cronjob of `Tor` is your issue: in the specific, it is unable to retrieve information from `https://check.torproject.org/exit-addresses`. On the `why` you have this kind of issue, unfortunately i'm unable to reproduce on my side: can you try to inside a celery container e manually try to retrieve the information from this url? I think it is something related to your network in particular

**Comment by ccw2777** [comment]
I was able to get it to work successfully. However, after upgrading to version 5 I am running into the exact same hangup (shown below) where Intelowl stays indefinitely. I didnt see any previous issue posting regarding this problem. This is the ONLY thing keeping it from running, and I am not finding much info on what part of IntelOwl could be causing this.  Any suggestions would be greatly appreciated! 


Intelowl_celery_worker_default | requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')).  
![issue](https://github.com/intelowlproject/IntelOwl/assets/10868403/15108ec7-d3cd-4385-a307-2ebad47b9f4a)

**Comment by 0ssigeno** [comment]
Mmmmmh, we did not change anything related to the communication between containers, and i'm unable to reproduce on my side.
Do you have any custom routing going on in your machine? Any other container up at the same time as intelowl? Vpns?

**Comment by taylor-madeak** [comment]
I got looped into this because I'm one of @ccw2777's colleagues.  It appears that torproject.org may be having some technical issues this week:

```
openssl s_client -connect check.torproject.org:443
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 312 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

**Comment by ccw2777** [comment]
@0ssigeno,  I think your comment regarding TOR could be what is causing the issue.  I think that "https://checktorproject.org/exit-addresses" has an SSL error and is unreachable. Is there a way to force IntelOwl to skip this?

**Comment by ccw2777** [comment]
@0ssigeno @mlodic  is there a way to get IntelOwl to skip Tor for the time being so that it no longer hangs when trying to access check.torproject.org.

**Comment by mlodic** [comment]
> Have you tried to use the application from the GUI? Did you face any error there?
> 
> Then, you should extract the errors from the log files in the paths stated by the doc: https://intelowl.readthedocs.io/en/latest/Contribute.html#debug-application-problems
> 
> Anyway, I am not sure even if there is actually a problem here. Please do more efforts and try to use the application... only then provide feedback there. ty

I still got no answers from these questions I made, so, aside the network problem, we have no way to help you if you don't help us understand your current situation.

The problem with Tor is not a reason enough to say that the application is not working. With your `docker ps`  command is clear that all the services are up and running so you don't have to stop once you get a generic error from the console.

**Comment by 0ssigeno** [comment]
So, as Matteo said, having the cron for Tor not working does not mean the application is not working: the important issue that i saw in your screenshot were the one between the containers, not between a container and the tor url.


Having said that, you can disable the Tor analyzer (django admin -> analyzer configs -> torproject -> disabled -> save) and this will disable the cronjob too.

**Comment by ccw2777** [comment]
Here are a few screenshots of the errors from the log files you mentioned. 
<img width="922" alt="CELERY ERRORS" src="https://github.com/intelowlproject/IntelOwl/assets/10868403/d0c0378d-1400-4b8b-a7f2-d2eb574ddd67">
<img width="675" alt="API APP ERRORS" src="https://github.com/intelowlproject/IntelOwl/assets/10868403/0e40d60c-f73c-4f95-92f3-3590a589a104">

**Comment by ccw2777** [comment]
I am able to do all of the above.  However, how do you get rabbitmq to pick the same IP address set in the BROKER_URL variable as each time IntelOwl is shut down and turned back on rabbitmq gets a different IP address that doesnt normally match the BROKER_URL variable IP.

**Comment by 0ssigeno** [comment]
Fair enough, my solution was just to prove that there was something wrong with the dns and not the application itself.
To force an ip address in the container, you can change the `docker-compose` file, `docker/rabbitmq.override.yml` adding these lines
```docker

    networks:
      static_network:
        ipv4_address: YOUR_IP
```
And at the end of the file
```docker
networks:
  static_network:
    ipam:
      driver: default
      config:
        - subnet: "YOUR_SUBNET/24"
```
More information: https://docs.docker.com/compose/compose-file/05-services/#ipv4_address-ipv6_address

But I'm gonna say again that this will **NOT** solve the issues that at the moment you have on your host that is disrupting docker itself.
