### ISSUE TITLE
Error after clicking on the Start Scan button (IntelOwl v5.0.0)

### ISSUE THREAD

**Issue by nebu10uz** [intelowlproject/IntelOwl#1727]
So I was able to install from scratch and run the latest IntelOwl v5.0.0. Upon creating the superuser, I encounter some errors when I tried to login, however, based on the cache error, I waited about an hour and it appears that the cache was deleted and I was able to successfully login afterwards.

But the main problem that I'm having now is that I cannot Scan. I'm seeing a few bugs on the Scan page but the main issue is that every time I hit the Start Scan button, I get the following error

`Failed!
{"errors":[{"playbooks":["Invalid pk \"{'isDisabled': False, 'value': 'FREE_TO_USE_ANALYZERS', 'label': {'type': 'div', 'key': None, 'ref': None, 'props': {'className': 'd-flex justify-content-start align-items-start flex-column', 'children': {'type': 'div', 'key': None, 'ref': None, 'props': {'className': 'd-flex justify-content-start align-items-baseline flex-column', 'children': [{'type': 'div', 'key': None, 'ref': None, 'props': {'children': ['FREE_TO_USE_ANALYZERS', '\\xa0']}, '_owner': None}, {'type': 'div', 'key': None, 'ref': None, 'props': {'className': 'small text-left text-muted', 'children': {'key': None, 'ref': None, 'props': {'children': 'A playbook containing all free to use analyzers.', 'components': {}}, '_owner': None}}, '_owner': None}]}, '_owner': None}}, '_owner': None}, 'labelDisplay': 'FREE_TO_USE_ANALYZERS'}\" - object does not exist."]}]}`

I disabled the FREE_TO_USE_ANALYZERS playbook from the Django Admin page but to no avail, I get the same error. I also changed the playbook name, saved it and no dice.

Additionally, in order for me to Scan, I need to add a space after I supply the IP address for example, without doing this, the Start Scan button is disable. 

Environment:
OS: Ubuntu 22.04
 IntelOwl: v5.0.0
Client computer: Macbook Air M1
Browsers: Firefox, Brave
Info: I changed the default TCP port 80 to TCP port 8010 on the default.yml and Nginx http.conf files.

![image](https://github.com/intelowlproject/IntelOwl/assets/1797583/61a61f1c-f34b-42cd-8e26-86b05b5a5d41)

**Comment by nebu10uz** [comment]
Furthermore, when I use playbooks the Start Scan button is disabled, I have to switch to Analyzers/Connectors, do some selections then go back to playbooks and then the Start Scan button is enabled, however, upon clicking on the Scan button, nothing happens. This is another issue or bug that I'm seeing.

**Comment by mlodic** [comment]
something was answered in #1728.

About the issue from the `FREE_TO_USE_ANALYZERS` playbook, I guess it was related to the databases migration that were not completed yet. I cannot reproduce it actually. In your case, I would just try to re-install from scratch once we release the 5.0.1 version (we'll do that today If I can), give it just few minutes to end migrations and then try again.

**Comment by mlodic** [comment]
please try the new 5.0.1 and let me know. ty

**Comment by nebu10uz** [comment]
Hi @mlodic,

Yup, v.5.0.1 fixed the issues I was seeing, especially the Start Scan button. 

I was able to query an IP address and receive the data. Also, I was able to use the playbooks.

Thank you very much for your assistance on this matter. I will continue to test and report back any issues that I may find.

**Comment by mlodic** [comment]
thank you, any report is extremely useful for us! :)
