### ISSUE TITLE
Error fetching user access information

### ISSUE THREAD

**Issue by d3f3nder** [intelowlproject/IntelOwl#1728]
## What happened
I've installed a fresh installation using the installation guide and a fresh ubuntu server 20.4. Everything looks good, when creating the user i am trying to singin using that user, but i am getting 'error fetching user access information' 
Tried several times, rebooten, created new users, but most of the time i get the given message or it just loads, and nothing happens. 

## Environment
1. OS: Ubuntu 22.04.2 LTS, running in hyper-v host. 
2. IntelOwl version: 5

##  What did you expect to happen
A successful sign-in

## How to reproduce your issue
Fresh installation, creating user, try to logon

## Error messages and logs
i am seeing this which i can't explain:
96+00:00 [info] <0.926.0> connection <0.926.0> (172.19.0.6:44860 -> 172.19.0.2:5672): user 'guest' authenticated and granted access to vhost '/'

**Comment by d3f3nder** [comment]
I tried it a second time, started all over, new server in hyper-v, ubuntu 20.4, installed all required apps using the manual, after startup of IntelOwl went on to create a user, tried to logon, it works but it gives me a 'error fetching user access information' error right away, before it logged me out again, now it doesn't but i am seeing a lot of 500 ínternal server errors on the screen. The django admin portal is not working either. 

when i try to log out it hangs sort of, when i try to sign-in using new session it now also hangs. 

something is not right here :)

is there anything i can provide for troubleshooting this?

regards! i am so looking forward to use this for my daily soc analyst tasks :/

**Comment by nebu10uz** [comment]
I had the same issue.

Looking at the error messages, it appears to be a cache issue and to resolve this, I just waited about an hour and then I was able to login with no error messages.

It appears that the app erases the cache running a schedule job and then you able to login.

However, the scan feature is not working for me at the moment. I reported the bug and waiting for the devs to investigate and report back to me.

I installed the latest version on an Ubuntu 22.04.

**Comment by d3f3nder** [comment]
I see, lets wait then. I hope this is not the standard procedure if you have to restart it every week in case of memory leaks. Lets hope the creators have a solution for us. 

Thanks and regards

**Comment by d3f3nder** [comment]
Ok i've waited and indeed it is wat you said, i can now signin, but the scan function is not working, i simple can't select it, its not active.

**Comment by nebu10uz** [comment]
> Ok i've waited and indeed it is wat you said, i can now signin, but the scan function is not working, i simple can't select it, its not active. 

Ok, so I'm definitely not the only one and we are having the same issues. I reported this bug recently but the devs have yet to respond. Hopefully we hear from them soon and there's a fix.

**Comment by mlodic** [comment]
hey, thank you for reporting. With new major releases, we could have introduced few bugs.

About the cache problem, there were a lot of database migrations going on under the hood with the changes we made for the new major so I think it's normal to have few server errors in the first few minutes. This should happen only the first time that you run the application. (Please tell us if that happens again). Nothing to worry about. Just refresh the pages if you get 500 errors until they are vanished.

About the Scan Form: we noticed a problem in the validation of the form. We are fixing it soon.

**Comment by mlodic** [comment]
please try the new 5.0.1 and let me know. ty

**Comment by d3f3nder** [comment]
Im forgo to mention this works! thanks.
