### ISSUE TITLE
[Analyzer] Greynoise Labs

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1758]
## Name
Greynoise_Labs

## Link
https://www.greynoise.io/blog/labs-api-its-playtime

## Type of analyzer
observable for IP only. 
It should extract the data from all the available queries that support IP addresses:
* noiseRank
* topC2s
* topKnocks

## Why should we use it
It's free and experimental: https://www.greynoise.io/blog/labs-api-its-playtime

## Possible implementation
check the docs: https://api.labs.greynoise.io/1/docs/

**Comment by moonpatel** [comment]
Hey @mlodic I would like to work on this issue. Can you assign this to me?
And one more thing, do I need to combine all three queries (noiseRank, topC2s, topKnocks) and show them on the result page ?

**Comment by mlodic** [comment]
hey, yes you should follow the analyzer creation guidelines and male queries for all the different endpoints

**Comment by moonpatel** [comment]
This API is available in only GraphQL. Can I use graphene for it ?

**Comment by mlodic** [comment]
sure

**Comment by eshaan7** [comment]
> This API is available in only GraphQL. Can I use graphene for it ?

Don't need graphene to make requests to a GraphQL API. Just use `requests`.

**Comment by mlodic** [comment]
nope cause this is another service, please create a new one and ignore the other one that already exist

**Comment by moonpatel** [comment]
This is the result so far now.
[grey_noise_result1.webm](https://github.com/intelowlproject/IntelOwl/assets/95487062/af314338-423c-4d81-abb1-48555e64e625)
Is this okay or do I need to make any changes?
@mlodic

**Comment by mlodic** [comment]
please open a PR and follow the guidelines. Issues are not meant to be used for reviews

**Comment by moonpatel** [comment]
I mean is this output format okay? If its fine then I will finalize the changes and create a PR. @mlodic
