### ISSUE TITLE
CAPE sandbox and a SOAR

### ISSUE THREAD

**Issue by mathurin68** [intelowlproject/IntelOwl#176]
Anyone used this with a SOAR like phantom and a CAPE sandbox?  Looks like its tailor made to work with a SOAR.

**Comment by mlodic** [comment]
IntelOwl is built to be easily integrated with other security tools. You can leverage the [official client](https://github.com/intelowlproject/pyintelowl) to integrate it via python with a SOAR of your preference.

You could also develop a specific CAPE analyzer to directly create and send analysis from IntelOwl if you wish.
