### ISSUE TITLE
[Analyzer] TweetFeeds

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1770]
## Name
TweetFeeds

## Link
https://tweetfeed.live

## Type of analyzer
observables

## Why should we use it
Free from the community

## Possible implementation
https://tweetfeed.live/api.html Extract their IOCs periodically in a text file and perform a simple match there.

**Comment by mlodic** [comment]
the service is no more available because Elon decided to force payment for Twitter's APIs 🤷🏻

**Comment by mlodic** [comment]
the service is back online. We should integrate it and then notify the creator to have IntelOwl added to the homepage.

**Comment by g4ze** [comment]
@mlodic assign pls

**Comment by g4ze** [comment]
hey! Concerning the implementation, can't we directly take in input parameters from the user as `filter1` , `filter2`, `filter3` and then just generate the URL, get the list and perform look up on each fresh run?

**Comment by mlodic** [comment]
yep, it is not required to manage an internal cache like I mentioned. That would be maybe the optimal solution because we cannot request all the data from the service at each request. It would make sense to just download all the data, keep it internally (like we do for Tor, Maxmind, etc) and query them internally.

The easiest way is to implement it like you mentioned and that would be better than nothing.
The hardest would be to implement this update and caching mechanism to keep the data locally

**Comment by g4ze** [comment]
I'm thinking of a middle ground approach, where we can periodically update the db based on the url set by the user. Like  the feodo tracker, we can let the user decide if they want to update the db for the particular url at every run. Therefore, we can have a solution which is optimised in the sense that if the same url is requested again, the user can decide if they want to update the db again and perform a look up, or just simply depend upon the default update cron routine. How does that sound?

**Comment by mlodic** [comment]
that sounds good, let's try this!

**Comment by mlodic** [comment]
solved with v6.0.0
