### ISSUE TITLE
[Analyzer] mmdb-server

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1779]
## Name
mmdb-server

## Link
https://github.com/adulau/mmdb-server

## Type of analyzer
observable -> ip only

## Why should we use it
Free service available at https://ip.circl.lu/

## Possible implementation
 lookup via https://ip.circl.lu/geolookup/8.8.8.8

**Comment by mlodic** [comment]
you can follow the documentation about the creation of a new analyzer and try to add this integration if you wish.

**Comment by che8u** [comment]
I've just added a possible implementation via geolookup [here](https://github.com/che8u/IntelOwl/commit/4d68f347b09b8e8cb26cc9e2bb5ccffcd893dfa7#diff-c2258f668c0cd881e950db37809466b77d3e74782b02f53f24dde85c0d1d7e9a). I'd greatly appreciate any feedback you might have.

**Comment by mlodic** [comment]
Please open a draft PR to the main repository and follow the checklist there

**Comment by g4ze** [comment]
Hey @mlodic ! I'd like to take up the issue pls
