### ISSUE TITLE
Job Table does not filter correctly for files

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1880]
the filter for "file" does not work.

![image](https://github.com/intelowlproject/IntelOwl/assets/30625432/9ee5d8bb-50d0-415e-92fd-8a7bcb8fa385)

**Comment by Shiva953** [comment]
I would like to take up this issue

**Comment by mlodic** [comment]
hello you are welcome! you got assigned! please follow the guidelines!

**Comment by Shiva953** [comment]
@mlodic sure

**Comment by drosetti** [comment]
Solved and merged into develop
