### ISSUE TITLE
Support for ipv6 addresses

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1885]
We should add the chance to analyze ipv6 addresses like any other ipv4 address. We should fix it both in the frontend and the backend regex.

Plus, we should check out the integrated services to understand whether they need some internal change or not to support it (maybe some different functions in the libraries)

**Comment by abhiraj-mengade** [comment]
May I work on this?

**Comment by shivam-Purohit** [comment]
hey @mlodic if this is going stale can I try this?
