### ISSUE TITLE
[Analyzer] Tor_Nodes_DanMeUk

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1886]
## Name
Tor_Nodes_DanMeUk

## Link
Extract lists of all Tor nodes from this site periodically:
https://www.dan.me.uk/tornodes

## Type of analyzer
observable for IP addresses only

## Why should we use it
An user requested this:

> the Torproject Analyzer uses the Tor exit nodes list, whereas the [dan.me.uk](http://dan.me.uk/) list includes all nodes (also entry and intermediary relays). It may be debatable if only the exit nodes are of interest - surely if you are looking at their roles as senders. However, if you look at outgoing traffic (possible C2) yo also want to match against the bridges and entry relay nodes, as this could identify malware. I would advocate to actually use the full list of tor nodes found at [dan.me.uk](http://dan.me.uk/), or provide another Analyzer that uses this list

## Possible implementation
just basically copy/paste TorProject one and change the results based on the type of the node

**Comment by moonpatel** [comment]
Hey @mlodic, I would like to work on this issue.

**Comment by moonpatel** [comment]
Hey @mlodic what should be the name of this analyzer?

**Comment by mlodic** [comment]
Tor_Nodes_DanMeUk

we need to complete the other issue before starting a new one

**Comment by mlodic** [comment]
solved with v6.0.0
