### ISSUE TITLE
[Analyzer] BGP-Ranking

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1901]
## Name
BGP-Ranking

## Link
https://github.com/D4-project/BGP-Ranking

## Type of analyzer
for IP only:
* first query to get the ASN: https://github.com/D4-project/BGP-Ranking#get-the-asn-from-an-ip-or-a-prefix
* second query to get the rank: https://github.com/D4-project/BGP-Ranking#get-the-ranking-of-the-as
* (optional, enabled by a parameter) third query to get history:  https://github.com/D4-project/BGP-Ranking#get-historical-information-for-an-asn

## Why should we use it
Free online service provided by CIRCL

## Possible implementation
Follow the guide on Github

**Comment by revv2703** [comment]
hello @mlodic
i would like to work on this issue
:)

**Comment by abheektripathy** [comment]
sure go for it @revv2703

**Comment by g4ze** [comment]
assign pls

**Comment by g4ze** [comment]
Hi! @mlodic here the second and third query does not require any ip but just an ASN, so which approach would you like to implement the query?:
- use ASN as the observable_name
- use ASN as another paraeter, but this imposes us to have atleast some type of observable name, which wiould be useless.

**Comment by mlodic** [comment]
the second query must use the AS value extracted by the first query, that's the idea. 

Then, the third query requires the AS too so you have it for that query too. The only difference is that I would make this query optional because it could retrieve a lot and useless data. This is why I'd leverage a parameter and set the extraction of this data by enabled by default

**Comment by mlodic** [comment]
maybe you can use https://pypi.org/project/pybgpranking2/ if you like instead of just classic requests

**Comment by mlodic** [comment]
solved in v6.0.0
