### ISSUE TITLE
Unable to scan files

### ISSUE THREAD

**Issue by Spyd3r0TW** [intelowlproject/IntelOwl#192]
No matter which type of file I use or which analyzer I try to use I get a 400 Error.

![error](https://user-images.githubusercontent.com/69591767/93253958-98784d80-f765-11ea-877d-72f972a00485.PNG)

Here is an example of some of the stuff I see in the logs:

{"log":"10.100.11.216 - - [15/Sep/2020:19:06:40 +0000] \"POST /api/send_analysis_request HTTP/1.1\" 400 134 \"http://hostname/pages/scan/file\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0\" \"-\"\n","stream":"stdout","time":"2020-09-15T19:06:40.985635925Z"}

{"log":"10.100.11.216 - - [15/Sep/2020:19:06:42 +0000] \"POST /api/send_analysis_request HTTP/1.1\" 400 134 \"http://hostname/pages/scan/file\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0\" \"-\"\n","stream":"stdout","time":"2020-09-15T19:06:42.220873709Z"}

I'm unsure where to look for more information on this.

**Comment by Eshaan7** [comment]
Hey. Can you tell what version of IntelOwl you are using?

**Comment by Spyd3r0TW** [comment]
I am using the docker containers which use v1.5.0

**Comment by Eshaan7** [comment]
Please follow the update guide. https://intelowl.readthedocs.io/en/latest/Installation.html#update-to-the-most-recent-version
