### ISSUE TITLE
Error 500 then logged off (Token error)

### ISSUE THREAD

**Issue by Stormozor** [intelowlproject/IntelOwl#1920]
Hello,
I've been trying to use IntelOwl for my school internship for days now but i've encoutered few issues.

After deploying the contenairs, it works. Every contenairs launched well without issue. 
When i log in for the first time the issue is that i get error 500 as told in the documentation.

After waiting minutes for the databases to work, I reload the page and i still have error 500 "Internal Error server" + "Error fetching users access informations". Then i also sometime get "Invalid Token" and i get logged off. 

But aside all of this, it sometimes works fine for a few minutes and then, all these issues comeback again.

I'll attach screens so you can see.

I can't find why I get all these errors. Any idea?

Thanks,

![image](https://github.com/intelowlproject/IntelOwl/assets/147034826/e38b7b97-3ae5-4db5-90f4-832f6e22eb70)
![image](https://github.com/intelowlproject/IntelOwl/assets/147034826/1ce154da-eb6d-46c0-a415-f35ea0f6f740)
![Screenshot_2023-10-05_04_55_20](https://github.com/intelowlproject/IntelOwl/assets/147034826/abb77a12-3e6f-43a6-bbfc-b3a714e1d2a7)
![Screenshot_2023-10-05_05_20_10](https://github.com/intelowlproject/IntelOwl/assets/147034826/4e676df2-1a15-42b1-ba3f-049d7cf96860)

**Comment by Stormozor** [comment]
Update:
After one and a half hour, it seems to works well. 
Is it possible IntelOwl need that much time to work without errors?

**Comment by mlodic** [comment]
There are a lot of database migrations in place. The speed could change based on your installation and your resources. It seems a lot of time to me but it could happen.
