### ISSUE TITLE
[Analyzer] IP2Location.io

### ISSUE THREAD

**Issue by ip2location** [intelowlproject/IntelOwl#1924]
## Name
IP2Location.io

## Link
https://www.ip2location.io

## Type of analyzer
Observable -> IP address only

## Why should we use it
It detects IP geolocation and proxy information using API. Free to use.

## Possible implementation
Refer to the documentation section in API page.

**Comment by aryan-bhokare** [comment]
Hi @mlodic , this API has two free options 
1. Without api_key with 500 queries per day limit.
2. With api_key with more limit.

**Comment by mlodic** [comment]
both, you can write an analyzer that supports both. There are other ones that already supports this mode.

**Comment by aryan-bhokare** [comment]
> both, you can write an analyzer that supports both. There are other ones that already supports this mode.

So should I work on adding this one ?

**Comment by aryan-bhokare** [comment]
@mlodic we can close this issue.
