### ISSUE TITLE
Update Capa analyzer to last version and move it from docker-based analyzer to classic one

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#193]
With the version [1.3.0](https://github.com/fireeye/capa/releases/tag/v1.3.0), they have also added Capa to [Pypi](https://pypi.org/project/flare-capa/). Maybe we could erase the already existing docker-based analyzer and create a classic file analyzer with a simple import from pypi

**Comment by CITIZENDOT** [comment]
I'll work on this. So, We're also moving capa from optional to built-in analyzers, Right?

**Comment by mlodic** [comment]
The main goal was to remove a useless docker-analyzer but now we merged it and there are other tools inside so there won't be much improvement imho. 

We could skip this or close it for now.

**Comment by CITIZENDOT** [comment]
Okay.
