### ISSUE TITLE
Dashboard improv: add button to filter for the user's org only

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1936]
Right now the dashboard provides generic data from all instance's users. It would be useful to get statistics only from the logged user's organization only.

We could add a toggle button at the top right of the page that perform this change. This would require a little change in the backend too to filter the data by the selected org. It is enough to use a toggle button because an user can be part of a single organization only.

**Comment by shivam-Purohit** [comment]
@mlodic should I try this?

**Comment by mlodic** [comment]
if you want you can. This is a full-stack issue so it is a really good way to work throughout the project

**Comment by shivam-Purohit** [comment]
Yes, will be a good way to learn. I will try to get a draft PR ready before next week.

**Comment by shivam-Purohit** [comment]
@mlodic mind if I take some time on this. I am currently in the middle of college projects and practicals, and have final exams from the next week.
Regarding the feature, for now job model does not have a direct relation with organisation. Though it is related with user model and user has property describing the org it owns. The way i am think of is getting the user org and using the organisation model we can get all the members of the org. Then we can filter jobs based on those users and then aggregate. is the approach correct?

**Comment by mlodic** [comment]
sure, that makes sense. You need to get the information about the org from there. Np about the time you need to do this, just keep me updated in any case please :) thank you

**Comment by shivam-Purohit** [comment]
> sure, that makes sense. You need to get the information about the org from there. Np about the time you need to do this, just keep me updated in any case please :) thank you

thanks for waiting! done with the exams. I have started working and will update soon.

**Comment by aryan-bhokare** [comment]
We can close this issue too.
