### ISSUE TITLE
Update DNSDB analyzer to v.2 + more options

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#195]
At the moment the DNSDB analyzer still leverages Farsight API v.1. Recently they published v.2 with even more options.
Doc: https://docs.dnsdb.info/dnsdb-apiv2/

We should give the chance to:
* set a different API endpoint
* support for `max_count` and "time" options (`time_first_before`, ...)
* wildcard queries (ex: `*.farsightsecurity.com`)
* nameserver queries (endpoint `rdata/name`)
* search for query type (ex: `A` only)
* keep retrocompatibility for v.1 API

**Comment by drosetti** [comment]
Max count is only for summarize (aggregate) queries, we do not perform them, max_count filter is not required.

**Comment by drosetti** [comment]
DNSDV API v2 use [DNSDB SAF Protocol](https://docs.dnsdb.info/dnsdb-saf-protocol/), this protocol has on element at the begin and one in the end of them message, the reason for these elements is that their presence assure all data have been sent.

**Comment by drosetti** [comment]
Done: f49db90
