### ISSUE TITLE
MISP observable analyzer adjustments

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1955]
We should revision that analyzer:

- [ ] "timeout" in PyMISP should be configurable by the user
- [ ] new option in the search: "published" to get only published event
- [ ] new option in the search: "metadata" to have lighter queries but less data

Reference:
https://github.com/MISP/PyMISP/blob/main/docs/tutorial/Search-FullOverview.ipynb

**Comment by Varlight** [comment]
Hi, I would like to work on this issue @mlodic

**Comment by mlodic** [comment]
hey, this is an urgent feature to add: if you get the time to try to work on it right now you can pick up, otherwise please select another issue to start with IntelOwl :) thank you for your understanding

**Comment by AnkurPrabhu** [comment]
Hey i am new here and this would be my first issue can i pick this up ? if yes pls assign it tot me

**Comment by HanilJain** [comment]
hi wanted to contribute for this issue.
could you please assign.
also while trying this out, I'm not sure what should be and misp-url in misp analyzer while configuring it.
I setted up misp-docker and launched http://localhost:8080/ and setted this as misp-url and with api_key but doesnt works.
could you please guide over it.

**Comment by mlodic** [comment]
if you have both intelowl and misp in the same machine in 2 different docker networks, they just cannot communicate

**Comment by HanilJain** [comment]
Hi I tried to get public IP address through multiple methods but none of them succeed. Tried to launch misp-docker in AWS EC2 instance either build fails or instance wasnt getting connected, i tired docker network for this but it does not seems to give a public IP is there any other method? could you please guide me.

**Comment by g4ze** [comment]
Hellou! @mlodic I'll look into this one
