### ISSUE TITLE
Date broken in the "Sending invitations" table of the org

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1969]
![image](https://github.com/intelowlproject/IntelOwl/assets/30625432/60e4f77e-ba3f-47fb-bcd6-b057767de248)

this should work the same way that the dates in the "Members" section works

**Comment by yuvrajrathva** [comment]
I can see the format of dates in both sections is the same as you can see in the attached image. 
![image](https://github.com/intelowlproject/IntelOwl/assets/102233638/104f5c4c-8ab1-4608-a806-bbb4b20fc161)
Please correct me if I am wrong and give me more detail on the issue. Please assign this issue to me; I want to resolve this.

**Comment by mlodic** [comment]
you are right but that is what you see from the `master` branch.

In the `develop` branch the members section is fixed. You start from there as stated in the Contribute section of the docs

**Comment by yuvrajrathva** [comment]
Even in the `develop` branch, the format of the date is the same. I have pulled all the changes, and I am in the `develop` branch. You can see the attached image.
Code:
![image](https://github.com/intelowlproject/IntelOwl/assets/102233638/dfa701a3-3bce-4807-ae3e-8d67c3fd388c)
Frontend: 
![image](https://github.com/intelowlproject/IntelOwl/assets/102233638/7e8f3aca-7936-4c36-a6b7-05bbb81fca13)

**Comment by mlodic** [comment]
honestly I see it working on `develop`...how did you run IntelOwl?

**Comment by mlodic** [comment]
yep the point is that if you run IntelOwl with `prod` you are executing the code in the `master` branch which is the one that we have built for that release. Please, check the documentation before trying to do any kind of development or testing.

**Comment by drosetti** [comment]
![Screenshot from 2023-11-16 15-54-19](https://github.com/intelowlproject/IntelOwl/assets/55402684/54a17300-9343-42a9-b4d8-1c59b3696eaa)

Already fixed
