### ISSUE TITLE
oletools dependency - update to 0.56

### ISSUE THREAD

**Issue by decalage2** [intelowlproject/IntelOwl#198]
Now that I merged your PR on oletools, I think it's better to point to the main oletools 0.56 release in requirements.txt instead of your modified version, to benefit from the latest bugfixes and future ones. :-)

**Comment by mlodic** [comment]
Hi @decalage2, I have already done it in the `develop` branch (https://github.com/intelowlproject/IntelOwl/commit/84b165f5875d5a0a008817f8ac20a3b0e7f392e1). I am about to push it into the next release. Thank you very much!
