### ISSUE TITLE
InQuest OpenAPI analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#200]
We could create a new classic analyzer for InQuest APIs. Ref: https://labs.inquest.net/docs

The analyzer should be configured to be used both without and with an API key.

Maybe we could leverage this: https://github.com/InQuest/python-inquestlabs. However, integrating these API should not require a lot of effort so if it is preferred to leave IntelOwl without such dependencies.

Interesting endpoints for IntelOwl:
* /api/dfi/search/hash/{source}
* /api/dfi/search/ioc/{kind}
* /api/dfi/details
* /api/dfi/details/attributes
* /api/iocdb/search
* /api/repdb/search

**Comment by KarenImmanuel** [comment]
Hey, I would like to work on this!

**Comment by Eshaan7** [comment]
@KarenImmanuel you've been assigned.

Per the requirements,
> The analyzer should be configured to be used both without and with an API key.
You can look at pulsedive.py, urlscan.py to see how the same thing is implemented there.

Don't use their python library use the requests module for making API calls with required parameters (you will find many examples of this under `api_app/script_analyzers/observable_analyzers/`

Here is proper, detailed docs on [Adding New Analyzers](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-analyzer).

**Comment by i-karen** [comment]
Hi @Eshaan7 ,
I have sent a PR.
It contains only one API for now.

Is this approach correct?
Any suggestions?

**Comment by mlodic** [comment]
Hey @i-karen, you can try to follow what @Eshaan7 suggested in the PR to adjust the code and, if you can, to add all the other APIs. 

All contributions are welcome even if little. However, with little more effort, I think you can finish the task completely and resolve this issue👍

**Comment by i-karen** [comment]
Sent a new PR #231 and incorporated the suggestions from @Eshaan7 and @mlodic from old PR #230

**Comment by CITIZENDOT** [comment]
Work going on regarding Issue? If not, I'd like to work on this.

**Comment by mlodic** [comment]
This task was left unfinished. You can start over or pick the code from the opened [PR](https://github.com/intelowlproject/IntelOwl/pull/231) and start from there.

Thank you!
