### ISSUE TITLE
[Analyzer] HudsonRock

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#2027]
## Name
HudsonRock

## Link
https://www.hudsonrock.com/

## Type of analyzer
domain: domain intelligence
ip: ip intelligence
generic: end user protection (email lookup)

## Why should we use it
free quota with the free api key provided at: https://cavalier.hudsonrock.com/docs

## Possible implementation
follow the docs:
https://cavalier.hudsonrock.com/docs

**Comment by 404-geek** [comment]
Hi @mlodic I am looking to contribute to new analyzers. 

Can you explain me the working as I am new to the project and looking forward to contribute.

**Comment by 404-geek** [comment]
class hudson(classes.ObservableAnalyzer):
    base_url: str = "https://cavalier.hudsonrock.com"

    api_version: str = "/api/json/v2"

    hudson_analysis: str
    _api_key: str
    start_page: str = 1

    def _make_request(self, uri, params, payload):
        headers = {
            'Content-Type': 'application/json',
            'api-key': self._api_key
        }

        response = requests.post(uri, params=params, headers=headers, data=payload)
        response_json = response.json()
        return response_json

    def _pagination(self, uri, payload, extra_params=None):
        result = []
        page = self.start_page

        while True:
            payload = json.dumps(payload)
            params = {'page': page}
            params.update(extra_params)

            response_json = self._make_request(uri, params, payload)

            if response_json == []:
                break

            result.append(response_json)
            page += 1

        return result

    def search_by_ip(self, ip):
        uri = f"{self.base_url}{self.api_version}/search-by-ip"
        payload_value = {"ip" : ip}
        return self._pagination(uri, payload_value)

    def search_by_domain(self, domains):
        uri = f"{self.base_url}{self.api_version}/search-by-domain"
        payload_value = {"domains": domains}
        params = {'type': 'all', 'third_party_domains': 'false'}
        return self._pagination(uri, payload_value, params=params)

    def search_by_email(self, email):
        uri = f"{self.base_url}{self.api_version}/search-by-login"
        payload_value = {"login": email}
        return self._pagination(uri, payload_value)



    def run(self):


        if self.hudson_analysis == "ip":

            result = self.search_by_ip(self.observable_name)
            result = {"ip": result}

        elif self.hudson_analysis == "domain":

            result = self.search_by_domain(self.observable_name)
            result = {"domain": result}

        elif self.hudson_analysis == "generic":

            result = self.search_by_email(self.observable_name)
            result = {"generic": result}

        else:
            raise AnalyzerConfigurationException(
                f"analysis type: '{self.hudson_analysis}' not supported."
                "Supported are: 'ip', 'domain', 'email'"
            )

        return result


Hi @mlodic can we review the above code for hudson analyzer.

**Comment by mlodic** [comment]
hey, thanks for your interest! It is really important to follow [Contribution rules](https://intelowl.readthedocs.io/en/latest/Contribute.html#rules) though.
I'll assign you but please follow the rules.

**Comment by 404-geek** [comment]
Hi @mlodic I went through the contribution rules and used shodan analyzer as a reference. I tried to write the hudson analyzer using that as a reference the above snippet is just the business logic integrating ip, domain and email lookup with pagination functionality. 

Is there anything I can add here or any suggestions?. Please let me know.

**Comment by mlodic** [comment]
You didn't. Otherwise you wouldn't have auto-assigned issues to yourself and written the code here. You are making us waste our time.

**Comment by 404-geek** [comment]
Ohh, really sorry for that. I was just trying to get a validation of whether the code I wrote was right or wrong. I will strictly follow it in the upcoming contributions. 

Since now this issue is assigned to me. Can you please validate the code I have written?

**Comment by 404-geek** [comment]
Hi @mlodic any update on this analyzer. Should I raise a PR for the above written code.

**Comment by mlodic** [comment]
I don't know how to tell you that you must read the documentation 🤣

**Comment by aryan-bhokare** [comment]
@mlodic in end user protection do we want the bulk one or normal one?

**Comment by mlodic** [comment]
assigned!

> @mlodic in end user protection do we want the bulk one or normal one?

I cannot access their site now (it is not responding) so I can't check to answer you rn

**Comment by aryan-bhokare** [comment]
> assigned!
> 
> > @mlodic in end user protection do we want the bulk one or normal one?
> 
> I cannot access their site now (it is not responding) so I can't check to answer you rn

Okay I'll wait.

**Comment by aryan-bhokare** [comment]
@mlodic if you are able to access it now. Can you tell me which one to implement.

**Comment by mlodic** [comment]
the normal one cause we are just analyzing one email at a time

**Comment by mlodic** [comment]
closing cause duplicate [exists](https://github.com/intelowlproject/IntelOwl/issues/2279) and the assigner is inactive

**Comment by aryan-bhokare** [comment]
Apologies for the inconvenience, I was hard stuck in college work, exams and internship work.
