### ISSUE TITLE
Performing Upgrades Removes Access to Dashboard

### ISSUE THREAD

**Issue by Spyd3r0TW** [intelowlproject/IntelOwl#203]
Anytime I perform a sudo apt-get update && sudo apt-get upgrade, I reboot the server then no longer have access to the dashboard or admin page. Any ideas why this happens?

FYI: These actions are performed on the host server containing the intelowl docker container.

**Comment by Eshaan7** [comment]
Hey. I am not sure what's causing this issue but off the top of my head maybe when you run system upgrades the docker services are stopped to update docker and docker-compose packages ?

**Comment by Spyd3r0TW** [comment]
Sorry, I have been out of the office for a few days.
I ended up putting the docker packages on hold and it still happened.
I decided to just try to reboot without upgrading and it still happened.

Is there a specific way I should be rebooting? A protocol I should be following.

**Comment by Spyd3r0TW** [comment]
I want to clarify that what I mean by lose access i that it doesn't remember our credentials. The dashboard is still up and running, just cannot login. All containers are running by the looks of it as well.

**Comment by mlodic** [comment]
Hey, somehow the docker volumes containing the database (and your credentials) were deleted during the operation. 

Honestly it should not happen and I think that it is not related to a project issue but maybe to something related to docker management.

However I suggest you to create a super user again, login into the Django Admin Interface and check if the users you created before are still there or not. Just to exclude any problems on the application.

**Comment by Spyd3r0TW** [comment]
Yeah, I have no clue what happened but instead of reverting back to my snapshot I have done the suggestion above. I have updated/upgraded/rebooted a few times and it is no longer happening.

Wish I knew the cause of this but its resolved for now at least. 

Thanks everyone for the help. Love the application.

**Comment by mlodic** [comment]
You are welcome :+1:
