### ISSUE TITLE
Shell script not running correctly

### ISSUE THREAD

**Issue by JayeshNarkar** [intelowlproject/IntelOwl#2037]
## What happened
![image](https://github.com/intelowlproject/IntelOwl/assets/141546762/d769f9fb-7c9f-44f1-9b8e-34fdabc01bb9)
Docker compose version too old
## Environment
1. OS: ubuntu, github codespace
2. IntelOwl version: fork of latest commit.

##  What did you expect to happen
My docker compose version is 1.29 as shown in the image but it says in the error message that version should be atleast 1.23.
After changing what the error message displayed was. It showed that the variable $docker_compose was blank or empty.
Image for reference:
![image](https://github.com/intelowlproject/IntelOwl/assets/141546762/92d5f4f3-c801-411a-ac5f-8113523c0923)

## How to reproduce your issue
Create a codespace on github Run the first four "# construct environment files from templates" commands 
Then run sudo ./initialize.sh

## Error messages and logs
"Error: Docker-compose version is too old. Please upgrade to at least 1.23.2."

**Comment by JayeshNarkar** [comment]
I know I did raise this issue but can i also be the one assigned to it!

**Comment by mlodic** [comment]
This is not something that we bother about because we have a guy who has been already rewriting and fixing the installation scripts

**Comment by JayeshNarkar** [comment]
Sorry for bothering then. I just thought that it hadn't been looked at for 2 weeks so I should just make a pr and see if that gets attention finally.
