### ISSUE TITLE
Simplifying CONTRIBUTIONS to IntelOwl

### ISSUE THREAD

**Issue by NerdSec** [intelowlproject/IntelOwl#212]
Hi Team,

First of all, great work on putting this out. I have just started to test `IntelOwl` and it looks promising. Have managed to do something similar previously, albeit without a UI. Would love to contribute to this repo and improve it, :small_airplane: 

I just have two suggestions:

1. Simplify the directory structure
a. Currently too many files are cluttered into the main repo and it is difficult to understand which of the folders are actually django modules.
b. I think it makes sense to separate configurations, dockerfiles, and the actual code in a much more cleaner layout.
2. Avoid using root user in the `intelowl` images.
a. Adding a non-privileged user and running all the processes with that user should help reducing risk.

There are some other suggestions which I would prefer to raise as PR's but I will wait before I create a branch.

**Comment by mlodic** [comment]
Hi,

thank you for your interest in the project!

About your suggestions, feel free to open a PR with those improvements. 

We are here to help you if necessary.

**Comment by NerdSec** [comment]
Sure @mlodic 

Could not identify the use of the following folders:
1. [integrations](https://github.com/NerdSec/IntelOwl/tree/develop/integrations)
2. [configuration](https://github.com/NerdSec/IntelOwl/tree/develop/configuration)

What are these used for or by? Have opened a draft PR. Could you please take a look and let me know your thoughts? :slightly_smiling_face:

**Comment by Eshaan7** [comment]
- The `integrations/` folder containes code, dockerfiles and compose files for optional analyzers which run in their own container. Kind of a micro-services pattern.
- The `configuration/` folder contains files which are mounted as docker volumes to the `uwsgi` docker service, they include configurable settings.

**Comment by Eshaan7** [comment]
> Simplify the directory structure

Done in: #277, #98
