### ISSUE TITLE
Configuration of the External Analyzer

### ISSUE THREAD

**Issue by KhaledEid020** [intelowlproject/IntelOwl#2121]
It is a dumb question, but how can I put my API for abuseIPDB in Intel Owl? Where is the place I can put my API and configure it?

![apuse](https://github.com/intelowlproject/IntelOwl/assets/159165053/47a1b560-9811-466a-a1bd-70b49d90df07)

**Comment by mlodic** [comment]
there are several options based on your use case: https://intelowl.readthedocs.io/en/latest/Usage.html#parameters

The most common use case is to go into the "Plugin config" section
