### ISSUE TITLE
BUG MISP Connector get wrong link for External analysis 

### ISSUE THREAD

**Issue by CyberAbwehr** [intelowlproject/IntelOwl#2123]
## What happened
Get wrong link for External analysis
http://localhost/pages/scan/result/11

<img width="1487" alt="MISP External analysis link wrong" src="https://github.com/intelowlproject/IntelOwl/assets/51229037/e75490bd-7f73-4e50-ae44-33cd3957c50e">

 
## Environment
1. OS: Ubuntu 22.04 LTS
2. IntelOWL: v5.2.3
3. MISP: 2.4.181

##  What did you expect to happen
as a minimum
http://192.168.1.44/jobs/11/raw/full

<img width="1663" alt="IntelOWL Full Report" src="https://github.com/intelowlproject/IntelOwl/assets/51229037/45a7dc29-e983-4875-9855-3196c786ad62">

The best solution is that not the link to the external analysis is posted, 
it would be that the full report (json) is in the misp event as example as External analysis text or add a file.

**Comment by mlodic** [comment]
the reason why you do not have the correct URL is because you have not configured the environment variable called `INTELOWL_WEB_CLIENT_DOMAIN`. That is specified in the documentation [here](https://intelowl.readthedocs.io/en/latest/Installation.html#environment-configuration-required).

Then yes, the integration can be customized and changed to add additional things if you want.

**Comment by CyberAbwehr** [comment]
I set the variable INTELOWL_WEB_CLIENT_DOMAIN, but still the link /pages/scan/result/12 is not working

<img width="722" alt="Screenshot 2024-02-09 145552" src="https://github.com/intelowlproject/IntelOwl/assets/51229037/958cab67-5c04-485a-b58b-67562a4d7921">

<img width="1061" alt="Screenshot 2024-02-09 145620" src="https://github.com/intelowlproject/IntelOwl/assets/51229037/b062d69a-cb17-4ef3-86b6-78faaf4d2e1d">

**Comment by mlodic** [comment]
ah yes, you are right. This connector hasn't been updated after an IntelOwl's major release that changed that URL.
I have just pushed a fix in the `develop` branch

**Comment by mlodic** [comment]
this has been solved since the last release
