### ISSUE TITLE
Add Stratosphere prioritzed blacklists

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#216]
These researchers created a public and very smart IP blocklists. Blog: https://www.stratosphereips.org/attacker-ip-prioritization-blacklist

We could create a new analyzer for these lists (all 3). 

We should also create an "updater" function that, daily, get the new lists (see this example: [Talos analyzer](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/script_analyzers/observable_analyzers/talos.py)). 
We should try to avoid the flood of updating requests to their site caused by this updater. This means that I suggest to add an environment variable that allows people to activate this analyzer (and its updates) manually, only if they want to use it. By default, both analyzer and updater should be disabled and the analyzer, if executed, should show a message explaining that the analyzer must be activated manually.

**Comment by Rishabh-Kumar-07** [comment]
I have a doubt. Through the proposed analyzer are you trying to display the blocked IPs or cross-reference the IP provided by user with these blacklists ??

**Comment by mlodic** [comment]
The second one because the point is to analyze a suspicious IP address. 
IntelOwl goal is to analyze artifacts. It would be out of scope to show all the blacklist.
The IntelOwl user would come with a suspicious IP address, would select this analyzer and the result would be whether that IP is in one of that blacklist or not

**Comment by Rishabh-Kumar-07** [comment]
@mlodic Okay.. I have written the analyzer working similar to Talos.  I was wondering if instead of environment variable can we download the dataset only when the analyzer is used. To prevent multiple downloads we can check whether the existing files are downloaded on the same day.

**Comment by mlodic** [comment]
that's good idea

**Comment by Rishabh-Kumar-07** [comment]
I have added the analyzer file "stratosphere.py" in the directory: "IntelOwl/api_app/script_analyzers/observable_analyzers", added the analyzer in analyzer_config.json and have added the test. However when running the test or accessing the analyzer from app. It shows the following error. I think the app is not able to find my file. Can you suggest something ??

report = stratosphere.Stratos(
NameError: name 'stratosphere' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.004s

**Comment by mlodic** [comment]
Please have some patience and try to debug this by similarity with other already available analyzers.

If you can't solve this, please open a draft PR. Without all the code it is really hard to debug this

**Comment by Rishabh-Kumar-07** [comment]
I have made a PR. Let me know if some changes needs to be done.

**Comment by mlodic** [comment]
Added #278!!! Thank you!
