### ISSUE TITLE
Missing command in installation documentation

### ISSUE THREAD

**Issue by moonpatel** [intelowlproject/IntelOwl#2165]
Missing command in installation documentation on this page.
https://intelowl.readthedocs.io/en/latest/Installation.html

After following the instructions given on this page, when I execute the command `./start prod up` I get the following error.
![Screenshot from 2024-02-26 01-42-48](https://github.com/intelowlproject/IntelOwl/assets/95487062/7391150e-3275-40e1-9ea1-66389dce245c)

**Comment by moonpatel** [comment]
I think we need to add the command in the installation instructions:
`cp docker/.env.start.test.template docker/.env.start.test`

**Comment by mlodic** [comment]
hey, thanks for reporting. That command is not really required, you can ignore the warning.

Anyway we already noticed that and has already been taken care by @fgibertoni. Next release will have it fixed

**Comment by fgibertoni** [comment]
@moonpatel in https://github.com/intelowlproject/IntelOwl/pull/2158 there is the next release script with this fix.
