### ISSUE TITLE
Evaluate substitution of time picker with a normal date picker

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#2176]
![image](https://github.com/intelowlproject/IntelOwl/assets/30625432/baf357c0-92b3-49cf-beb1-4077f1191bd8)

We need to have the chance to select more precisely a time frame to analyze.

We should look for a react component that does already something similar and add the support in the backend for that type of query -> queries should be done against the "created" field.

**Comment by aryan-bhokare** [comment]
take a look at this [one](https://reactdatepicker.com/)
and this
[one](https://www.npmjs.com/package/react-datepicker)

**Comment by mlodic** [comment]
done in 6.1.0
