### ISSUE TITLE
Docker compose doen't read `.env` file

### ISSUE THREAD

**Issue by Clovel** [intelowlproject/IntelOwl#2188]
## What happened

When starting the IntelOwl software suite using the `./start prod up` command, I get this error :

```log
Error response from daemon: invalid reference format
```

By modiying the `./start` script to print the env & the docker compose command I get :

```log
...env blablabla...
REACT_APP_INTELOWL_VERSION="v5.2.3"
...env blablabla...

docker compose --project-directory docker --env-file docker/.env -f docker/default.yml -f docker/postgres.override.yml -f docker/rabbitmq.override.yml -p intel_owl up

Error response from daemon: invalid reference format
```

I then tried to replace the `${REACT_APP_INTELOWL_VERSION}` references in `docker/default.yml` with a hardcoded value (`v5.2.3`) and it worked ! So the issue lies on the loading of the `docker/.env` file by `docker-compose`.

## Environment
1. OS : Ubuntu 22.04.3 LTS on Windows 10 x86_64 (via WSL)
2. IntelOwl version : `REACT_APP_INTELOWL_VERSION="v5.2.3"`

##  What did you expect to happen

Basic `docker compose up` behavior

## How to reproduce your issue

```bash
# clone the IntelOwl project repository
git clone https://github.com/intelowlproject/IntelOwl
cd IntelOwl/

# construct environment files from templates
cp docker/env_file_app_template docker/env_file_app
cp docker/env_file_postgres_template docker/env_file_postgres
cp docker/env_file_integrations_template docker/env_file_integrations
cp docker/.env.start.test.template docker/.env.start.test.template # WARNING : NOT IN THE DOCS, SEE #2189
cp frontend/public/env_template.js frontend/public/env.js

# verify installed dependencies and start the app
./start prod up
```

For the `.env.start.test.template` file that need to be copied but isn't in the documentation, see #2189.

## Error messages and logs

```log
Error response from daemon: invalid reference format
```

**Comment by mlodic** [comment]
thanks for reporting. This already had been fixed and the change will be available in the next v6.0.0 release (~end of month)
