### ISSUE TITLE
Missing `.env.start.test.template` template copy in quick start documentation 

### ISSUE THREAD

**Issue by Clovel** [intelowlproject/IntelOwl#2189]
## What happened

When starting the IntelOwl software suite using the `./start prod up` command, I get this error :

```log
grep: docker/.env.start.test: No such file or directory
./start: line 92: export: `': not a valid identifier
Error response from daemon: invalid reference format
```

By modiying the `./start` script to print the env I found out that `.env/start/test` is required. The `.env.start.test.template` file exists but the documentation doesn't specify that we need to copy it. This step should be added to the docs. 

Also the script should have better error handling for this. 

```log
./start: line 92: export: `': not a valid identifier
```

## Environment
1. OS : Ubuntu 22.04.3 LTS on Windows 10 x86_64 (via WSL)
2. IntelOwl version : `REACT_APP_INTELOWL_VERSION="v5.2.3"`

##  What did you expect to happen

Basic `docker compose up` behavior

## How to reproduce your issue

```bash
# clone the IntelOwl project repository
git clone https://github.com/intelowlproject/IntelOwl
cd IntelOwl/

# construct environment files from templates
cp docker/env_file_app_template docker/env_file_app
cp docker/env_file_postgres_template docker/env_file_postgres
cp docker/env_file_integrations_template docker/env_file_integrations
# cp docker/.env.start.test.template docker/.env.start.test.template # WARNING : NOT IN THE DOCS
cp frontend/public/env_template.js frontend/public/env.js

# verify installed dependencies and start the app
./start prod up
```

## Error messages and logs

```log
grep: docker/.env.start.test: No such file or directory
./start: line 92: export: `': not a valid identifier
```

**Comment by mlodic** [comment]
thanks for reporting. This already had been fixed and the change will be available in the next v6.0.0 release (~end of month)
