### ISSUE TITLE
[Analyzer] Blint

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#2232]
## Name
Blint

## Link
https://github.com/owasp-dep-scan/blint?tab=readme-ov-file

## Type of analyzer
file analyzer for various types of executables (configure supported files properly)

## Why should we use it
open source and free, it helps to evaluate a binary

## Possible implementation
pip package
https://github.com/owasp-dep-scan/blint?tab=readme-ov-file

**Comment by g4ze** [comment]
Hi! Assign pls.
