### ISSUE TITLE
[API] endpoint to stop/kill a running job

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#225]
In this case it would be nice to have a button - kill job or stop job. 

_Originally posted by @WhiteHatMR in https://github.com/intelowlproject/IntelOwl/issue_comments/707807962_

We could add a `kill` button to the job (analysis) result page. This button when invoked should stop all ongoing celery tasks (i.e. all running analyzers) for the particular job. The status of such job should then be marked `failed` or `killed`. 

This sounds easy on paper, but would require much changes:

- To stop an ongoing celery task, we can send a control signal (`TERM`) ([ref.](https://stackoverflow.com/a/25561389/10534470))  but it requires the ID for the particular task. So need a way to keep track of all celery task IDs for a particular job.
- An endpoint `/api/kill_analysis/{job_id}` with appropriate permission enforcing i.e. If X created the job then only the admin and X should be allowed to kill it.

**Checklist:**
- [x] API endpoint
- [ ] Button in frontend (IntelOwl-ng)
- [ ] member function and CLI command in pyintelowl.

**Comment by Eshaan7** [comment]
Could be use [django's low level cache API](https://docs.djangoproject.com/en/3.1/topics/cache/#basic-usage) to store the task IDs for a particular job.

**Comment by sp35** [comment]
Hi, I would like to work on this issue.

**Comment by Eshaan7** [comment]
The API endpoint has been added, thanks to @sp35. Now we need to add support for this to pyintelowl as well as IntelOwl-ng.

**Comment by Eshaan7** [comment]
> We could add a `kill` button to the job (analysis) result page. This button when invoked should stop all ongoing celery tasks (i.e. all running analyzers) for the particular job. The status of such job should then be marked `failed` or `killed`.

**Comment by Eshaan7** [comment]
New member function `def kill_running_job(job_id: int) -> bool` in pyintelowl.
