### ISSUE TITLE
[Analyzer] Hudson Rock Cybercrime Intelligence Free API 

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [intelowlproject/IntelOwl#2279]
Consider adding Hudson Rock's complimentary data to your enrichment stack to check if an email address or domain was compromised in a global Infostealer attack.

Email API sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-email?email=manvirdi2000@gmail.com
Domain API sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-domain?domain=tesla.com

Free API key and full documentation is available here: https://cavalier.hudsonrock.com/docs

Thank you.

**Comment by mlodic** [comment]
closing the already existing duplicate [here](https://github.com/intelowlproject/IntelOwl/issues/2027).

**Comment by mlodic** [comment]
@hudsonrock-partnerships please remember that the tool is open source with extended documentation so you are always free to implement this by yourself and open a PR

**Comment by g4ze** [comment]
assign pls :)
