### ISSUE TITLE
Change an existing Playbook without creating a new one

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#2303]
Right now this is possible only from the Django Admin by administrators.

The users should be able to change the Playbooks of their organizations if they are admin or just their own created playbooks.

For instance, if I would like to just add/delete a single Analyzer to a Playbook that I own, I would like to be able to do that from the GUI.

It should also be possibile to add a new "basic" Pivot from the GUI to connect an already existing Playbook to another.

**Comment by mlodic** [comment]
* button "edit" in "action" column to edit plugins + tlp + scan mode + tags
* "Pivot create button" -> name, description, playbook to execute, base Pivot (AnyCompare o SelfAnalyzable)

**Comment by carellamartina** [comment]
#2451

**Comment by carellamartina** [comment]
#2451
