### ISSUE TITLE
Add new analyzer for CERT Polska MWDB

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#234]
References:
* https://www.cert.pl/en/news/single/set-up-your-own-malware-repository-with-mwdb-core/
* https://mwdb.readthedocs.io/en/latest/user-guide/8-REST-and-mwdblib.html#using-mwdblib-for-automation
* (after login) https://mwdb.cert.pl/docs

We should create a new analyzer to interact with the MWDB project.
Some considerations:
* for a more pythonic code we can leverage the official library (pip install mwdblib),even if it would add a dependency
* the analyzer should support both the public instance and a private one (configurable URL)
* we should use API keys, not user/password for authentication
* there are a lot of endpoints available. We should focus on the ones that can be more valuable for IntelOwl.

   Examples:
* get file info from hash (/api/file) and, if available, get info from the related id (/api/file/{identifier})
* if the user wants to share the file (optional config) and the file is not available, upload the file (POST /api/file) and retrieve the result later with polling.

**Comment by Rishabh-Kumar-07** [comment]
Hi! I would like to implement it. Will soon follow-up with the PR.

**Comment by Rishabh-Kumar-07** [comment]
@mlodic Hey! The analyzer is almost written. I do not have API keys to test the code. Can you suggest something ?

**Comment by mlodic** [comment]
You could request access to the platform.

**Comment by mlodic** [comment]
merged #302
