### ISSUE TITLE
File Not Found Error: daphne.log

### ISSUE THREAD

**Issue by nebu10uz** [intelowlproject/IntelOwl#2367]
## What happened
For intelowl_daphne container, I get the following error:

 
![image](https://github.com/intelowlproject/IntelOwl/assets/1797583/5ff8769f-74f7-4256-b3e5-20df369f4474)

## Environment
1. OS:
Ubuntu-22.04.2

2. IntelOwl version:
v6.0.4

##  What did you expect to happen
Successfully started Intel Owl.

## How to reproduce your issue
Updated Intel Owl to the latest v6.0.4 from 5.x.x and then issued the following command: `./start prod up`

## Error messages and logs

`FileNotFoundError: [Errno 2] No such file or directory: '/var/log/intel_owl/asgi/daphne.log'`

However, I verified and the directory and log file are there:

```
$ ls /var/log/intel_owl/asgi/daphne.log
/var/log/intel_owl/asgi/daphne.log
```

**Comment by drosetti** [comment]
Hey @nebu10uz thanks for your report, we are going to replicate the bug and respond to you asap

**Comment by fgibertoni** [comment]
Hi @nebu10uz. 
I was not able to replicate the exact same issue that you mentioned. I found another issue that could be related to yours and fixed it.
You can find the fix in `develop` branch. 
Can you please move to that branch and try running `./start test up` ? if you're missing dependencies try running `./start test up -- --build`

**Comment by nebu10uz** [comment]
> Hi @nebu10uz. I was not able to replicate the exact same issue that you mentioned. I found another issue that could be related to yours and fixed it. You can find the fix in `develop` branch. Can you please move to that branch and try running `./start test up` ? if you're missing dependencies try running `./start test up -- --build`

Hi @fgibertoni,
I switched to the develop branch and ran both commands, however, I got errors for both. Thx for helping out.

**Comment by drosetti** [comment]
It's strange, do you check it exist in the path inside the container ? Because outside the file should be located in `/var/lib/docker/volumes/intel_owl_generic_logs/_data/asgi`

**Comment by nebu10uz** [comment]
> It's strange, do you check it exist in the path inside the container ? Because outside the file should be located in `/var/lib/docker/volumes/intel_owl_generic_logs/_data/asgi`

I checked this path and I don't have this directory. Once I created this directory `mkdir /var/lib/docker/volumes/intel_owl_generic_logs/_data/asgi` I was able to start Intel Owl.

Thanks @drosetti for this information! I was able to resolve this issue.

**Comment by mlodic** [comment]
great, I'll add a note in the documentation for other users
