### ISSUE TITLE
Integration with other Infra Intel providers? (Similar with Shodan)

### ISSUE THREAD

**Issue by terminatordoink** [intelowlproject/IntelOwl#238]
Dear IntelOwl Creators,

The tool you have created is awesome, possible to also integrate this in your development pipeline?
https://www.zoomeye.org

**Comment by mlodic** [comment]
Hi @terminatordoink and thank you for your interest in the project!

Sure, adding a new analyzer that leverages external APIs is the easiest thing to do. IntelOwl is built to ease the process of adding new analyzers.

If you are confortable with python, you can try to add the analyzer by yourself. It should be pretty straightforward if you follow the [doc](https://intelowl.readthedocs.io/en/latest/Contribute.html). And you can always ask help.

Meanwhile I created a new issue (#239) with your request.

**Comment by terminatordoink** [comment]
Bro, awesome integration with ZoomEye *Salute*, now this is another good one as well "pulsedive.com"

**Comment by mlodic** [comment]
We have already the Pulsedive analyzer :P

**Comment by terminatordoink** [comment]
nice one bro! how about this?
https://team-cymru.com/community-services/mhr/

**Comment by mlodic** [comment]
That one too :P 

Check the docs [here](https://intelowl.readthedocs.io/en/latest/Usage.html) to see all the integrations available!

**Comment by terminatordoink** [comment]
*Salute* <3

**Comment by terminatordoink** [comment]
Another nice one to add dear creators https://quake.360.cn/quake/#/index  you will love it
