### ISSUE TITLE
Slowness in scan after 6.0.4 update

### ISSUE THREAD

**Issue by krunalgaikwad97** [intelowlproject/IntelOwl#2394]
## Environment
1. OS:Linux

3. IntelOwl version:6.0.4

##  What did you expect to happen
issue with the time scan takes to complete as compared to the previous version. Scanning IP with 26 analyzers takes more than double the time as compared to previous version.

**Comment by mlodic** [comment]
hey, this is impossible for us to replicate so, without any additional info, we cannot actually state that this is an existing bug. We have no such issues in our deployments in that sense. Can you send more information about? Application logs? In case, I'll reopen the issue
