### ISSUE TITLE
Create analyzers from the GUI

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#2429]
We should give the users the chance to create a basic analyzer directly from the GUI.

In some cases, it's enough to provide an URL, a way to authenticate to the service and you are done if the results are available in json.
There's no need to write python code for these cases. It would be enough to leverage a basic analyzer and create a custom version of it via the GUI, thanks to a very simple modal.

We should provide some chances of customization to allow the most common use cases:
* the name of the header key it could easily change from service to service, it must be configurable or it must be explicitly said that a key is not needed
* the chance to validate or not the https certificate and the chance to upload a custom one to enable verification (see MISP analyzer where we already do this)
*  others?

**Comment by drosetti** [comment]
Recurrent parameters in several analyzers:

* url (required)
* http method (default GET)
* name of the header key (default Authorization)
* API key (required)
* certificate (in case it's empty, default certificates)
* user-agent (optional)
* param name (optional for GET, required for POST)
* some analyzers use the observable in the URL as a rest resource (Ex: /api/status/<observable>) (default in case the previous param miss)
