### ISSUE TITLE
[Analyzer] APK_Artifacts

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#2444]
## Name
APK_Artifacts

## Link
https://github.com/guelfoweb/artifacts

## Type of analyzer
file anayzer for APKs only

## Why should we use it
cool open source tool to triage apk packages

## Possible implementation
https://github.com/guelfoweb/artifacts with all the possible options

**Comment by g4ze** [comment]
hey! @mlodic  how would like me to proceed with this one? its just a single file/script that is being used here. How do you suggest that we proceed with its installation?

**Comment by mlodic** [comment]
install as suggested, even if it's not on pypi. This time is not a particular problem cause we would add it into the malware analyzers container so I am not bothered about it

**Comment by g4ze** [comment]
yo @mlodic  this requires our docker image to be updated from python 3.8 to 3.9
```
21.86 ERROR: Ignored the following versions that require a different python version: 2.1.0 Requires-Python >=3.9; 2.1.0rc0 Requires-Python >=3.9; 2.1.1 Requires-Python >=3.9; 2.1.2 Requires-Python >=3.9; 2.1.3 Requires-Python >=3.9; 2.1.4 Requires-Python >=3.9; 2.2.0 Requires-Python >=3.9; 2.2.0rc0 Requires-Python >=3.9; 2.2.1 Requires-Python >=3.9; 2.2.2 Requires-Python >=3.9
21.87 ERROR: Could not find a version that satisfies the requirement pandas==2.1.3 (from litejdb) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.0rc0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0rc0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3)
22.17 ERROR: No matching distribution found for pandas==2.1.3
```

**Comment by mlodic** [comment]
as suggested in the comment in the Dockerfile, the problem about not upgrading python was related to a specific tool: stringsifter.

I noticed that there is a newer version that support python 3.9: https://pypi.org/project/stringsifter/
You can try to update both python and stringsifter together so you can support this analyzer too. Please try an execution of stringsifter to see if that works as expected. thanks
