### ISSUE TITLE
Error response from daemon: invalid reference format

### ISSUE THREAD

**Issue by paulie007** [intelowlproject/IntelOwl#2460]
minor issue

Got this error when running ./start prod up

unable to get image 'intelowlproject/intelowl:"v6.0.4"': Error response from daemon: invalid reference format

Solution:

In docker/.env  change  

REACT_APP_INTELOWL_VERSION="v6.0.4"
to
REACT_APP_INTELOWL_VERSION=v6.0.4

**Comment by mlodic** [comment]
hey, can we please tell us your OS, shell, docker versions? cause we cannot replicate it. In our test envs work perfectly good

**Comment by dpalavra** [comment]
Yup, I had to do the same, without quotes, its working now. Ubuntu 22.04 git cloned this latest image you guys have here today. 

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Docker version 27.1.2, build d01f264
Docker Compose version v2.20.3

**Comment by thedunston** [comment]
I'm on Ubuntu 22.04 and had to remove the double quotes:
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by arkrwn** [comment]
Mine also had to remove the quotes to make it run
 
 Docker Compose version v2.3.4
 Docker version  24.0.7
 Git commit:        24.0.7-0ubuntu2~22.04.1
 Built:                   Wed Mar 13 20:23:54 2024
 OS/Arch:             Ubuntu 22.04 x86_64 GNU/Linux
 Shell:                   Bash

**Comment by paulie007** [comment]
> hey, can we please tell us your OS, shell, docker versions? cause we cannot replicate it. In our test envs work perfectly good

Ubuntu 22.04
GNU bash, version 5.1.16
Docker version 27.1.1

**Comment by mlodic** [comment]
thank you for the feedback, we'll remove that quotes. It seems they are not necessary in any case.
We'll have a new release next week with those fix.
