### ISSUE TITLE
test env doesnt work with tls/ssl certificate from letsencrypt/certbot

### ISSUE THREAD

**Issue by krunalgaikwad97** [intelowlproject/IntelOwl#2462]
## What happened
We tested all analyzers and visualized all the data from those analyzers using visualizer code file (customed to our need), but as soon as when we added certificate from letsencrypt and certbot to our domain we couldnt get the visualizer data (dash) from our analyzer's report. also we cant get our domain up with ssl cert using test env. whatever worling with test doesnt work with prod.

## Environment
1. OS: ubuntu
2. IntelOwl version: 6.4

## Error messages and logs
![prod](https://github.com/user-attachments/assets/f3976ca1-880e-47dd-a20c-16a16a2b9b00)
![test](https://github.com/user-attachments/assets/47d6f1a1-5dc7-461c-9bb1-a42cf2a927a6)

**Comment by krunalgaikwad97** [comment]
![image](https://github.com/user-attachments/assets/2063cc27-da13-40c8-b311-8c6d9105b1bf)

**Comment by krunalgaikwad97** [comment]
Both images are for test and prod with same code for visualizers. i mean ge the data from the analyzers and visualizing it. problem is we can get the desired output when testing the code in test env, but we can see the default dash(prebuild) for visualizer with the same code.

**Comment by mlodic** [comment]
hey, great usage of visualizations :)

About the deployment problems you are having: it's almost impossible, from our side, without having any access to your environment, to understand what's going on. These problems are most of the times your personal deploy problems, not IntelOwl problems.

If you are interested in paying for consultancy, we can talk about that and provide custom support.
