### ISSUE TITLE
[Analyzer] Androguard

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#2514]
## Name
Androguard

## Link
https://github.com/androguard/androguard

## Type of analyzer
file analyzer https://github.com/androguard/androguard to embed in IntelOwl

## Why should we use it
https://github.com/androguard/androguard cool tool for extracting information about APK

## Possible implementation
https://androguard.readthedocs.io/en/latest/intro/gettingstarted.html
https://androguard.readthedocs.io/en/latest/intro/gettingstarted.html#getting-information-about-an-apk
Extract:
* permissions
* activites
* other basic useful info

**Comment by spoiicy** [comment]
Hi @mlodic, Shall I pick this issue up and commence working on this.

I'll extract info about the APK corresponding to what we get from the following functions provided by Androguard:
1. get_permissions()  
2. get_providers() 
3. get_activities() 
4. get_requested_third_party_permissions()
5. get_app_name()
6. get_features()
Reference: https://androguard.readthedocs.io/en/latest/api/androguard.core.bytecodes.html#module-androguard.core.bytecodes.apk

Hope this makes sense. Let me know in case you want any changes to be made.

**Comment by spoiicy** [comment]
@mlodic since the PR has been merged, shall we we close the issue.
