### ISSUE TITLE
Hung jobs - unable to kill

### ISSUE THREAD

**Issue by neilunderwood** [intelowlproject/IntelOwl#252]
I see that you have a "kill" button in the works potentially.  However, our instance of OWL is stuck.  I ran 3 jobs through it via API this morning and all 3 are still running now this afternoon with no end in sight.  It seems that it is still accepting new jobs, but those get hung as well.  We now have 4 jobs hung indefinitely and can't use OWL until we sort this.   Is there an easy way to kill these jobs on the backend? (issue persists through reboot)

**Comment by Eshaan7** [comment]
Hey. Can you please tell:
- the version of IntelOwl you are using? (look in the .env file) 
- for which analyzer the job is going on indefinitely?
- sure your setup is okay? IntelOwl stops and marks all running jobs as failed when it reboots so this is a weird behavior.

**Comment by neilunderwood** [comment]
I don't have access to the machine. Allow me to get with the maintainer and
get you those answers Monday. Thanks.

**Comment by neilunderwood** [comment]
Chatting with him now.  Sorry for the delay.  I'll get some info for you.

**Comment by neilunderwood** [comment]
Well,  we booted it back up this morning and gave it a hug and it seems happy now.  Scans are working in GUI and via API.  Not really sure what happened as we did nothing to fix.  We can close this out I guess.  Thanks!
