### ISSUE TITLE
Missing Test Coverage for ask_analysis_availability API View

### ISSUE THREAD

**Issue by n-strong** [intelowlproject/IntelOwl#2579]
Issue: Missing Test Coverage for ask_analysis_availability API View
What happened

The ask_analysis_availability API view currently lacks comprehensive test coverage. This absence of tests may lead to undetected bugs and regressions in future updates, affecting the reliability of the API endpoint.
Environment

    OS: Linux Mint 21.3
    IntelOwl version: v6.1.0

What did you expect to happen

I expected the ask_analysis_availability API view to have thorough unit tests covering various scenarios to ensure its correct functionality and to prevent potential issues during development and deployment.
How to reproduce your issue

Not applicable—this issue pertains to missing test cases rather than a runtime error.
Error messages and logs

There are no error messages or logs since this is about adding missing test cases.
Suggested Test Cases for ask_analysis_availability API View

    Valid Request
        Test Scenario: Provide a valid MD5 hash and analyzer details.
        Expected Result: Receive a 200 OK response with the correct data.

    Missing Fields
        Test Scenario: Submit a request without the required md5 field.
        Expected Result: Receive a 400 Bad Request response indicating the missing fields.

    Unauthorized Access
        Test Scenario: Attempt to access the endpoint without authentication.
        Expected Result: Receive a 401 Unauthorized response, ensuring that only authenticated users can access the endpoint.

Implementation Details

    Testing Tool: Use APIClient from rest_framework.test to simulate POST requests.
    Test Methods: Create separate test methods for each scenario to maintain clarity and organization.
    Assertions: Check both response status codes and content to verify that the API behaves as expected.

**Comment by fgibertoni** [comment]
I am correctly seeing all tests where they should be. Can you please provide better explanation on what you mean?
Closing the issue for the meantime.

https://github.com/intelowlproject/IntelOwl/blob/1f5992887e0e49aa8d37a68414df6ae1e34f9d9f/tests/api_app/test_api.py#L88
