### ISSUE TITLE
New analyzer: RecordedFuture

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#263]
An analyzer to get the latest risk data from [RecordedFuture](https://www.recordedfuture.com/) for a hash, domain or an IP address.

**Comment by CITIZENDOT** [comment]
I'll work on this.

**Comment by mlodic** [comment]
> Same is the case with Recorded Future. I had requested demo 2 times. No reply from them yet.

If you confirm this, we can close the issue. Thank you

**Comment by CITIZENDOT** [comment]
Yeah. I can confirm this. You can close this now. If I receive any updates, I'll open it.
