### ISSUE TITLE
Add other useful hashes to File_Info analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#270]
We could add the following hash calculations to `File_Info` analyzer:

- [ ]  TLSH: https://github.com/trendmicro/tlsh (pip library available)

- [ ]  telfhash: https://github.com/trendmicro/telfhash (pip library available). This one should be used only for ELF files. Maybe we could create another analyzer (`Elf_Info`) like the `PE_info` for portable executables

**Comment by Rishabh-Kumar-07** [comment]
I didn't find any pip library for telfhash. Can you share the link of pip library. In case the pip library is not there can we proceed for docker based analyzer ?

**Comment by CITIZENDOT** [comment]
As mentioned in docs, Install like [this](https://github.com/trendmicro/telfhash#installing).
You may get `ModuleNotFound` error for `grouping` library. Install that too, with `pip install grouping`.

**Comment by mlodic** [comment]
Yes, it was my mistake I think, I checked again and I did not find it. I am about to ask them if they can upload the library. https://github.com/trendmicro/telfhash/issues/3

**Comment by Hritish42** [comment]
Can i take this issue?

**Comment by mlodic** [comment]
Yes, you are welcome

**Comment by palrohitg** [comment]
@mlodic  is this issue still active? if Not. Could u provide more insight about the same.

**Comment by mlodic** [comment]
The issue is still active. You can pick it up. The goal is to add support for those new hashes in the specified analyzer

**Comment by mlodic** [comment]
Telfhash creators did not answer about creating a package in pip. I'll do it and then we can integrate it with IntelOwl

**Comment by mlodic** [comment]
the Pip project is available: https://pypi.org/project/telfhash/

**Comment by mlodic** [comment]
closed by #1073
