### ISSUE TITLE
Remove unused analyzers

### ISSUE THREAD

**Issue by darrellducote** [intelowlproject/IntelOwl#298]
This is my first time trying to write a post. So, forgive me if I do it wrong or leave out info.

I have searched for a few days trying to find a solution, but have not had any luck.

I tried commenting out analyzers in `analyzer_config.json` that I do not currently have API keys for to eliminate them from the "run all available analyzers" within the web GUI. When I do this, it breaks the "Select Analyzers" drop down. 

![image](https://user-images.githubusercontent.com/38150131/102642041-b073ba80-4122-11eb-9279-380abdd92db1.png)

Is there anyway I can temporarily remove them. Is there a different file I have to configure for this?

I have this installed on Centos 8

Thanks for any help.

**Comment by darrellducote** [comment]
As soon as I posted this, I read that json does not have a way to comment out an analyzer. I previously tried Django and Python style commenting. So, I'm guessing I will need to make a template file for this so I will have an original on hand. Would that be the proper way to handle this situation?

**Comment by mlodic** [comment]
Hey @darrellducote , thank you for your interest in the project!

Honestly I have already noticed that this could have been a possible problem for some users so I guess we should think about how to solve this in a clean way.

Meanwhile you could:
* disable the unwanted analyzers by adding a key `"disable": true` in the analyzers configuration (see [this](https://github.com/intelowlproject/IntelOwl/blob/master/configuration/analyzer_config.json#L1022) as an example of disabled analyzer)
* completely delete the unwanted analyzers configuration from the json manually.

We will update this issue as soon as we figure out a clean solution that does not involve manual changes by the user

**Comment by darrellducote** [comment]
@mlodic Thank you for your response.

I tried adding `"disable": true` and could not get that to remove it from the drop down. I did however make a template copy of the original `analyzer_config.json` and removed the analyzers I did not want from the original `analyzer_config.json` and that worked.

Thanks

**Comment by Eshaan7** [comment]
> I tried adding "disable": true and could not get that to remove it from the drop down.

Opened https://github.com/intelowlproject/IntelOwl-ng/issues/67 for this.

**Comment by Eshaan7** [comment]
@darrellducote Thank you for your patience. With the new [v2.2.0 release](https://github.com/intelowlproject/IntelOwl/releases/tag/v2.2.0), analyzers with `disabled: true` are excluded from the drop down. We have also added some awesome new features so make sure to checkout the changelog and update!!

Thank you for once again for bringing this issue to our notice.
