### ISSUE TITLE
How to get threat intel data

### ISSUE THREAD

**Issue by mfiedler144** [intelowlproject/IntelOwl#319]
Hello everyone, 

I just installed Intelowl, and I'm able to navigate the webserver. But I am just not able to figure out how to gather threat intel data from IOC-Feeds (like domain, IP, URL). I tried the job section, but it seems that you can upload data manually and analyze it.

Can anyone help please? I am using Ubuntu 18.04, the latest version of docker and docker-compose and intelowl. 

Best regards

Maurice

**Comment by CITIZENDOT** [comment]
Try navigating to http://localhost:80. Are you able to see the dashboard like [this](https://intelowlclient.firebaseapp.com/)? And yes, you can upload data manually and analyze it. 
Could you please describe your problem more?

**Comment by Eshaan7** [comment]
There are 2 ways you can submit analysis to IntelOwl: a.) webapp b.) CLI client.

For the webapp, look => [demo GIF](https://i.imgur.com/LzriEDq.gif)
For the CLI client, look => [installation](https://github.com/intelowlproject/pyintelowl#installation), [demo GIF](https://asciinema.org/a/vBqr6Jg93kdyTJqc1HwxmZITd)
