### ISSUE TITLE
VirusTotal v3 needs another query to retrieve data

### ISSUE THREAD

**Issue by tsale** [intelowlproject/IntelOwl#320]
Hello,

I just realized that the results returned from VirusTotal v3 are not complete. According to VT documentation, there should be another query with the exact relationship to return the requested data. 

![Pasted Graphic](https://user-images.githubusercontent.com/25332397/104834571-29b31a00-5855-11eb-8a80-314220df6f7a.png)

At the moment, it is only the id of the relationship and the related URLs returned as per below (same domain):

![Pasted Graphic 2](https://user-images.githubusercontent.com/25332397/104834809-b01c2b80-5856-11eb-86df-46cabf1a308d.png)

One would need to query the related links to retrieve the relevant information. I think that this withholds almost all of the valuable information that an analyst you like to receive to make an informed decision on a certain observable. Is this shortcoming going to be addressed in the future? VirusTotal is one of the most important APIs that, in my opinion, IntelOwl should utilize to the fullest.

**Comment by mlodic** [comment]
Thank you for opening the issue. 

This is a wanted behavior actually. The idea is that a normal user would expect this analyzer to use just a single VT quota each time he executes the analyzer. If you would like to get all the data that VT provides, ATM it is not possible from this analyzer.

We could add a "full" option (configurable) where the analyzer would "pivot" though the relationships and **use** a quota for each relationship, increasing the overall quota usage of this analyzer by about 10 times. This could be a wanted behavior for people who have enough resources to get all these data at once

**Comment by tsale** [comment]
It makes sense to not query all the relationships, my free quota would fly away and I wouldn't even have half of the data I need... I hope VT will at least increase the free quota before deprecating v2.
