### ISSUE TITLE
[API] Delete job endpoint +  button

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#324]
### Issue

At the moment there is not a way to delete old jobs manually.

The only way to remove jobs is:

1. wait for the cron that removes the old jobs. This cron is automatically launched once a day at night. It does remove jobs older than 3 days. It can be customized with the variable `OLD_JOBS_RETENTION_DAYS`.
2. Drop the database
3. The administrator can delete any job from the Django Admin Interface.

### Proposed Solution

**Web App:**

We could provide an API + a button in the GUI to allow the user to perform this operation directly. This should be added in:

1. The single job view
2. The dashboard

**CLI:**

Should also add a `IntelOwl.delete_job_by_id(job_id: int)` function in pyintelowl and create a corresponding command.

> Note: We should allow the users to only delete jobs created by themselves, while the administrator can already do it in the Django Admin Interface

**Comment by Eshaan7** [comment]
Should use the already implemented permissions using django-guardian package.

**Comment by Slavell** [comment]
Can you give advise how can i drop the database?

**Comment by Eshaan7** [comment]
> We could provide an API + a button in the GUI to allow the user to perform this operation directly. This should be added in:
> 
>     1. The single job view
> 
>     2. The dashboard

Tracking in IntelOwl-ng as #.

**Comment by Eshaan7** [comment]
> Should also add a `IntelOwl.delete_job_by_id(job_id: int)` function in pyintelowl and create a corresponding command.

Tracking in pyintelowl as

**Comment by Rishabh-Kumar-07** [comment]
Hi. I would like to work on this.

**Comment by sp35** [comment]
Hi, is this up for grabs?

**Comment by Eshaan7** [comment]
> Hi, is this up for grabs?

The endpoint has been added but the corresponding issue on pyintelowl repo is still open.

**Comment by sp35** [comment]
> > Hi, is this up for grabs?
> 
> The endpoint has been added but the corresponding issue on pyintelowl repo is still open.

This will be fixed in https://github.com/intelowlproject/pyintelowl/pull/71
