### ISSUE TITLE
404 doc pages, unclear instructions, outdated/missing dockerhub tags/images and more

### ISSUE THREAD

**Issue by seccentral** [intelowlproject/IntelOwl#325]
a few things:  
### **404 pages in docs** 

in page `https://intelowl.readthedocs.io/en/latest/Advanced-Usage.html#multi-queue` clicking on "example" leads to 404 page https://github.com/intelowlproject/IntelOwl/blob/master/docker-compose-multi-queue.yml#L29  

django users groups and permissions here `https://intelowl.readthedocs.io/en/latest/Installation.html#django-groups-permissions-settings` leads to 404 page `https://intelowl.readthedocs.io/en/latest/Advanced-Usage.md#django-groups-permissions`  

### **web UI bug** 
upon successful start of docker composition and creation of admin, clicking django admin console is useless, nothing happens. (i suppose that's where i was supposed to create non privileged regular users. Well, it doesn't work)  

### **Unclear documentation/vague/confusing** 
When attempting to start the composition, by default .env is ignored completely when running "python3 start.py prod up" leading to warnings and then errors:  
`WARNING: The INTELOWL_TAG_VERSION variable is not set. Defaulting to a blank string.`
this fails all docker builds since they have no tag assigned, i managed to start it by exporting INTELOWL_TAG_VERSION=v2.0.0 in the shell.  

Attempting to use https with letsencrypt is very vague and after trial and error I just installed nginx as a reverse proxy on the docker box and changed the docker ports exposed to listen to 127.0.0.1:80/443.
Documentation unclear: 

> After the configuration is done, you should either add the traefik.override.yml reference in the .env file or you can use the start.py script

That's nice, but what am i supposed to write in the .env file ? how exactly do i add "traefik.override.yml" to the .env file ? what syntax do i need to use ? a one liner example would have saved neurons and hours. The same .env file that was ignored on start btw.  

Enabling custom integrations from the integrations folder : instructions are just as vague: 

> In the project, you can find template file .env_file_integrations_template. You have to create new file named env_file_integrations from this.
> 
> Docker services defined in the compose files added in COMPOSE_FILE variable present in the .env file are ran on docker-compose up. So, modify it to include only the analyzers you wish to use. Such compose files are available under integrations/.

That env_file_integrations_template "template" is an empty file. what am i supposed to append to it ? Again, refering to the globally ignored .env file, I am supposed to create a variable named COMPOSE_FILE and what value do I assign to it ? What is the logic behind it ? After i supposedly figure out the logic, do i put it in the .env file or the env_file_integrations_template ? 

### **Docker hub missing tags and/or containers altogether**
First, NONE of the images except intelowl have corespoding v2.0.0 tag as defined in the required-but-ignored .env file.  
These don't work at all:

```bash
docker pull intelowlproject/intelowl_static_analyzers
Using default tag: latest
Error response from daemon: manifest for intelowlproject/intelowl_static_analyzers:latest not found: manifest unknown: manifest unknown
```

```bash
docker pull intelowlproject/intelowl_qiling
Using default tag: latest
Error response from daemon: manifest for intelowlproject/intelowl_qiling:latest not found: manifest unknown: manifest unknown
```
etc

Running `python3 start.py --all-analyzers prod up` gives,
 
```bash
python3 start.py --all_analyzers prod up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Pulling thug (intelowlproject/intelowl_thug:v2.0.0)...
ERROR: manifest for intelowlproject/intelowl_thug:v2.0.0 not found: manifest unknown: manifest unknown
```

**Comment by mlodic** [comment]
Hi and thank you for your report. I'll try to answer by points.

**404 pages in docs**
I have updated the docs with correct links. You can check the develop versions of the docs with the updated references: https://intelowl.readthedocs.io/en/develop/

**web UI bug**
did you use the last version from a clean installation or did you update from an old version?
Anyway, do you mean this button is not working? Was you logged with the superuser account? 
![image](https://user-images.githubusercontent.com/30625432/105684082-c11f0980-5ef4-11eb-9e78-39bffa69d9c8.png)

**Unclear documentation/vague/confusing**
About this: ` WARNING: The INTELOWL_TAG_VERSION variable is not set. Defaulting to a blank string.`, it correctly works if you execute `python3 start.py prod up` from the main directory of the project. See [docker docs](https://docs.docker.com/compose/env-file/). If it does not, it should be something not related to IntelOwl but to your own environment.

> After the configuration is done, you should either add the traefik.override.yml reference in the .env file or you can use the start.py script

This is a reference from a previous IntelOwl version. You cannot add that in the `.env` file anymore. Now to execute the `traefik` configuration you can just use `--traefik` like this:
```
python3 start.py prod --traefik up
```
Anyway, the HTTPS support is very basic and was just added to help some standalone installations. For production usage, you should set your own configuration (as you did) depending on your infrastructure.

> Enabling custom integrations from the integrations folder : instructions are just as vague:

Also this is from old IntelOwl setup. I'll update this doc too. To enable all the analyzers at once you can just use the `--all_analyzers` option like this: `python3 start.py prod --all_analyzers up`. That's all, you do not have to touch the .env file.

**Docker hub missing tags and/or containers altogether**
The builds for optional analyzers failed for the v.2.0.0. This is my fault, I did not notice it. I'll try to fix this ASAP

** Conclusion**
The tone of your report was not exactly "friendly". This is open source and there are people behind it that work hard to give this project to everyone for FREE. We should collaborate in a nice and friendly environment. So, please next time say "hi", present yourself, say "please" and do not be sarcastic about errors. Thank you in advance.

Also, you can always contact us directly on Twitter if you want to have a chat or a more direct feedback or help.

**Comment by mlodic** [comment]
You can use the last version to find everything fixed.
