### ISSUE TITLE
Create a PR template for the master branch

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#328]
This is to help maintainers to remember to do everything before creating a release:

Some remainders:

- [ ] update `CHANGELOG.md` for the new version

- [ ] change version number in `conf.py` and `.env`

- [ ] verify CI tests

- [ ] create the release for the branch `develop`

- [ ] wait for dockerHub to finish the builds

- [ ] merge the PR to the `master` branch

**Comment by m0mosenpai** [comment]
Hi, I would like to take this issue up.

**Comment by m0mosenpai** [comment]
@mlodic I was testing out using multiple templates on a private repo and I created a new file `release_template.md` with the above 4 points inside the `.github` directory but I couldn't get it to display when I opened a PR. It would default to showing the `pull_request_template.md` only. Is there anything else that needs to be done besides the creating a new template file to make it work and is there supposed to be an option to choose/set a particular template? 
I looked this up online and could only find that adding `?template=release_template.md` query to the PR URL is the way to switch to a template.

**Comment by mlodic** [comment]
It seems that all the PR templates should be put in a specific directory called `PULL_REQUEST_TEMPLATE` inside the `.github` folder. The point is: by having 2 different templates what will happen then? No template would be pre-populated by default and you would have to remember to add that query string you mentioned to the URL? If it is like that this is really non-user friendly and imho bad for new contributors and for maintainers. Not everyone can know how this would work...

**Comment by m0mosenpai** [comment]
Yeah, that's what I was thinking as well.  I was trying to find some graphical list/ option to select the template according to the type of PR, but I changing the query in the URL was the only thing I could find. <br>
One alternative to this could be to maybe automate the entire process of creating new releases? Like an action scheduled to run every X amount of days - make sure the necessary changes are made, the tests are passed and `develop` is merged into `master`

**Comment by mlodic** [comment]
Good idea, most of this (except the changelog text) could be automated. However I guess this is not a fast work and in the future it could be subject of change. So I would prefer to do not this. 

I think that, for now, we can just save a template for this without adding it as a real PR template. I mean, like you have already did. You created a `release_template.md` that is not detected by Github as a template. The maintainers know about that and can just copy and paste it at the time of the release. Fast and still a bit useful. Better keeping that template there than in this issue. What do you think about?

**Comment by m0mosenpai** [comment]
Yeah, for sure. Having something there which is accessible would be great. I'll just make a PR with `release_template.md` then. We could maybe think of automating all this in the future sometime since I do feel that it would scale well and creating releases would be one less thing to worry about.

Any other points I should add to the template besides the 4 mentioned above?

**Comment by mlodic** [comment]
I just splitted the last point, then I think this is fine
