### ISSUE TITLE
Reduce complexity: django object/model permissions

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#341]
We are using django object permissions but we are also using django model permissions. At some places, these are intermixed and that is troubling.

**Comment by m0mosenpai** [comment]
Hey, is it possible if you could specificy one or two places where this occurs and causes issues? I'm trying to understand more about the issue a bit, thanks.

**Comment by Eshaan7** [comment]
**Clarification**: Yes, they are supposed to be intermixed and used together but it's complex to manage for any admin managing an IntelOwl instance. 

**Example**: It may be better to overwrite the `get_permissions` method on the viewset rather than using `django-guardian` to store the object permissions.

**Comment by iharshit009** [comment]
Hi @eshaan7, I got some understanding of intelowl and have knowledge of Django Viewsets. Can I take this up and work on it?

**Comment by eshaan7** [comment]
@iharshit009 This issue has by and large solved as part of #856 by making use of the _organizations_ pattern available in [certego_saas](https://github.com/certego/certego-saas).

**Comment by iharshit009** [comment]
> @iharshit009 This issue is by and large solved as part of #856 by making use of the _organizations_ pattern available in [certego_saas](https://github.com/certego/certego-saas).

Okay no issues, Let me know if I could contribute to this in any way. Will look for other issues.

**Comment by mlodic** [comment]
I consider this closed so we can start to better filter out issues for the v4 milestone
