### ISSUE TITLE
How do I change the IntelOwl's logo on the installation homepage. 

### ISSUE THREAD

**Issue by rocheston** [intelowlproject/IntelOwl#342]
How do I change the IntelOwl's logo on the installation homepage (http://localhost). I'm using Docker version of IntelOwl's.

I tried to replace the logo in static and static_intel directories. But still not reflected when the page is loaded.

Please help.

**Comment by mlodic** [comment]
hi @rocheston, thank you for your interest in the project! How do you plan to use IntelOwl?

**Comment by Eshaan7** [comment]
Hi. Are u talking about the logo on the login page ?

All assets visible on the webpage are actually stored in the `IntelOwl-ng` repository which holds the frontend code. (see [assets](https://github.com/intelowlproject/IntelOwl-ng/blob/master/src/assets) folder). Currently, there is no way for a user to overwrite this logo.

**Comment by rocheston** [comment]
I figured it out. It is in the intel_owl_nginx container. Changed the logo beautifully there. Thanks.

**Comment by mlodic** [comment]
I would like to remember that you must follow the license terms: https://github.com/intelowlproject/IntelOwl/blob/master/LICENSE

Can you please tell us how do you plan to use the IntelOwl project? Thank you
