### ISSUE TITLE
ThreatFox (from Abuse.ch) analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#348]
There is this new great tool from Abuse.ch: https://threatfox.abuse.ch/api/

We should create a simple analyzer to check if an analyzed observables is in the threatfox database ("Search an IOC" query)

**Comment by Shreyas220** [comment]
Hey @mlodic, I'd like to work on this, I would be very grateful if you could give me some pointers on how to get started as this is my first time contributing and I'm new to security.

**Comment by mlodic** [comment]
thank you for your interest but there is already a PR opened for that: https://github.com/intelowlproject/IntelOwl/pull/350

New analyzers are a good way to start into this project. Even if they are not listed in the issues, any service that leverages web APIs + provide threat intel info is good for IntelOwl. You can propose also one of your own

**Comment by Shreyas220** [comment]
I dont know how, but  i might have missed noticing the PR 🤔
Sure thank you @mlodic  ill keep learning and contributing

**Comment by mlodic** [comment]
@Shreyas220 I closed that PR because it was unfinished. If you are still on, you can try to work on it.

**Comment by mlodic** [comment]
this is pretty easy and start contribution for newcomers. I strongly encourage to get this opportunity
