### ISSUE TITLE
Add archive.org's wayback as url analyzer

### ISSUE THREAD

**Issue by subhashissuara** [intelowlproject/IntelOwl#351]
Will it be beneficial if we add [archive.org's](https://archive.org/) wayback machine to url analyzers? We can fetch the closest archived snapshot if it exists and return it. If it's good to go, I would like to work on it.

**Comment by mlodic** [comment]
Hey @subhashissuara thank you for your interest in the project!

The service you mentioned is something related to OSINT and it would follow the IntelOwl schema correctly. So this is basically a potentially good idea.

However the point is that I do not see any pratical way to leverage that tool for *cyber security*. IntelOwl could be also used as a generic OSINT tool but it is not its goal. There are better open source tools for that. Our main goal is to provide analyzers that can be useful for investigations about cyber threat actors or during potential security incidents.

If you can show me a practical use case in one of the mentioned area, I am here to hear from you.

**Comment by subhashissuara** [comment]
You are right, it needs to be useful for cyber security. I don't have anything solid off my mind at the moment however if I do, I will definitely let you know!
