### ISSUE TITLE
Integrate new Community Greynoise endpoint

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#380]
https://developer.greynoise.io/reference/community-api

We should integrate it inside the already existing `greynoise.py` module and set the new version as the default.

**Comment by palrohitg** [comment]
@mlodic  Can share little more insight about the issue. 
As I am able to understood we had version v1 for greynoise_api 
`additional_config_params.get("greynoise_api_version", "v1")` 
and we need to set to default 
`additional_config_params.get("greynoise_api_version", "default")`

**Comment by sp35** [comment]
Hi @palrohitg `additional_config_params` are defined in the [analyzer_config.json](https://github.com/intelowlproject/IntelOwl/blob/master/configuration/analyzer_config.json), so you'll have to set the default version there. 

You need to set the new version as default that is `v3` not `default.`

As for what you have already noticed, these are instances when a default value for a parameter is set, if not set from the config file. So you change these to `v3` as well.

**Comment by mlodic** [comment]
This is a very first good issue to solve. We would just need to update an already existing analyzer. I encourage new contributors to go through this.

**Comment by palrohitg** [comment]
@sp35 Hi, Thanks for the clarification. I updated  all the instance of v1 to v3 in both [analyzer_config.json](https://github.com/intelowlproject/IntelOwl/blob/master/configuration/analyzer_config.json) and [greynoise.py](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/script_analyzers/observable_analyzers/greynoise.py)

**Comment by mlodic** [comment]
solved with #417
