### ISSUE TITLE
OpenCTI analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#401]
We could create an analyzer for [OpenCTI](https://www.opencti.io/en/). This would leverage the [official python client](https://github.com/OpenCTI-Platform/client-python) to look for a specific observable in a OpentCTI instance.

This would require some knowledge of OpenCTI and set up an OpenCTI instance locally. We could use [how it is implemented in Cortex](https://github.com/TheHive-Project/Cortex-Analyzers/blob/master/analyzers/OpenCTI/opencti.py) as an example

**Comment by mwatermolen** [comment]
1+ Just came here to say this!
