### ISSUE TITLE
[New Analyzer] YETI platform

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#426]
The guys behind this other threat intel project have just released a python client to interact with the platform.

The same way as we have a "search" option for other TI platforms like the MISP, we could have it for YETI.

[Example reference from the readme of the library](https://github.com/yeti-platform/pyeti#search-for-observables)

**Comment by sp35** [comment]
I see a scope for adding a `YETI Connector` as well, like #12.

**Comment by mlodic** [comment]
Sure!

**Comment by sp35** [comment]
I'm thinking of using the API directly for purposes other than search since the client doesn't raise exceptions.
Tracking https://github.com/yeti-platform/pyeti/issues/21
