### ISSUE TITLE
Ubuntu 18.04 Bionic Universe Issue

### ISSUE THREAD

**Issue by PolarBearGod** [intelowlproject/IntelOwl#427]
The `ReadTheDocs` has two gaps in the installation instruction if the user is using a default Ubuntu 18.04 LTS build. 

1. The `docker` and `docker-compose` are significantly out of date in the Bionic Universe if using `apt` (or `apt-get`). So much so that following the directions as is, creates errors like the below which will prevent starting the project at all.

```
(WARNING: The INTELOWL_TAG_VERSION variable is not set. Defaulting to a blank string.)
ERROR: manifest for intelowlproject/intelowl:${INTELOWL_TAG_VERSION} not found: manifest unknown: manifest unknown
```

The issue can be corrected one of two ways. A bandaid solution would be grabbing a copy `~/IntelOwl/docker/.env` and dropping it into the root `~/IntelOwl/` directory. You can run the following `$ cp ~/IntelOwl/docker/.env ../.env`. One should keep in mind that this is a bandaid solution. As the project matures and grows, its dependencies on the later versions of `docker` and `docker-compose` will ultimately break any attempts to update. 

The better path is to remove `docker`, `docker-compose`, and a few other apps: 

`sudo apt remove docker docker-compose docker-engine docker.io containerd runc && sudo apt update`

Next would be installing `docker` according to the official Docker Ubuntu [installation docs](https://docs.docker.com/engine/install/ubuntu/). Once installed, install `docker-compose` according to the official Docker [docs ](https://docs.docker.com/compose/install/) as well.

2. The other issue in the docs is really minor but important until Python 2 officially goes away. The directions instructs to use `python ~/IntelOwl/start.py prod up`. If using the base install of Ubuntu, this will fail with any number of errors. Mostly due to `python` running the old 2.7 version and not being able to handle the Python 3+ script. The solution here is to install `python3.6`  or later (as instructed in the requirements) and call the script as `python3`.

**Comment by int3ring0** [comment]
Ran exactly into this problem and copying the .env file worked for me.
Thanks
