### ISSUE TITLE
[New Analyzer] Analyzer for mnemonic PDNS

### ISSUE THREAD

**Issue by masq** [intelowlproject/IntelOwl#428]
[mnemonic PDNS API Documentation](https://docs.mnemonic.no/display/public/API/PassiveDNS+Integration+Guide)

Notably, authentication is optional (using an API key means you have some agreement/payment with mnemonic), though the plugin implementation should at minimum account for users having one, and would ideally account for the different types of queries an authenticated user might want to make (e.g. changing TLP).

Otherwise, this seems like a straightforward API.

**Comment by uzair-ali10** [comment]
Hey, I would like to work on this
Can u pin-point which endpoints are we interested in and the observable types which will be supported by API

**Comment by mlodic** [comment]
The API is well documented and provide examples. 

This analyzer should support the same functions that are available in common PDNS services. Please take a look to the other PDNS-related analyzers like dnsdb.

**Comment by 0x0elliot** [comment]
I decided to take care of this issue as I had time and it was a simple one :D
