### ISSUE TITLE
Hash support beyond MD5? [NO REAL SHA256 / SHA1 Support]

### ISSUE THREAD

**Issue by mwatermolen** [intelowlproject/IntelOwl#436]
Why are  SHA256's and SHA1's being MD5'ed, wouldn't this make intelowl near useless for any non-MD5 hashes?

Is there any plan to resolve this?

![image](https://user-images.githubusercontent.com/73605619/116620749-dd717e80-a907-11eb-9226-c68ee24a0a99.png)
![image](https://user-images.githubusercontent.com/73605619/116620830-fb3ee380-a907-11eb-9b7d-ba42fea60582.png)
![image](https://user-images.githubusercontent.com/73605619/116621571-fd557200-a908-11eb-8db6-438177a26ba8.png)

**Comment by mlodic** [comment]
Hey, first of all please say Hi, your name and so on...this is open source, try to be gentle.

Then, you did not understand at all what that the `md5` field exists for. We use that value as a key for the database. As a user, you should completely ignore that value. IntelOwl does search correctly for the shaX hash you asked for. Like every other observable, the analyzed value is saved in `observable_name` and, on the backed side, we save the correspondant md5 as a the primary index. This is not an issue.

**Comment by mwatermolen** [comment]
@mlodic Thanks for the heads up.

**Comment by mlodic** [comment]
You are welcome. Feel free to ask for advice. Even on Twitter for a more direct approach if you prefer.

**Comment by mlodic** [comment]
yes, the client should also support this edge case. We will add the support for the next release. Meanwhile you can just lowercase the md5

**Comment by mwatermolen** [comment]
Much appreciated, Thank you!
