### ISSUE TITLE
Update Censys.io analyzer to v2

### ISSUE THREAD

**Issue by sp35** [intelowlproject/IntelOwl#439]
Censys data can enrich many security products and platforms.

#### Endpoint
- Get structured data about a specific host or website. https://censys.io/api/v1/docs/view

**Comment by mlodic** [comment]
it makes sense. One question: do they provide a free quota/plan too?

**Comment by sp35** [comment]
Yes, a limited free access for non-commercial use.

**Comment by sp35** [comment]
Missed it somehow, we already have it :sweat_smile:
([censys.py](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/script_analyzers/observable_analyzers/censys.py))

**Comment by mixmax18** [comment]
please pointing to endpoint censys V2

**Comment by mlodic** [comment]
can you please help us with a reference of the docs of what you would like to be implemented? are v1 endpoints no more available?

**Comment by mixmax18** [comment]
the v1 endpoint has deprecated 

> Notice: The Censys Search v1 endpoints are deprecated as of Nov. 30, 2021. Please begin using v2 endpoints to query hosts and certificates and check out our [support center](https://support.censys.io/hc/en-us/sections/360013076551-Censys-Search-2-0) for resources.

for reference https://search.censys.io/api

**Comment by mlodic** [comment]
I have reopened the issue. The project is open source and it is very easy to update a new analyzer if you follow the documentation. If you need this change fast, I strongly suggest you to develop this and propose a PR.
