### ISSUE TITLE
[New Analyzer] - Virushee

### ISSUE THREAD

**Issue by sp35** [intelowlproject/IntelOwl#440]
Scan files by hash https://api.virushee.com
- [x] Privacy: deletes all analyzed files

#### Endpoints
- [Check file status by SHA256 / SHA1 / MD5 hash](https://api.virushee.com/#operation/hash)
- [Upload file sample for analysis](https://api.virushee.com/#operation/upload)

**Comment by 0x0elliot** [comment]
I would like to take care of this issue.

**Comment by fear-the-reaper** [comment]
If it's possible can I also try to do this issue?

**Comment by sp35** [comment]
This analyzer would be a file analyzer and requires the following:
1. Checking if file results are already available by searching for the file's hash (`https://api.virushee.com/file/hash/{hash}`).
2. If the hash is not found, the file should be uploaded (`https://api.virushee.com/file/upload`) and results can be polled using the task id received after upload (`https://api.virushee.com/file/upload`). 

Configuration params: These make the analyzer more flexible. The ones I can think of right now would be: `force_scan` (default False) - this would upload the file anyways to obtain a fresh result, `results_polling_interval` - (default 10s).

Bonus: The first task can be reused to create a hash-type analyzer.

You can refer to the Virustotal analyzers which do the same, if it gets a bit difficult to understand, just follow the steps mentioned above.

**Comment by sp35** [comment]
> I would like to take care of this issue.

@0x0elliot Are you working on this issue?

**Comment by 0x0elliot** [comment]
@sp35 I have gotten a little busy with other work. It's fine if someone else wants to tacke this issue for now!

**Comment by fear-the-reaper** [comment]
Alright. Can I be assigned this task then?

**Comment by fear-the-reaper** [comment]
Bit of a stupid question but for this analyzer, I'll get the file right? Then I'll take out its hash and then see if it has results or not.

**Comment by fear-the-reaper** [comment]
Also, how can I test the analyzer I'm making? I made the developer instance and everything but am still confused on how to check it and everything. Sorry for the questions this is my first time doing something like this.

**Comment by mlodic** [comment]
Please, before asking, please read through all the documentation about how to contribute then check other analyzers code as an example, like @sp35 mentioned.

**Comment by uzair-ali10** [comment]
Hey, Please assign this one to me I've created a PR (#792)  against it

**Comment by eshaan7** [comment]
> Bonus: The first task can be reused to create a hash-type analyzer.

Yep, I like that! We can create 2 analyzers out of Virushee.

- `Virushee_CheckHash` observable analyzer for `hash`.
- `Virushee_UploadFile` file analyzer.

>  The ones I can think of right now would be: force_scan (default False) - this would upload the file anyways to obtain a fresh result,

This too. This parameter should be added to the `Virushee_UploadFile` file analyzer.

**Comment by eshaan7** [comment]
> Also, how can I test the analyzer I'm making? I made the developer instance and everything but am still confused on how to check it and everything.

Since you already made the development instance then,
- build and up the docker containers
- create a django superuser
- open a browser and navigate to http://localhost/ and click on "Scan a File". 
- Upload a file and select your new analyzer's name from the dropdown list and simply start the scan.

Do remember to thoroughly read the [Contribute docs](https://intelowl.readthedocs.io/en/latest/Contribute.html).

**Comment by eshaan7** [comment]
Hi, @fear-the-reaper. Any progress update ? are you still interested in working on this issue ? You can ask questions on the slack chat if you need help with anything.

**Comment by fear-the-reaper** [comment]
> Hi, @fear-the-reaper. Any progress update ? are you still interested in working on this issue ? You can ask questions on the slack chat if you need help with anything.

I've gotten busy with my university projects and final exams so right now I haven't done anything. Really sorry!

**Comment by uzair-ali10** [comment]
> > Hi, @fear-the-reaper. Any progress update ? are you still interested in working on this issue ? You can ask questions on the slack chat if you need help with anything.
> 
> I've gotten busy with my university projects and final exams so right now I haven't done anything. Really sorry!

So I should take up this issue?

**Comment by fear-the-reaper** [comment]
> > > Hi, @fear-the-reaper. Any progress update ? are you still interested in working on this issue ? You can ask questions on the slack chat if you need help with anything.
> > 
> > I've gotten busy with my university projects and final exams so right now I haven't done anything. Really sorry!
> 
> So I should take up this issue?

Yeah sure no problem.

**Comment by eshaan7** [comment]
**Update:**

Reference to: https://github.com/intelowlproject/IntelOwl/issues/440#issuecomment-988828006. 

The file analyzer was created but observable analyzer still remains. Feel free to ask to be assigned to work on it.

**Comment by Yshaq** [comment]
Hey, I'd like to work on this issue and add the observable analyzer. I've gone through the project code and I think I'll be able to implement it.
