### ISSUE TITLE
[New analyzer] - onionscan

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#505]
GitHub: https://github.com/s-rah/onionscan

```bash
onionscan --jsonReport notarealhiddenservice.onion
```

There are 2 ways to integrate this:
a) as a docker based analyzer
b) compile and store as binary which can executed with subprocess

I'd prefer option `b`, because docker based analyzer should be made only as the last resort.

**Comment by fear-the-reaper** [comment]
Can you elaborate on option b like do we use forking or something?

**Comment by mlodic** [comment]
[this analyzer](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/analyzers_manager/file_analyzers/signature_info.py) is an example of executing the binary with subprocess

**Comment by CypherpunkSamurai** [comment]
Hello Sir, would you mind if it work on this issue as well? I've worked with python3 as well as golang projects, I feel comfortable with the issue requirements.

**Comment by eshaan7** [comment]
Go ahead, @CypherpunkSamurai. Feel free to ask questions on the [Honeynet slack chat](https://gsoc-slack.honeynet.org/) (channel: `#2021-intelowl`).

Basically, 
- you should clone the latest version of onionscan and compile it as a standalone executable that does not require golang to be installed to use.
- put the binary inside `configuration/` folder of IntelOwl.
- read through the [contribution guide](https://intelowl.readthedocs.io/en/latest/Contribute.html) on how to add a new analyzer (refer to the [`signature_info.py`](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/analyzers_manager/file_analyzers/signature_info.py) analyzer)

We recommend raising a draft PR early with incomplete changes and then you can keep working on that issue. This way we can track your progress and actively review and help.

**Comment by CypherpunkSamurai** [comment]
Sure thing. Thank you :)

**Comment by CypherpunkSamurai** [comment]
Hello everyone, I had a few questions.  

> * you should clone the latest version of onionscan and compile it as a standalone executable that does not require golang to be installed to use.

I think adding precompiled x86, amd64, and arm64 arch binaries for Win, Linux, and MacOS would make the repo bulky. Can we utilize any bootstrap script that would download pre-compiled binaries from github?

**Comment by CypherpunkSamurai** [comment]
Update:
I don't think binaries for Win and MacOS are required as the deployment is container only (I didn't find any manual deployment method in the docs so I'll assume).

That leaves us to architecture. I assume they will use amd64 docker host so I will download the binary using `repo_downloader.sh` script.

**Comment by mlodic** [comment]
> put the binary inside configuration/ folder of IntelOwl.

We cannot download the binary from you personal repo. Please just embed it to the application itself.

Then amd64 is ok but we just need to remember to explicitly state this problem in the description/documentation of the analyzer. In this way people know the constraints before using the analyzer.

**Comment by CypherpunkSamurai** [comment]
> > put the binary inside configuration/ folder of IntelOwl.
> 
> We cannot download the binary from you personal repo (as you did in your first draft PR). Please just embed it to the application itself.

Sure. I was also thinking adding my external repo executable would be a security issue. I'll make sure to add it in the next PR. There's another option, we can use gobinaries.com.

> Then amd64 is ok but we just need to remember to explicitly state this problem in the description/documentation of the analyzer. In this way people know the constraints before using the analyzer.

Ok. I will make sure to document that onionscan is x64 only and user should compile it themselves for other architectures.

**Comment by CypherpunkSamurai** [comment]
Hello Sir, I'm having trouble understanding why [this line](https://github.com/CypherpunkSamurai/IntelOwl/blob/b8ce2fc7477fdb53fe333962cb766bbacc32d2d8/api_app/analyzers_manager/observable_analyzers/onionscan.py#L47) is not working during the [tests ](https://github.com/intelowlproject/IntelOwl/runs/4553843215?check_suite_focus=true).

The module is supposed to run onionscan binary and wait for output. onionscan take around a few minutes to scan any domain, but the test isn't waiting long enough, so the stdout is "", which raises exceptions.

Can someone please point out what I might be doing wrong?

**Comment by sp35** [comment]
@CypherpunkSamurai use `monkeypatch` for it

**Comment by CypherpunkSamurai** [comment]
> @CypherpunkSamurai use `monkeypatch` for it

Oh. Thanks for the tip 😄

**Comment by CypherpunkSamurai** [comment]
Hello everyone,
I'm having a little problem getting the monkey patch to work with `subprocess.Popen`. I tried setting up a simple Popen class in a new py file on my local machine and it works but when I try the similar patch with the IntelOwl module it doesn't work. 

Can anyone please point out what I might be doing wrong? :)

Mock implementation at ([L96](https://github.com/CypherpunkSamurai/IntelOwl/blob/dabe4c7381fff95c465aba264f7a8f3ac6b1d024/api_app/analyzers_manager/observable_analyzers/onionscan.py#L96) and [L21](https://github.com/CypherpunkSamurai/IntelOwl/blob/dabe4c7381fff95c465aba264f7a8f3ac6b1d024/api_app/analyzers_manager/observable_analyzers/onionscan.py#L21))
