### ISSUE TITLE
Exiftool download link broken

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#507]
broken link: https://exiftool.org/Image-ExifTool-12.26.tar.gz

**Comment by Eshaan7** [comment]
wayback link can be used instead: http://web.archive.org/web/20210521005103/https://exiftool.org/Image-ExifTool-12.26.tar.gz

**Comment by m0mosenpai** [comment]
Is there any particular reason we can't use the link for versions > 12.26 instead?

**Comment by mlodic** [comment]
solved [here](https://github.com/intelowlproject/IntelOwl/commit/f60b868b328d5caf4fc8ca36f6ea9d67a5f93a83), available from the next version
