### ISSUE TITLE
[v3] Plugin actions: Kill, retry, healthcheck

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#534]
- The `kill` can be made on top of [`celery.app.control`](https://docs.celeryproject.org/en/stable/reference/celery.app.control.html) by using corresponding task IDs which we store already.
- For `retry`, we have to construct the same arguments again and call `run_plugin` again. Another way could be to have someway to store the `Plugin` object instance and just call the `.start()` method again but I don't think this is doable.
- `healthcheck`: it would be good to have a some sort of basic check to see if that instance/URL is up or not.

**Checklist**:
- [x] 1. Kill (#572)
- [x] 2. Retry (#582)
- [x] 3. Healthchecks (for: connectors + docker based analyzers) (#627 )

**Comment by sp35** [comment]
We know if an analyzer, say docker plugin is configured or not but is it running? (health check)

**Comment by sp35** [comment]
The point behind this was that all my connector calls would fail if the associated instance is not running. For this we are adding a call re-run option. But it would be good to have a some sort of basic check to see if that instance is up or not.

**Comment by mlodic** [comment]
Yep a healthcheck against the associated instances (MISP, etc) can be useful to add

**Comment by Eshaan7** [comment]
> But it would be good to have a some sort of basic check to see if that instance is up or not.

I did not think about it like that. You are definitely right, this could indeed be a great addition. Like a ping-pong that just tells whether the instance/URL is reachable or not.

Note: This could be useful even for the docker analyzers.

**Comment by Eshaan7** [comment]
Tracking in clients as:
- PyIntelOwl (https://github.com/intelowlproject/pyintelowl/issues/111)
- IntelOwl-ng (https://github.com/intelowlproject/IntelOwl-ng/issues/123)
