### ISSUE TITLE
Maxmind updater broken in `develop-2` branch

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#536]
This a side-effect of the recent refactor.

**Comment by Eshaan7** [comment]
We will check everything once all refactoring is done. If we fix now, it might break again.

**Comment by Eshaan7** [comment]
This is because the `Maxmind.updater` function was made an instance method but was a class method before. Need to figure out a good way to convert it into a class method again passing as argument the API key.
