### ISSUE TITLE
[Discussion] `FileAnalyzer` with empty `supported_filetypes` and `not_supported_filetypes`.

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#538]
There are FileAnalyzers for which the fields `supported_filetypes` and `not_supported_filetypes` are empty `[]`.

How should we handle the `filter_analyzers` function (which checks the `job.file_mimetype` against these) in such a case ?

**Comment by m0mosenpai** [comment]
We could assume if none of these fields are set, they support all filetypes perhaps? And if that's not the case for some analyzers, we can manually update these parameters similar to what we did for the missing secrets.

**Comment by Eshaan7** [comment]
Analyzers that have these problem:

```python3
['Cuckoo_Scan',
 'Cymru_Hash_Registry_Get_File',
 'File_Info',
 'HybridAnalysis_Get_File',
 'MISPFIRST_Check_Hash',
 'MISP_Check_Hash',
 'MalwareBazaar_Get_File',
 'MWDB_Scan',
 'OTX_Check_Hash',
 'Strings_Info_Classic',
 'Strings_Info_ML',
 'Triage_Scan',
 'VirusTotal_v2_Get_File',
 'VirusTotal_v2_Scan_File',
 'VirusTotal_v3_Get_File',
 'VirusTotal_v3_Get_File_And_Scan',
 'Yara_Scan_Community',
 'Yara_Scan_Daily_Ioc',
 'Yara_Scan_FireEye',
 'Yara_Scan_Florian',
 'Yara_Scan_Inquest',
 'Yara_Scan_Intezer',
 'Yara_Scan_McAfee',
 'Yara_Scan_ReversingLabs',
 'Yara_Scan_Samir',
 'Yara_Scan_Stratosphere']
```

**Comment by mlodic** [comment]
shouldn't we need to handle this like before? I noticed that some logic was removed in `filter_analyzers` in `develop-2`

**Comment by mlodic** [comment]
https://github.com/intelowlproject/IntelOwl/blob/master/api_app/helpers.py#L62

**Comment by Eshaan7** [comment]
> shouldn't we need to handle this like before?

So as @m0mosenpai said, we just let them run for all file types ?
