### ISSUE TITLE
use dataclasses and not serializer in `Plugin`

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#539]
Now that we have the dataclasses, we should use them only in the `Plugin` (and it's subclasses).

Changes required:

- [x]  `Plugin.__init__` will take an instance of `config: AbstractConfig` and not `config_dict: Dict`. (and saved as `self._config`) 
     * changes will be required in `Plugin`, `ObservableAnalyzer`, `FileAnalyzer`, `Connector` classes and `run_analyzer` and `run_connector` functions.
      
- [x] `_serializer` cached_property: not needed anymore.
- [x] `_params` cached_property:  make it a normal `@property` and `return self._config.config`
- [x]  The `_read_secrets` method on `AbstractConfigSerializer` should be move to `AbstractConfig` dataclass instead.
- [x] `_secrets` cached_property: `return self._config._read_secrets()`
- [x] other bug fixes that might arise because of this change

**Comment by sp35** [comment]
>_serializer cached_property: not needed anymore.
>
This would require changes in analyzers using the constants (like `ObservableTypes`) via `_serializer`.
