### ISSUE TITLE
CIRCLPassiveDNS should be unconfigured if default secret is applied

### ISSUE THREAD

**Issue by sp35** [intelowlproject/IntelOwl#543]
https://github.com/intelowlproject/IntelOwl/blob/856208c73d79544c2fe74caf6e7c6de0df554a51/docker/env_file_app_template#L27

While the default secret is helpful for knowing the format, the analyzer should not run with these credentials (it can be marked unconfigured)

**Comment by Eshaan7** [comment]
Nice catch. We could change those lines in the `env_file_app_template` such as:

```bash
# format: user|pass
 CIRCL_CREDENTIALS=
```
