### ISSUE TITLE
[New Analyzer] Emailrep.io

### ISSUE THREAD

**Issue by AshishBhadouria** [intelowlproject/IntelOwl#546]
Hi Folks, 

I would like to suggest a new analyzer to add.

https://emailrep.io

Please have a look.

**Comment by m0mosenpai** [comment]
https://github.com/intelowlproject/IntelOwl/blob/master/api_app/script_analyzers/observable_analyzers/emailrep.py

I think we already have this one implemented if I'm not mistaken

**Comment by mlodic** [comment]
yep :P

**Comment by AshishBhadouria** [comment]
yep. saw it later. Thanks for your response.
