### ISSUE TITLE
Keep docker images and docker analyzers updated

### ISSUE THREAD

**Issue by 0ssigeno** [intelowlproject/IntelOwl#554]
Right now we are not verifying via Dependabot neither docker-images versions nor some requirements that are hardcoded inside the dockerfile of some docker analyzers.

I think that leverage the `package-ecosystem`  `docker` inside dependabot.yml should solve the first issue.
For the second, I don't have a clean solution, since a lot of packages unfortunately are not in a package manager system

**Comment by Eshaan7** [comment]
Fixed in https://github.com/intelowlproject/IntelOwl/commit/74878c7636d573819825834544bd5547a1a4c2e0.
