### ISSUE TITLE
RIPE API analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#56]
Get WHOIS for a specific IP with the RIPE API:

https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API
https://www.ripe.net/manage-ips-and-asns/db/support/documentation/ripe-database-query-reference-manual#tables-of-query-types-supported-by-the-ripe-database
http://jaluther.blogspot.com/2016/04/python-for-network-engineers-part-2.html

**Comment by 0x0elliot** [comment]
can you assign this issue to me? i can work on this but i am not sure what is to be done with the fetched WHOIS after it is fetched. kindly elaborate :>

**Comment by CITIZENDOT** [comment]
Hey another Mr.Robot fan, Take a look [here](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-analyzer), on how to add new analyzer. You can see [some analyzers](https://github.com/intelowlproject/IntelOwl/blob/develop/api_app/script_analyzers/observable_analyzers/shodan.py) as an example. Basically, After quering and getting the data, you have to return it from `run()` function inside the Analyzer class. Everything else is taken care by the classes.

**Comment by 0x0elliot** [comment]
nice! when i have time i will try contributing to it. thanks for pointing me in the right direction :D

**Comment by 0x0elliot** [comment]
i am still a little confused as to how i can accept the IP address as the parameter to use. any guidance?

**Comment by CITIZENDOT** [comment]
IP address and type of the observable (whether it is IP/domain/URL) is passed as `self.observable_name` and `self.observable_classification` respectively.

**Comment by 0x0elliot** [comment]
currently i am having a problem where the results are not showing up at /pages/scan/result/1 for my addition specifically. it isn't even in the list.

**Comment by mlodic** [comment]
If you like you can join the [Honeynet Slack channel](https://gsoc-slack.honeynet.org/) where you can have a faster chat than here if you require some technical help during development.

**Comment by 0x0elliot** [comment]
thanks! i have it joined. i will communicate there when i can ^^
