### ISSUE TITLE
[tests] API/models permissions, groups

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#561]
Inside the `test_api`, we are currently using the admin user so we are basically bypassing all permissions.

We should define test cases where we use normal users and verify their permissions/groups. For example, enabling/disabling certain permissions to a group/user and then making request to a protected endpoint and verify that the behavior changed.

-------
[back reference to previous issue](https://github.com/intelowlproject/IntelOwl/issues/229#issue-723352673)

**Comment by uzair-ali10** [comment]
Hey!!
From what I've understood is that currently in [`test_api`](https://github.com/intelowlproject/IntelOwl/blob/master/tests/test_api.py) all the views are tested against a Super User. And it is desired to test them against a normal user correct??
If this is the case please assign this to me i could take this up

**Comment by eshaan7** [comment]
You are right but the issue #341 needs to be solved prior to working on this.
