### ISSUE TITLE
Add other useful hashes to PE_Info analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#569]
- [x] Dhashicon implemented [here](https://github.com/fr0gger/SuperPeHasher/commit/e9b753bf52d4e48dda2da0b7801075be4037a161#diff-2bb2d2d4d25fef20a893a4e93e96c9b8c0b0c6d5791fc14594cc9dd5cbf40b41)

- [x] [ImpFuzzy](https://github.com/JPCERTCC/impfuzzy)

**Comment by CypherpunkSamurai** [comment]
Hello Sir, Can I work on this issue please? :)

I have a basic understanding of file signature checks and PE signature checks, and I would like to know it better.

**Comment by mlodic** [comment]
Updates on this?

**Comment by CypherpunkSamurai** [comment]
I've completed implementing `Dhashicon` module on my local machine, I'll be working on `ImpFuzzy` next and push a draft commit.

**Comment by CypherpunkSamurai** [comment]
Thank You Mr. @mlodic and Mr. @eshaan7 for helping me along this issue :)
