### ISSUE TITLE
Team Cymru Hash analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#58]
We could create an analyzer that checks a specific hash against the malware database of Team Cymru

https://www.team-cymru.com/mhr.html

**Comment by mlodic** [comment]
I have just contacted them and asked for permission to integrate this tool in Intel Owl. I will update this issue as soon as I receive a response.

**Comment by mlodic** [comment]
They said ok! Working on it!

**Comment by Eshaan7** [comment]
Commits by @mlodic - https://github.com/intelowlproject/IntelOwl/commit/23917299720c765cb9383826c535567e9947d69b, https://github.com/intelowlproject/IntelOwl/commit/d49ecbb8ef411b124361b42eb672155f58b8d488
