### ISSUE TITLE
VirusTotal Sandbox analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#59]
We could add another analyzer for VirusTotal that extracts the sandbox reports available for a specific file.

https://developers.virustotal.com/v3.0/reference#file-behaviour-summary

**Comment by Aena11** [comment]
can I work on this??

**Comment by Aena11** [comment]
can I work on this?

**Comment by mlodic** [comment]
Sure, you are welcome

**Comment by sp35** [comment]
@mlodic what's the update on this? I guess it is already done since we call the `behaviours` relationship in `vt3`

https://github.com/intelowlproject/IntelOwl/blob/caf4bc9ea60ce6e60a4a2c203ab9a4a8b2e81264/api_app/script_analyzers/observable_analyzers/vt3_get.py#L192-L194

**Comment by mlodic** [comment]
no, it is not the same, we need to call the other available endpoints and not only those relationships because they just provide links without the full information

**Comment by m0mosenpai** [comment]
Checklist:
- [X] VT Sandbox (`/files/{id}/behaviour_summary`) [#617]
- [ ] VT Analyzer for Sigma Analysis (`/sigma_analyses/{id}`)
