### ISSUE TITLE
moving and updating IntelOwl-Ng documentation

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#611]
I think that we should move the IntelOwl-Ng documentation inside the official IntelOwl documentation so everything is in a single place considering that those 2 projects are a single one at the end.

Plus, we would need to add more information for developers in the same sections that we already use in the IntelOwl docs (`Contribute` and `Tests`). In this way the developers would find everything they need to touch everything inside the project in a single ordered place

**Comment by Eshaan7** [comment]
If we move the IntelOwl-ng docs to the main one, then should we move pyintelowl docs to the main one too ? this doesn't seem feasible. We already link the client docs in the main one that's sufficent.

**Comment by mlodic** [comment]
everything that could be easier for a new developer to start working on it
