### ISSUE TITLE
Disable connectors before release

### ISSUE THREAD

**Issue by sp35** [intelowlproject/IntelOwl#612]
Connectors by nature are optional.
Task: set `disabled=true` in `connector_config.json`

**Comment by sp35** [comment]
Another possible issue is that users might want to use separate instances for the connectors (connectors: MISP and OpenCTI share the same keys as their analyzers (`MISP_KEY`, `OPENCTI_KEY`, etc)). 

The keys for connectors can be renamed to `CONNECTOR_*`. Then the connectors will be unconfigured at the start so they won't run and we can be kept enabled.

**Comment by mlodic** [comment]
yep, it makes sense. They should not share the keys
