### ISSUE TITLE
[New analyzer] Spyse.com API

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#613]
Mark from their marketing team reached out to me on Twitter for this integration a long time back but I forgot about it.

SDK: https://github.com/spyse-com/spyse-python

**Comment by Palash-Vishnani** [comment]
I can work on this issue. Will you please elaborate what do I have to do exactly.?

**Comment by sp35** [comment]
Hi @Palash-Vishnani, thank you for your interest in contributing to the project. You need to look for the services which can be integrated as an analyzer.

- https://spyse-dev.readme.io/reference/ips#ip_details (observable_type - `ip`)
- https://spyse-dev.readme.io/reference/emails#email_details (observable_type - `general`)
- https://spyse-dev.readme.io/reference/domains#domain_details (observable_type - `domain`)
- https://spyse-dev.readme.io/reference/history#domain_whois_history (observable_type - `domain`)

See the docs on [How to add new analyzer?](https://intelowl.readthedocs.io/en/latest/Contribute.html#how-to-add-a-new-analyzer)
Join us on Slack [@Honeynet Slack](https://honeynetpublic.slack.com/archives/C01KVGMAKL6), if you need any help regarding development.

**Comment by m0mosenpai** [comment]
Another thing, we are in works of releasing a new version which brings about a lot of changes in the project (It may or maynot be or concern to you depending on the timeline of your PR). The process for the addition of analyzer is not going to be affected as much but just giving a heads up.

**Comment by Eshaan7** [comment]
Hello, @Palash-Vishnani. Welcome to IntelOwl, you are more than welcome to work on this issue.

Here are some tips:
- Fork the repository and checkout to `develop-2` branch, from there create a new branch `dev-spyse`
```bash
git checkout develop-2
git checkout -b dev-spyse
```
- The analyzer configurations are defined in the `configuration/analyzer_config.json` file. Similar to the existing entries, you've to create a new entry for Spyse. 
- Let me give you an example: If you look at the `Shodan_Search` entry in this JSON file, you will see it's python module points to a file named `shodan.py` inside which we have a class named `Shodan` which is a child class of `ObservableAnalyzer` class. Similar to this, you should create a `spyse.py` file with a class `Spyse` that inherits from `ObservableAnalyzer`. You will overwrite the `set_params` method with the logic of getting the API key and the `run` method is where the main logic lives.
- As @sp35 has mentioned the various different endpoints that Spyse has so we want to support all of them but that doesn't mean we need different analyzer/`.py` file for each. Instead, it can be made as part of a single new analyzer only. Meaning the `observable_supported` of this new analyzer will be: `["ip", "domain", "generic"]`. Depending on which observable classification was passed to the class instance (accessed with: `self.observable_classification`), the endpoint to be queried will change.

**Comment by Eshaan7** [comment]
Hi, @Palash-Vishnani. Feel free to drop into our slack [@Honeynet Slack](https://honeynetpublic.slack.com/archives/C01KVGMAKL6), if you need any help regarding development.

**Comment by Palash-Vishnani** [comment]
Sorry for the delay, I was busy because of my exams. I will start working on this issue soon now.

**Comment by Palash-Vishnani** [comment]
Hey,  just confirming ..which git command should I use to push this new `dev-spyse` branch from my local system to my remote forked IntelOwl repository??? And the origin should be `master` or `develop` branch?
