### ISSUE TITLE
Use drf-flex-fields package

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#615]
I'd recommend the use of [DRF-Flex-Fields](https://github.com/rsinger86/drf-flex-fields) package. Using this, we can specify at the time of request what fields we want so we wouldn't require different endpoints.

_Originally posted by @Eshaan7 in https://github.com/intelowlproject/IntelOwl-ng/issues/125#issuecomment-893295790_

**Comment by mlodic** [comment]
just one thing: please always care when adding more packages if not strictly needed. We have already too many dependencies to manage

**Comment by sp35** [comment]
How about we just take the fields required as a GET parameter?

**Comment by Eshaan7** [comment]
That's basically what DRF flex fields achieves with other advanced stuff. I wouldn't want to roll out a custom solution as it can be hard to manage.
