### ISSUE TITLE
updated PR template based on v3 changes

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#619]

**Comment by m0mosenpai** [comment]
Fixed in #610

**Comment by Eshaan7** [comment]
- [ ] We should add a bullet point regarding the `_moneypatch` method.
- [ ] A point about that in case of file analyzer, the analyzer name has to be defined manually in the `tests/analyzers_manager/test_file_scripts` file but not in case of observable analyzer.
