### ISSUE TITLE
Support for TLP, both for analyzers and connectors

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#638]
> That could/should condition which analyzers can be invoked and if/how an IOC and relatives analyses can be shared with external parts. Example: tag an IP as TLP:RED => only run internal/fully controlled analyzers, do not submit the IP to external platforms, and keep the result as well as the IOC for internal users only

At the moment there are 3 options for visibility and privacy:
![image](https://user-images.githubusercontent.com/30625432/129700460-177899d0-d2b1-494b-8322-3a5522adafeb.png)

* `leaks_info` flag: disable analyzers that could impact privacy
* `external_service` flag: disable analyzers that use external services
* `private` flag: limit view permissions to my groups

I guess that, even if this does make sense, it is too much complicated and could be simplified by leveraging the Traffic Light Protocol.
Also the TLP could be used to check if we can share an analysis or not with the configured connectors. ATM the connectors can only be active or not and there is no a granular way to choose which analysis we want to share (@sp35 could you confirm this?).
We could add an option on each connector where the user can choose which is the TLP minimum value of the related analysis that can be accepted for sharing (default would be the highest, TLP:white)

Also, the corresponding relation with the flags could be something like:
* TLP: RED. all the 3 previous flag set. 
* TLP: AMBER: `leaks_info` and `private` flag set.
* TLP: GREEN: `leaks_info` flag set.
* TLP: WHITE: no flag set.
(obviously this should be explicitly declared somewhere in the GUI)

Plus, this could be also used to change the configuration at runtime of the analyzers like VT, MWDB, Intezer, etc that provide the option `upload_file` that would be changed based on the TLP set. (upload only if TLP:white is set for instance). Anyway this could be changed even without the TLP rework.

**Comment by sp35** [comment]
>
there is no a granular way to choose which analysis we want to share (@sp35 could you confirm this?)
>
Yes that's right, also with #629, the user can specify the connectors to execute, but as of now the default behaviour is to execute all enabled connectors.

**Comment by sp35** [comment]
Tracking in clients

- [ ] IntelOwl-ng (https://github.com/intelowlproject/IntelOwl-ng/issues/138)
- [ ] Pyintelowl

**Comment by mlodic** [comment]
This was not implemented in the #641 PR:

> Plus, this could be also used to change the configuration at runtime of the analyzers like VT, MWDB, Intezer, etc that provide the option upload_file that would be changed based on the TLP set. (upload only if TLP:white is set for instance). Anyway this could be changed even without the TLP rework.
