### ISSUE TITLE
[v3] Allow to run only one or few analyzers in unit tests

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#642]
Related to #540.

**Comment by mlodic** [comment]
Yeah I guess that if we do not find a fast solution, we could just solve this problem with a proper documentation.

At the end, it is just an issue for active developers so they can manage it while developing by adding a line of code

This is your example: (https://github.com/intelowlproject/IntelOwl/blob/c550d7fda52912ad569104ac78b98271b82d716f/tests/analyzers_manager/__init__.py#L192)
