### ISSUE TITLE
[v3] osslsigncode package not working in tests and outdated

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#643]
The same we did for Exiftool (#448), we should move the `osslsigncode` package from the Dockerfile (installed in the underline system as an apt *outdated* package) to a custom download and installation.

In this way we can keep control of the most recent version of the tool. For instance, they have released the 2.2 version few days ago (https://github.com/mtrojnar/osslsigncode/releases/tag/2.2) while the APT package was still at the 1.7

In particular, we noticed that that package does not correctly work in the test suite of the recent PR (#640)

**Comment by Eshaan7** [comment]
The #645 is a good and temporary fix for this. So this isn't a priority.
