### ISSUE TITLE
[v3] hash uppercase bug

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#658]
If we try to analyze an hash by inserting adding it with lowercase, it would be analyzed correctly. That's ok.

If we try to analyze it again by inserting it in uppercase, it would be analyzed again because it would be considered as a different observable with 2 different md5s. That's not good. They should be treated by the server as the same observable and the analysis should not be repeated. On the client side, I would leave the things like they are now to allow flexibility but, on the server side, I would force the lower case.

**Comment by Eshaan7** [comment]
we can just call `observable_name.lower()` before saving it in the `Job`. What do u think ?
