### ISSUE TITLE
[New analyzer] Use pyelftools to have static analysis of ELF files

### ISSUE THREAD

**Issue by 0ssigeno** [intelowlproject/IntelOwl#659]
Since we are using PeFile to analyze Portable executable headers, we can have the symmetrical type of analysis, but for ELF files.

We can use [pyelftools](https://github.com/eliben/pyelftools) to solve that.

**Comment by mlodic** [comment]
this would be a new analyzer that would leverage that tool.

**Comment by 0x0elliot** [comment]
Hey! I would like to work on this analyzer. The only question I have is what commands exactly do you want me to run for this on the given ELF binary?

**Comment by mlodic** [comment]
I'd guess you can go through their examples as mentioned [here](https://github.com/eliben/pyelftools/wiki/User's-guide#users-guide) and see what you can extract from an ELF file.

We would also need to add a test ELF file for tests (and also to the test_files.zip) (we could use [this](https://github.com/eliben/pyelftools/blob/master/examples/sample_exe64.elf))

**Comment by 0x0elliot** [comment]
Okay, I will get to it then. Thank you, Matteo.

**Comment by mlodic** [comment]
closed by #1073
