### ISSUE TITLE
Change analyzer behavior at runtime as per TLP

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#673]
This was not implemented in the #641 PR:

> Plus, this could be also used to change the configuration at runtime of the analyzers like VT, MWDB, Intezer, etc that provide the option upload_file that would be changed based on the TLP set. (upload only if TLP:white is set for instance). Anyway this could be changed even without the TLP rework.

_Originally posted by @mlodic in https://github.com/intelowlproject/IntelOwl/issues/638#issuecomment-902797929_

**Comment by mlodic** [comment]
this has been implemented in the afflicted analyzers
