### ISSUE TITLE
Google WebRisk analyzer config

### ISSUE THREAD

**Issue by andre-ame** [intelowlproject/IntelOwl#739]
Tried to setup Google WebRisk analyzer following documentation, my json file in configuration/service_account_keyfile.json, added Api Key in docker/env_file_app. 

Now I'm getting this json when I try run it 
`[
  "/opt/deploy/intel_owl/configuration/service_account_keyfile.json should be an existing file. Check the docs on how to add this file to properly execute this analyzer"
]` 

Is there any step I missed?

P.S. environment variable GOOGLE_APPLICATION_CREDENTIALS = /opt/deploy/intel_owl/configuration/service_account_keyfile.json

**Comment by mlodic** [comment]
Hi @ame90, I think you should restart the application to have the file properly loaded.

We'll push an adjustment to avoid this for the next patch. Thank you for your report
