### ISSUE TITLE
IntelOwl 3.1.0 - Mime Type Identification Error

### ISSUE THREAD

**Issue by OG-Sadpanda** [intelowlproject/IntelOwl#743]
IntelOwl 3.1.0 modules do not evaluate mime types of files properly. Modules still run against an unsupported file type causing errors in the output. 

### Example: EXE File scan THUG_HTML_Info Output

![image](https://user-images.githubusercontent.com/1459500/137927775-024a5e1d-f700-424f-a1a1-f71bbbf39ce9.png)

### Example: EXE File scan BOXJS_Scan Output

![image](https://user-images.githubusercontent.com/1459500/137927921-66f8c9cb-e365-4ef9-8940-11cb70ba2a33.png)

**Comment by eshaan7** [comment]
The fix for this will be released in the next patch release v3.1.1.
