### ISSUE TITLE
`extends` key in plugin configuration

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#752]
### Problem Description

Currently, there's no way to extend an existing configuration entry. 

For instance, take the case of `Shodan_Honeyscore` and `Shodan_Search` analyzer configurations. Both share most attributes differing in only few i.e. `description` and `params` so there is redundant copy-pasta between them.

https://github.com/intelowlproject/IntelOwl/blob/eaf95756d3af07c6604f8737896100cf22a5a68a/configuration/analyzer_config.json#L2413-L2470

Same problem applies to many other pairs too.

### Proposed Solution(s)

1. An `extends` attribute, like so:

```javascript
"Shodan_Honeyscore": {
    "type": "observable",
    "python_module": "shodan.Shodan",
    "description": "scan an IP against Shodan Honeyscore API",
    "disabled": false,
    "external_service": true,
    "leaks_info": false,
    "observable_supported": ["ip"],
    "config": {
      "soft_time_limit": 30,
      "queue": "default"
    },
    "secrets": {
      "api_key_name": {
        "env_var_key": "SHODAN_KEY",
        "description": "",
        "required": true
      }
    },
    "params": {
      "shodan_analysis": {
        "value": "honeyscore",
        "type": "str",
        "description": ""
      }
    }
  },
  "Shodan_Search": {
    "extends": "Shodan_Honeyscore",
    "description": "scan an IP against Shodan Search API",
    "params": {
      "shodan_analysis": {
        "value": "search",
        "type": "str",
        "description": ""
      }
    }
  },
```

i.e. `Shodan_Search` should,
- inherit all attributes from `Shodan_Honeyscore`
- overwrite for the attribute values defined explicitly in `Shodan_Search`
- overwrite-merge the `dict` attributes such as `params`, `secrets` and `config`.

**Comment by eshaan7** [comment]
Code:

```python3
from copy import deepcopy
from deepmerge import always_merger

def deep_merge(base, nxt) -> dict:
    return always_merger.merge(deepcopy(base), next) # need to use deepcopy to prevent modification to `base`
```

```python3
class AbstractConfigSerializer(rfs.Serializer):
    ...
   @classmethod
    def read_and_verify_config(cls) -> dict:
        ...
        for key, entry in config_dict.items():
            entry["name"] = key
            extends = entry.pop("extends", None)
            if extends is not None:
               entry = deep_merge(config_dict[extends], entry)

            serializer = cls(data=entry)
         ...
```

**Comment by 0x0elliot** [comment]
Can I take up this issue? Seems like a simple one now that you have laid it down. Which exact file do I need to edit other than <a href = "https://github.com/intelowlproject/IntelOwl/blob/master/configuration/analyzer_config.json">analyzer_config.json</a>?

**Comment by eshaan7** [comment]
This is not ready for work at the moment actually. Note the "needs approval" label.

**Comment by devmrfitz** [comment]
@eshaan7 @mlodic Can this be picked up for inclusion in GSoC proposal?

**Comment by eshaan7** [comment]
ideally this should be solved after #433.

**Comment by devmrfitz** [comment]
@eshaan7 How does [this](https://github.com/intelowlproject/IntelOwl/issues/752#issuecomment-1094261743) connect with #443?
#443 has to do with env_file_app while #752 has to do with analyzer_config.json

**Comment by devmrfitz** [comment]
> ideally this should be solved after (or in accordance with) #433.

How does this issue connect with #443?
#443 has to do with env_file_app while this has to do with analyzer_config.json

**Comment by eshaan7** [comment]
- 433 has to do with analyzer_config.json
- 978 has to do with env_file_app

See my comment [here](https://github.com/intelowlproject/IntelOwl/issues/433#issuecomment-1099073836).

**Comment by devmrfitz** [comment]
@eshaan7 @mlodic Can there be a chain of `extend`s i.e. A extends B while B itself extends C. 

If yes, we should also create a way to check for `extend`ing cycles, right?

**Comment by mlodic** [comment]
Honestly I won't complicate things too much. Just having a simple extension feature like the example made by Eshaan would be a great addition to the project.

**Comment by devmrfitz** [comment]
I made it to handle cycles too internally :)
