### ISSUE TITLE
Undderstanding Intelowl

### ISSUE THREAD

**Issue by fear-the-reaper** [intelowlproject/IntelOwl#755]
Hello, I am trying to understand the system and ecosystem of intelowl where I am trying to find out why is it integrating with other platforms such as MISP, making and using analyzers, other features, and overall concept and logic. Thank you in advance!

**Comment by eshaan7** [comment]
Hi.

IntelOwl is for aggregating maximum amount of threat intelligence data about a particular observable (IP, domain, hash, URL) or file. This data is collected from external sources or tools that are available as _analyzers_ inside of IntelOwl. You can query an observable/file against 100s of these analyzers and all the data is returned to you in a unified manner. Automation and ease-of-use is key here so all this is possible in just 2 HTTP calls to [IntelOwl's REST API](https://github.com/intelowlproject/pyintelowl).

IntelOwl is composed of two sets of plugins - Analyzers and Connectors.

- **Analyzers:**
    -  Used to retrieve data from external sources (e.g. VirusTotal, AbuseIPDB) or to generate intel from internal analyzers (e.g. Yara, Oletools)
    - [List of available analyzers](https://intelowl.readthedocs.io/en/latest/Usage.html#available-analyzers)
- **Connectors:**
    - Used to export data collected from analyzers to external platforms (e.g. MISP, OpenCTI, YETI)
    - [List of available connectors](https://intelowl.readthedocs.io/en/latest/Usage.html#available-connectors)

When requesting a job/analysis, you can choose precisely what analyzers or connectors should be executed or by default IntelOwl will only run the analyzers appropriate for the specific observable type or file type.

IntelOwl tries to be most flexible and abstract as to enable different use-cases and capabilities for different users/organizations. So the best way to understand it is to try it out yourself. See the [TL;DR installation](https://intelowl.readthedocs.io/en/latest/Installation.html#tl-dr) to get IntelOwl up and running on your system in about 10 minutes.
