### ISSUE TITLE
IntelOwl Freezes upon Starting A Scan

### ISSUE THREAD

**Issue by xander8945** [intelowlproject/IntelOwl#772]
I absolutely love IntelOwl so far, but I'm running into an issue where everytime I try to run a scan, the virtual machine I'm running freezes. If I power cycle the machine and reboot IntelOwl, it will sometimes complete the scan, but it might also just freeze. After enough reboots it will eventually complete. 

I'm running IntelOwl in Virtualbox using Kali 2021.3. 
![image](https://user-images.githubusercontent.com/67572719/142663660-5dbfa7cf-db04-461b-bbc5-2a679d2ef419.png)
If you note the difference in time in the top right and bottom right, it has been frozen for about 20 minutes.
I wasn't able to find any information on this issue. Any thoughts as to what might be the culprit?

**Comment by mlodic** [comment]
hey, thank you for your interest in the project!

I guess it is just a matter of VM resources, in particular the RAM I would guess (OOM issue in the VM).

ATM we do not provide specific system requirements (see existing [issue](https://github.com/intelowlproject/IntelOwl/issues/751)). We need to do some work for that.

Did you run IntelOwl with additional options (for instance `--all_analyzers`)? Removing the additional options would reduce the RAM usage. 

Anyway IntelOwl is pretty heavy so even a VM with 2CPU and 4GB RAM could not be enough.

**Comment by xander8945** [comment]
Thank you for the quick reply!
I tried upping the ram to 12G and the CPU to 6 with no luck. It's not running out of hard drive space, as its only 15G/80G Looking at the terminal it seems to always freeze upon loading a directory from yara, but it's a different directory each time.

**Comment by xander8945** [comment]
Nevermind, I just got a freeze during the API call to virustotal, so it's not unique to yara

**Comment by mlodic** [comment]
🤔 honestly I don't know how I could help more for now...as said, we know that sometimes IntelOwl could leverage a high amount of RAM. Other than that I think we would just need to do more testing. FYI we are using IntelOwl in servers with 2 CPU and 10GB RAM and it's all ok there.

**Comment by mlodic** [comment]
closing this because we have no similar report for the new IntelOwl v4. Please try out the new major version
