### ISSUE TITLE
[New Analyzer] - emergingthreats.net

### ISSUE THREAD

**Issue by uzair-ali10** [intelowlproject/IntelOwl#773]
http://apidocs.emergingthreats.net/

Supported Observable Types are Domain and IP

**Comment by uzair-ali10** [comment]
Assign this issue to me

**Comment by mlodic** [comment]
ok but how can you test this? do they provide free access because it seems not

**Comment by uzair-ali10** [comment]
ea they Ohh yes it sees that they do not have a free tier plan, my bad

**Comment by mlodic** [comment]
closing because it is closed intelligence
