### ISSUE TITLE
Enforce mypy

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#774]
http://mypy-lang.org/

**Comment by eshaan7** [comment]
This requires:
- making a configuration file for mypy
- adding mypy action to our lint pipeline in the CI
- fixing existing and adding type hints everywhere in the codebase

**Comment by devmrfitz** [comment]
@mlodic I would like to work on the first 2 subtasks. If it goes well, I'll then take up the 3rd subtask too

**Comment by mlodic** [comment]
won't be done for now.
