### ISSUE TITLE
new Yara rule repo to add

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#782]
https://github.com/fboldewin/YARA-rules

**Comment by CypherpunkSamurai** [comment]
> https://github.com/fboldewin/YARA-rules

Hello Sir, I'd like to contribute to the issue. Please allow me.

I also had a few questions regarding this issue. So, as the title says, am I just supposed to add all the yara rules available in the linked repo to our repo?

**Comment by mlodic** [comment]
Hi

you just need to add another analyer configuration based on the Yara analyzer like [this one](https://github.com/intelowlproject/IntelOwl/blob/master/configuration/analyzer_config.json#L3656).
Plus, you should instruct IntelOwl to download the new repo [here](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/analyzers_manager/repo_downloader.sh).

So there is no python code needed to solve this, just some configuration to add

**Comment by CypherpunkSamurai** [comment]
Sure. Thank you for your help, I'll do my best 😄

**Comment by CypherpunkSamurai** [comment]
Hello Sir, I've made a few changes and proposed a PR. Please review it and advise if changes are necessary :)
