### ISSUE TITLE
Error with "Yara_Scan_Custom_Signatures" in documentation

### ISSUE THREAD

**Issue by CorraMatte** [intelowlproject/IntelOwl#797]
Hi guys,
I was trying to create a configuration for some custom Yara signatures as explained in the official documentation (https://intelowl.readthedocs.io/en/latest/Usage.html#example-add-an-analyzer-configuration-for-your-own-yara-signatures), but I got some errors.

I managed to configure it properly, adding some missing required fields and removing a syntax error.
This is the final configuration that runs without errors:

```
  "yara_scan_custom_rules": {
    "type": "file",
    "python_module": "yara_scan.YaraScan",
    "description": "Executes Yara with custom signatures",
    "disabled": false,
    "external_service": false,
    "leaks_info": false,
    "secrets": {},
    "config": {
        "queue": "default",
        "soft_time_limit": 100
    },
    "params": {
        "directories_with_rules": {
        "value": ["/opt/deploy/yara/custom_ruleset"],
        "type": "list",
        "description": ""
      }
    }
  }
```

**Comment by mlodic** [comment]
hey, 

yeah that documentation was not updated correctly after the changes we made for the IntelOwl v3 major release.

I'll update the docs with your example. (or if you prefer become one of the contributors, you can submit a PR with your changes so you get the credit)

thank you!

**Comment by CorraMatte** [comment]
Perfect, I'll create the PR

**Comment by CorraMatte** [comment]
Here the PR https://github.com/intelowlproject/IntelOwl/pull/809
