### ISSUE TITLE
add Malpedia Yara rules

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#798]
similar to #782 

 https://github.com/malpedia/signator-rules/tree/main/rules

The problem is that this repo contains a lot of rules, so we should think about how to properly manage them.
We should solve the issue #741 before.

This problem has a high priority

**Comment by CypherpunkSamurai** [comment]
Hello sir, would you mind if i work on this issue please? :)

**Comment by CypherpunkSamurai** [comment]
Hello Sir, as there are issues regarding mass importing of Yara rules I'll make a draft PR for now and add the Malpedia rules.

**Comment by mlodic** [comment]
done with v3.3.1
