### ISSUE TITLE
add Github action tests to check if the sphinx build did work before releasing

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#804]
Right now, a bug to a dependency for the docs caused the build of the docs to fail in ReadTheDocs.

I noticed it before making a new release randomly. We need to have an automatic and reliable way to check if the docs will work in the releases just before creating them.

**Comment by devmrfitz** [comment]
We can create a test that gets triggered based on [releases](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release). Should I make a PR to that effect?

**Comment by devmrfitz** [comment]
@mlodic Should we mark this issue as resolved?
