### ISSUE TITLE
Http failure response for

### ISSUE THREAD

**Issue by alexmartz001** [intelowlproject/IntelOwl#808]
After installing, and following the steps of https://intelowl.readthedocs.io, when executing an analysis it shows a 
Scan Request Failed error
Http failure response for http://x.x.x.x/api/analyze_observable: 500 Internal Server Error (undefined: undefined)
  
After reviewing the dashboard you see a job but if results, when deleting the job it shows another error

Job # 1
![2](https://user-images.githubusercontent.com/14192836/146664715-d188e872-c62b-4dee-bbd8-d8c091f9cb84.png)
![1](https://user-images.githubusercontent.com/14192836/146664717-7eb68137-c53f-4732-92c3-ba213343b8ab.png)

Could not be deleted. Reason "Insufficient Premission".

**Comment by mlodic** [comment]
hey, thank you for reporting this.

We need the raw logs to understand the problem behind and if it is related to the application or the deployment.

To share them, please go in `/var/lib/docker/volumes/intel_owl_generic_logs/_data/django` and send us the content of the files called `*_errors.log`. If you think they may contain sensitive content, you have two options: either you clean the sensitive content and send them to us or if you want to share those files only with us and not publicly here you can contact me on Twitter  (https://twitter.com/matte_lodi)

**Comment by alexmartz001** [comment]
Thanks for your support, I have checked the configuration and the logs but
I have not been able to solve the problem, I send you the files from the
indicated directory

**Comment by v3daxt** [comment]
I am having the same issue when I try to run Intelowl with elastic and kibana.. And when I set elasticsearch=False in env file, Intel owl works normally. But I need to run both intelowl and kibana

**Comment by mlodic** [comment]
do you mean `ELASTICSEARCH_ENABLED` to `True`? Did you populate `ELASTICSEARCH_HOST` too?

**Comment by v3daxt** [comment]
Yes `ELASTICSEARCH_ENABLED=True` & `ELASTICSEARCH_HOST=localhost:9200`

**Comment by mlodic** [comment]
Ok I think it does not work because of the `ELASTICSEARCH_HOST` point to localhost.

IntelOwl is running in containers. This means that if you point to localhost you are pointing to the container itself: if you have an ElasticSearch instance running on the same server, that won't work.

This was a use case we did not considered. We assumed that the users would have pointed to an external ElasticSearch.
I think that an idea could be to add an option when executing the startup script (`start.py`) where we run an ElasticSearch container in IntelOwl. In that way, we would support that use case and it would be enough to add `elasticsearch:9200` as `ELASTICSEARCH_HOST`.

Can you confirm my hypothesis? thanks

**Comment by devmrfitz** [comment]
@mlodic This method of spinning an elasticsearch container could be helpful in GreedyBear too as ElasticSearch is its compulsory dependency

**Comment by mlodic** [comment]
Yeah but they are 2 different use cases:
* IntelOwl allows to store and leverage ElasticSearch as an _additional_ way to analyze and manage IntelOwl data. So its usage is optional. (We could create an issue regarding the addition of ElasticSearch as I mentioned)
* in Greedybear we *need* an ElasticSearch instance, specifically a T-POT ElasticSearch instance. When not having this option  (for example, while testing), we need to have running an internal ElasticSearch so it is possible to fake data into and test the application. (this is also a very useful thing to add to that project). Related: https://github.com/honeynet/GreedyBear/issues/23

**Comment by devmrfitz** [comment]
@mlodic I've made PR #874 for this. Please have a look
