### ISSUE TITLE
optimize number of docker-based analyzers.

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#842]
ATM [these](https://intelowl.readthedocs.io/en/latest/Advanced-Usage.html#optional-analyzers) are too many to be executed all together. As we have already done for the `static_analyzers` container, we should group some of them together, at least the ones that share something.

The first idea could be to merge `box-js` and `apk_analyzers` inside the `static_analyzers` image and then rename this one in `malware_analysis_tools`

**Comment by eshaan7** [comment]
> The first idea could be to merge box-js and apk_analyzers inside the static_analyzers image and then rename this one in malware_analysis_tools

I agree.

**Comment by eshaan7** [comment]
Going forward we can have 3 category of these integration containers:
- all tools that can be installed in a local-only manner (no external dependency on a daemon or API) which should be added to the `malware_tools_analyzers`
- tools that just work completely differently like rendertron and cannot be combined with any other
- TOR/darkweb/crypto/etc tools should be added to a new integration by the name of `tor_analyzers`.

**Comment by eshaan7** [comment]
`tor_analyzers` integration was added in #505.

**Comment by Yshaq** [comment]
Hey, please assign this issue to me, working on it with #882

**Comment by mlodic** [comment]
done with v3.3.1
