### ISSUE TITLE
New analyzer - Cyberchef

### ISSUE THREAD

**Issue by 0ssigeno** [intelowlproject/IntelOwl#843]
It is possible to have an instance of a [cyberchef server](https://github.com/gchq/CyberChef-server) and talk through it via API.
We could have this an external analyzer in IntelOwl, allowing users to write, or import, their recipes.
This can be useful to extract malicious payload from malwares, like it was made in this [repo](https://github.com/mattnotmax/cyberchef-recipes#recipe-61---extract-second-stage-urls-from-qakbot-excel-maldocs).

**Comment by devmrfitz** [comment]
@mlodic I'd like to work on this

**Comment by CypherpunkSamurai** [comment]
Hello @devmrfitz! I'm an aspiring contributor just like you, so I thought I'd help you out :)

Here are some tips to get started quickly!
* Clone IntelOwl and run it once on your PC. (you can also use [gitpod.io](https://gitpod.io) to run it if your PC has low resources).
* Make a fork of IntelOwl and go to the `develop` branch and make a new branch from it, and name it something matching the feature you're working on.
* Make Sure to Read [Contribution Guidelines](https://intelowl.readthedocs.io/en/latest/Contribute.html) and how to run tests locally.
* Read and check out the issue description and related links.
* Try making a single file local implementation of the feature without the whole IntelOwl framework.
* Make a draft PR so mentors can keep track of your progress.
* Feel free to ask questions on the slack channel and here :)

✌🏼

**Comment by devmrfitz** [comment]
In this task, are the recipes (like [this one](https://github.com/mattnotmax/cyberchef-recipes#recipe-61---extract-second-stage-urls-from-qakbot-excel-maldocs) to be hardcoded and run when the relevant document is uploaded?

**Comment by mlodic** [comment]
well, I would like to add some considerations about this task:

* interaction against a CyberChef server: the are 2 possible types of integration
    * integration with an external CyberChef server. The easiest. This would be a simple analyzer
    * integration with a CyberChef server embedded in IntelOwl as as an optional Docker analyzer. See [here](https://intelowl.readthedocs.io/en/latest/Advanced-Usage.html#optional-analyzers). For this case, we would connect to the internal CyberChef server. This would be really awesome. Nature of IntelOwl is to also provide tools inside IntelOwl itself when possible. We can build a Docker image like suggested [here](https://github.com/gchq/CyberChef-server#docker)
* considering that we would send strings, as you mentioned, to the CyberChef server, IntelOwl would need to accept complex input. So I think that the CyberChef analyzers could support only "generic" type of observables
* Then yes, it would be great to embed/upload pre-configured recipes and create/add custom ones and run them (we could think it similarly to Yara). My idea is that we could just embed some of the most valuable recipes that we find in that link (like the  last ones listed there) and create _a new analyzer configuration_ for each of them.

So the flow could be:

string to be analyzed -> pick `CyberChef_<recipe_name>` analyzer -> IntelOwl performs the request to the CyberChef server -> IntelOwl retrieves and show the data.

* We would need to add the recipes to an appropriate folder. Default ones (that would be converted to default Analyzers) and custom ones.
* We would need to provide a little manual where we explain how it is possible to add a new CyberChef analyzer based on a defined recipe (similarly on how we explain this for Yara now)

By having a different analyzer for each CyberChef recipe, an analyst can properly choose the right analyzer based on the situation. Usually, when an analyst wants to leverage CyberChef, he already knows what he needs to transform/debofuscate so he knows which kind of transformation he would need. By having those pre-built in IntelOwl Analyzer, he would be able to re-use common "recipes" to solve this easily.

One concern about that is that the IntelOwl GUI won't be able to easily support long strings as input. On the other hand, by leveraging APIs, it would be really cool to create particular and awesome analysis flow, in particular regarding the "upcoming" investigation feature (see #680). 

Imagine that first we launch some file analyzers for a suspicious sample -> we understand it is Ursnif malware -> we could automatically send the string we know it is needed to be analyzed to CyberChef Ursnif recipe as a second step.

thoughts?

**Comment by mlodic** [comment]
The problem regarding having a new analyzer for each recipe is scaling. I assumed that only the "useful" recipe would be enabled, not every one.

Another option could be to have just a single CyberChef analyzer and then providing the "recipe" name as an additional configuration. That would make more easy the managament of everything.

However that would be less user friendly because the IntelOwl GUI won't provide to the user any information regarding the available recipes. To help in that, we could just provide a link to the documentation where all the available recipes will be described.

Maybe this solution can be better

**Comment by devmrfitz** [comment]
@mlodic How about I start with implement a Docker-based cyberchef analyzer that runs [this](https://gchq.github.io/CyberChef/#recipe=Unzip('',false)Strings('16-bit%20littleendian',10,'All%20printable%20chars%20(U)',false)Filter('Line%20feed','%5E%5C%5C%22',false)Find_/_Replace(%7B'option':'Extended%20(%5C%5Cn,%20%5C%5Ct,%20%5C%5Cx...)','string':'%5C%5Cx00'%7D,'',true,false,true,false)Find_/_Replace(%7B'option':'Regex','string':'%5B%22%26%20,%5D'%7D,'',true,false,true,false)) recipe on whatever (excel) file user uploads.
Would that be a good starting point?

**Comment by devmrfitz** [comment]
I've made [a commit](https://github.com/devmrfitz/IntelOwl/commit/871256a9f9ea1e6c6eb7bf97b390d59bd04b46fa). Is this the correct path?

**Comment by mlodic** [comment]
> Edit: However, the only way I could find to support using files as input involves using NodeJS[[1]](https://github.com/gchq/CyberChef/wiki/Node-API#chefbake). Should I look into this?

Good find. Anyway that would mean to write Javascript code somewhere and right now it would mean to make some important changes only to support this analyzer. I don't think it is worth.
