### ISSUE TITLE
New Analyzers - Osint.sh Toolkit

### ISSUE THREAD

**Issue by CypherpunkSamurai** [intelowlproject/IntelOwl#851]
I feel like we can add another cool OSINT tool to IntelOwl.

[Osint.sh](https://osint.sh/) is a cool website with a large collection of useful tools. I'm thinking if we should add:
* Subdomain Finder - The fastest way to discover subdomains in your DNS recon.
* DNS History - View all DNS historical records for a specified domain name.
* Reverse Name Server - Reveal all domains that use the same name server
* Reverse MX Record - Reveal all domains that use the same mail server

Optional, would be nice to have:
* Certificate Search - Find information about the target assets from their SSL certificate
* Reverse Google Adsense - Find domains with the same Google AdSense ID
* Reverse Whois - Allow you to find domain names owned by an email address
* Reverse Google Analytics - Find domains with the same Google Analytics ID
* Public Buckets - Find public buckets on AWS S3 & Azure Blob by a keyword

This is just an Idea, I'd love to hear your thoughts on this Mr. @mlodic and Mr. @eshaan7 :)

**Comment by mlodic** [comment]
Yeah but have you checked the API section? 

![image](https://user-images.githubusercontent.com/30625432/149734922-baa50a99-590b-4fec-973b-085fd2d076d5.png)

I don't think it is feasible so :/

**Comment by CypherpunkSamurai** [comment]
I noticed the WebUI has no captchas and rate-limiting as of now. Is it ok if we use their webapi?

![image](https://user-images.githubusercontent.com/66906402/149974929-05c798e9-8e3a-4f35-963c-71ab2bb8c614.png)

**Comment by mlodic** [comment]
honestly I do not like to extract the data programmatically from a GUI because it was not made for it and it is most probably an abuse of the service

**Comment by CypherpunkSamurai** [comment]
Ok, Sir, I totally understand, and I feel the same.
