### ISSUE TITLE
add msodde tool to Doc_Info analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#875]
See: https://github.com/decalage2/oletools/wiki/msodde

We should add this tool in the pipeline of tools to run to detect anomalies in Office files.

Follow this thread in [Twitter](https://twitter.com/decalage2/status/1488481984242462728) to get more details on real use cases (also for testing the solution)

**Comment by Yshaq** [comment]
Hey, can I pick up this issue?
I was able to get a list of DDE links from a csv file on a scan by just passing the filepath to the msodde.process_maybe_encrypted() function.
I need to look into cases when the file is encrypted though.

**Comment by devmrfitz** [comment]
I would like to look into this issue
