### ISSUE TITLE
Correctly manage docker-analyzer dependencies

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#882]
Right now we rely on Dependabot to keep updated the high number of dependencies of this project.

Dependabot works by reading through "requirements" files that are standards of the chosen language (ex: "requirements.txt", "pyproject.toml", etc)

I noticed that there are some Docker-analyzers where we hardcoded some dependencies directly inside the Dockerfile. This causes the Dependabot to do not retrieve updates of those dependencies and, as a consequence, there is no way that they will be updated ever.

So, we should move them outside the Dockerfile when possible.

Python dependencies:
- [x] flare-capa
- [x] stringsifter

It would be great to solve this together with this issue: #842

**Comment by Yshaq** [comment]
Hey, can I be assigned this issue?
I'd like to work on it along with issue #842

**Comment by Yshaq** [comment]
For this issue, since I just have to remove the 2 installation lines from dockerfile and add the packages to requirements.txt,
would a single PR be good for this issue and #842 together, or should I make a seperate PR for this one first?

**Comment by mlodic** [comment]
as you wish...anyway you can separate them without problems

**Comment by Yshaq** [comment]
Ok i'll make a PR for this one then coz the other one will probably take longer to finish
