### ISSUE TITLE
Add DRF Throttling to Admin Login Page

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#884]
This is to protect it from abuse

See: https://www.django-rest-framework.org/api-guide/throttling/#api-reference

**Comment by eshaan7** [comment]
The admin page is part of django core and not django-rest-framework so DRF's throttling mechanism _probably_ cannot be used here.

**Comment by devmrfitz** [comment]
I'd like to work on this issue.
Before I saw @eshaan7's comment, I was looking into [https://github.com/jazzband/django-axes](https://github.com/jazzband/django-axes) to solve this problem as it also provided [some additional features](https://github.com/jazzband/django-axes#functionality). But you're also right in the fact that the nginx method would prevent the need for another dependency.

Which one of the 2 should I go with?

**Comment by mlodic** [comment]
I guess nginx is the simplest and could be enough

**Comment by devmrfitz** [comment]
Alright. Should bursts (2 requests within the same time window, say 100 ms) be allowed?

**Comment by mlodic** [comment]
if the time windows is such low I'd say no
