### ISSUE TITLE
Analyzer not working 

### ISSUE THREAD

**Issue by N0tDaniel** [intelowlproject/IntelOwl#892]
Ho installato IntelOwl con le rispettive "requirements.txt", dopo di chè da  django administration ho creato il token come richiesto da manuale e aggiunto le API  all'interno del file "configuration" una volta avviata l'applicazione andando sul pannello principale nessuna delle API precedentemente da me aggiunte vengono rilevate. 

![4](https://user-images.githubusercontent.com/42096350/154068016-ca82c660-2d2b-496d-a437-2db5c56b31ae.png)

![1](https://user-images.githubusercontent.com/42096350/154067808-15801528-c06b-4c9f-88e1-5f5f396b1fae.png)

Ed infatti l'applicazione non rileva configurate correttamente nessuno degli analyzer.

Un altro errore che non so se sia collegato o meno, è che quando effetto il check dell'health dal sito fallisce, se provo ad eseguirlo da CLI (pyintelowl) invece è tutto ok
![2](https://user-images.githubusercontent.com/42096350/154068074-9a2f4520-e382-42d4-907e-b588d912856c.png)

**Comment by mlodic** [comment]
Ciao, mi dispiace ma credo tu non abbia correttamente letto la documentazione. https://intelowl.readthedocs.io/en/latest/Installation.html#deployment-preparation

**Comment by mlodic** [comment]
Capisci che se dovessi rispondere a tutte le domande come la tua, non riuscirei a fare altro nella vita :) 
La documentazione esiste per un motivo e leggerla prima di fare domande è una forma di rispetto verso i maintainer.

Buon divertimento con IntelOwl :P

**Comment by N0tDaniel** [comment]
si ho capito, ma come hai scritto quella riga su, potevi benissimo scrivere "vedi che non devi metterla li" ed avrei capito subito il mio stupido errore, in ogni caso grazie lo stesso, la prossima volta vedrò di leggerlo due volte.
