### ISSUE TITLE
[analyzer] screenshot to detect phishing campaigns

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#9]
We could add a Manet analyzer to get a screenshot from a specified URL that we would like to analyze.

https://github.com/vbauer/manet

We should add the docker image as optional in the docker-compose configuration and use the Manet APIs to run the analysis.

**Comment by sp35** [comment]
`manet` can be run on either of the engines `slimerjs` or `phantomjs`. 
I tried using `slimerjs` but it fails.
```bash
2021-03-17T06:16:03.085Z - error: Process error: 
2021-03-17T06:16:03.086Z - error:  error=Can not capture: en.wikipedia.org
```

**`phantomjs` has been deprecated, it's not broken though, works.**
```bash
2021-03-17T06:33:39.599Z - info: Capture site screenshot: "en.wikipedia.org"
```
Ref: https://www.npmjs.com/package/phantomjs & https://github.com/ariya/phantomjs/issues/15344

**Comment by mlodic** [comment]
Manet itself was not updated recently but it is still a useful tool to capture screenshots. For instance, this could be useful when analyzing potential phishing pages.

IMHO there are 2 chances:
* do some research and check if there is a similar, more recent tool that can reach the same goal. Then use it instead of Manet
* Integrate Manet, even with deprecated dependencies, as a docker analyzer. It would be optional and separated so it won't influence the stability of project.

**Comment by sp35** [comment]
`puppeteer` is a good alternative. The function useful to us is [page.screenshot()](https://pptr.dev/#?product=Puppeteer&version=v8.0.0&show=api-pagescreenshotoptions)

To replicate manet's functionality, we can spin up a node server to serve an endpoint and grab a screenshot of the web page using this library. 

Each `puppeteer` instance uses an instance of chromium. For this, [puppeteer-cluster](https://www.npmjs.com/package/puppeteer-cluster) can be used for concurrency, and an env variable can be set for user-specified no of parallel instances of `puppeteer`.

**Comment by mlodic** [comment]
This could be an interesting alternative.

Have you checked how the actual docker analyzers are implemented? Do you think that we could host the node server in a new optional docker analyzer?

Also, at the moment, we just show the reports as a JSON. We should manage this special case accordingly, save the screenshots in some way and give the users the chance to see them from the GUI once an analysis is finished.

This analyzer would be a little complicated but it could be a great addition.

**Comment by mlodic** [comment]
Another important thing to manage is to provide the chance to connect to the URL with a proxy.

This is important considering the context and main goal of IntelOwl. We would actively analyze the site by visiting it so the user would need a way to hide himself behind a proxy to avoid to to be detected.

**Comment by sp35** [comment]
> Have you checked how the actual docker analyzers are implemented? Do you think that we could host the node server in a new optional docker analyzer?
>
Yes, we can do that.

> Another important thing to manage is to provide the chance to connect to the URL with a proxy.
> 
Noted!

**Comment by Eshaan7** [comment]
Sorry that I'm late to this conversation but I'm bit critical of using
node.js because that means introducing a new techstack into the project
especially because docker based analyzers are made to work with the
flask-shell2http wrapper and doing this in nodejs would mean duplicating
that extension.

Can't we use selenium in python? I can find lots of examples of using
selenium to grab screenshots (https://stackoverflow.com/a/50616021) and
selenium also supports proxies.

With this, we can use the already existing techstack and flask-shell2http
without reinventing the wheel.

**Comment by Eshaan7** [comment]
We could go the lazy way and just use an external public API. 

Reference: https://stackoverflow.com/a/63466479

IMO, we can at first simply integrate the public API as a normal observable analyzer. If we find any problems with it, then we can think about adding a docker based analyzers. I say this because large number of docker based analyzers is hard to maintain for us and also to spin up for the user.

**Comment by Eshaan7** [comment]
Also, at the moment, we just show the reports as a JSON. We should manage this special case accordingly, save the screenshots in some way and give the users the chance to see them from the GUI once an analysis is finished.

> bit hacky way but: how about storing the image in its base64 encoding? When send to the frontend, we can use this base64 encoded string to display the image.

**Comment by sp35** [comment]
> IMO, we can at first simply integrate the public API as a normal observable analyzer.
>
Seems fine to me, I felt having our own analyzer (running in sandbox layer in user's machine) would be beneficial. @mlodic, any specific reason for originally proposing manet?

> bit hacky way but: how about storing the image in its base64 encoding? When sent to the frontend, we can use this base64 encoded string to display the image.
>
How about adding a field `analysis_has_img` in the JSON report and a separate endpoint to fetch image results then? We can then store the images as a media file by creating a new model linking the job and the image files.

**Comment by mlodic** [comment]
I agree completely with @Eshaan7. His considerations should be followed.

> Seems fine to me, it felt like having our own analyzer (running in sandbox layer in user's machine) was beneficial. @mlodic, any specific reason for originally proposing manet?

Manet is a project related to the Honeynet Project, this is the main reason. However it is quite old so it does not matter anymore.

> bit hacky way but: how about storing the image in its base64 encoding? When sent to the frontend, we can use this base64 encoded string to display the image.

This is hacky but this won't need any particular customization of IntelOwl. Also, it makes sense to store binaries in base64 encoding.

> How about adding a field analysis_has_img in the JSON report and a separate endpoint to fetch image results then? We can store the images as a media file by creating a new model linking the job and the image files.

At the moment this new analyzer would be the only one to leverage this new feature. Maybe it is a bit overkill. Idk honestly

**Comment by Eshaan7** [comment]
> How about adding a field analysis_has_img in the JSON report and a separate endpoint to fetch image results then? We can store the images as a media file by creating a new model linking the job and the image files.

Good idea but as @mlodic said this seems overkill. It's possible to construct image URLs from base64 that can be opened in the browser so I think that's the way to go.

**Comment by Eshaan7** [comment]
After much discussion,

- For external service: screenshotapi.net
- For internal service: I found a wrapper over puppeteer so we won't need to write our own API in node.js (see: https://stackoverflow.com/a/55110164/10534470)

We can just take the docker image rendertron already provides and that will be our docker based analyzer.
