### ISSUE TITLE
Wigle.net integration

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#91]
We can integrate wigle.net's API for wireless network’s analysis.

Interesting API endpoints:

- https://api.wigle.net/swagger#/Bluetooth_search_and_information_tools/detail
- https://api.wigle.net/swagger#/Cell_search_and_information_tools/mccMnc

**Comment by CITIZENDOT** [comment]
I would like to work on this.

**Comment by mlodic** [comment]
solved #304
