### ISSUE TITLE
Script to automate releases posts on Twitter

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#912]

**Comment by 0x0elliot** [comment]
Is this something I can help out with Matteo?

**Comment by yaswanthsaivendra** [comment]
Or how about using [automate.io](https://automate.io/) for this??

**Comment by mlodic** [comment]
> Or how about using [automate.io](https://automate.io/app/bots/install/github/twitter/new-release/send-tweet) for this??

Yes, this could be enough and free. I have set-up that. Thanks for the suggestion, let's see if it works properly in the next release :P

**Comment by mlodic** [comment]
Automate.io is retiring (31st october). We need to find something else to push notifications for Twitter and LinkedIn

**Comment by mlodic** [comment]
this should be solved by the Github Action
