### ISSUE TITLE
Create default superuser with startup script.py

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#933]
To reduce the complexity of the installation, we could add this options to the `start.py` script:

* `--default-superuser` that automatically creates `intelowl:intelowl` as superuser. This can be useful to have the instance running in less time for tests/demos.

**Comment by iharshit009** [comment]
Hey @mlodic, Should I take this up? I guess this would give me enough insights on the code which would be good before I start #830

**Comment by mlodic** [comment]
yep, thanks!

**Comment by BenjaminH-Sogeti** [comment]
I may do that, it shouldn't take much time

**Comment by eshaan7** [comment]
It should be noted that this has the potential of accidental creation of such an user in production. This could result in a security mishap very easily.

> This can be useful to have the instance running in less time for tests/demos.

I recommend that the `--default--superuser` flag should be usable along with the `test` or `ci` modes only.

**Comment by eshaan7** [comment]
The `dev-v4` branch contains a [`initdb.sh`](https://github.com/intelowlproject/IntelOwl/blob/dev-v4/docker/scripts/initdb.sh) script which indirectly solves this.

**Comment by mlodic** [comment]
yeah, on a different thought I think it does not make sense to solve this issue as I intended it.

`initdb.sh` or not, the user would need to make a manual creation either way. So what we have [here](https://intelowl.readthedocs.io/en/latest/Installation.html#after-deployment) can be enough
