### ISSUE TITLE
[React new Frontend] update frontend dependencies and related code

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#935]
related to #856

**Comment by eshaan7** [comment]
Isn't this duplicate of #881 ?

**Comment by mlodic** [comment]
the intent is to remove all the deprecated dependencies (they are a lot), move to bootstrap 5 and refactor all the code as a consequence

**Comment by mlodic** [comment]
`npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

`

**Comment by mlodic** [comment]
after `npm audit fix` 

`27 vulnerabilities (13 moderate, 14 high)`

**Comment by eshaan7** [comment]
> move to bootstrap 5

Bootstrap 5 is very different from Bootstrap 4 - tonnes of breaking changes. Upgrading to bootstrap 5 also means having to upgrade to Reactstrap v9 (lots of breaking changes again) which in turn means migrating certego-ui first and then the IntelOwl frontend.

To be quite frank, we do not have the bandwidth for this. In my opinion, this is not an urgent requirement and we shouldn't make this part of the v4.0 milestone.

**Comment by eshaan7** [comment]
> after `npm audit fix`
> 
> `27 vulnerabilities (13 moderate, 14 high)`

That's just how npm works - you seriously cannot bring that number down to 0 (or even single digits) given how many different packages we use.

**Comment by mlodic** [comment]
> To be quite frank, we do not have the bandwidth for this. In my opinion, this is not an urgent requirement and we shouldn't make this part of the v4.0 milestone.

We will work about this internally in Certego in the next months.

> That's just how npm works - you seriously cannot bring that number down to 0 (or even single digits) given how many different packages we use.

As builders of security products we should take this more seriously. It is an annoying work, like the major upgrades you mentioned, but someone has to do it some day.

**Comment by mlodic** [comment]
consider this solved after the merge of branch `dev-v4-new`
