### ISSUE TITLE
Discussion: Traefik for self-hosted deployment + serverless deployment with celery

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [intelowlproject/IntelOwl#95]
Hey @Eshaan7. I'm a contributor on [cookiecutter-django](https://github.com/pydanny/cookiecutter-django), and I think the way you've set up this project could take some inspiration from that repository.

For one, the compose files could be labeled a little better. Other things like the .env files could be in their own directory, the Dockerfiles can be in their own, and the requirements could be separated to make the Docker builds smaller.

The one main part is Traefik: auto-renewal of certs and easy to configure with compose. You can take a look at production.yml and compose/production/traefik for how we configure it. It may come useful for those looking for self deployment.

If people want to scale, I made a [complete-walkthrough repository](https://github.com/Andrew-Chen-Wang/cookiecutter-django-ecs-github) for those looking to do AWS ECS deployment via git push to GitHub. It can be made into fargate if you don't integrate celery. (Which is the other thing: I don't think using Fargate with this project would be wise since you're using celery. The first two answers in [this SO makes it clear why.](https://stackoverflow.com/questions/53218715/operating-the-celery-worker-in-the-ecs-fargate)).

**Comment by Eshaan7** [comment]
>  the requirements could be separated to make the Docker builds smaller.

We have plans to work on that, but they mostly involve any newer dependencies regarding integration of new analyzers. See this [section](https://intelowl.readthedocs.io/en/latest/Installation.html#optional-analyzers). The main constraint we have with this is that most analyzers are command-line tools. If they are kept in seperate containers, we can't interact with them unless we wrap them as a REST API that can then be http called from the main django application (like how it's done for PEframe/optional analyzers). This is the main reason the base image is bulky. We are definitely open to ideas in this space.

> Traefik: auto-renewal of certs and easy to configure with compose

This seems like a good tool but IMO could be a bit advanced for our usage. We have nginx configured already. 

> If people want to scale, I made a complete-walkthrough repository for those looking to do AWS ECS deployment via git push to GitHub.
 
This seems like something better left to the end-user regarding their hosting requirements. Plus, celery is a primary component of our application. As mentioned in the Intel Owl's docs AWS fargate or serverless deployment is more of a "future" goal.

> For one, the compose files could be labeled a little better. Other things like the .env files could be in their own directory

Interested in this. I think as the application grows more we should better _seperate_ configurations into their own directory. Seperate folders for the env and compose files could be helpful although IMHO the way it's done in cookiecutter-django seems to have a learning curve to it and a new user trying to setup this application for the first time could easily lose himself. But I am all for cleaning the root directory and seperating different configurations in different folders. What do you think, @mlodic  ?


PS: It should be noted here that this project is quite new, so we are welcome to ideas and contributions in all spaces so thank you for your inputs, @Andrew-Chen-Wang.

**Comment by Andrew-Chen-Wang** [comment]
No problem! Project seems interesting, so I just left some comments to help out. Honestly, if you're using a compose file, in general, there's a Docker learning curve to go through (I think when I first looked at cookiecutter-django, not having any clue about Docker and knowing programming for a couple months). Separating the configurations of compose files could be helpful in general when thinking local vs. production usage. Although, I will give it to you that cookiecutter-django is more for cookiecutter-ing a template project for quick setup.

I mainly gave an ECS walkthrough because using celery with a server less setup is a bad idea. I left a note about why it's bad somewhere, but essentially instances are not supposed to start up just for a celery task, which is why you need at least one instance continuously running. (I was just taking a look at your beat configuration for getting something like the new MaxMind db, which is definitely something lambda or fargate should not be doing).

Regarding the requirements, I meant separate the requirements.txt files like requirements/local.txt and requirements/production.txt.

**Comment by Eshaan7** [comment]
> Separating the configurations of compose files could be helpful in general when thinking local vs. production usage.

Yes, we do have different compose/config files for local, tests and production. It would be good if we can better separate these into their own folders and potentially add their entries to .dockerignore to slim the image. 

> Regarding the requirements, I meant separate the requirements.txt files like requirements/local.txt and requirements/production.txt.

Yes, that can be done too. I just created a new issue regarding this. #98.

**Comment by mlodic** [comment]
Thank you very much @Andrew-Chen-Wang! I really appreciated your tips.

About the support for AWS Fargate, it was just a very early idea that was not completely developed. When we will think about that, we would set up a different configuration/architecture for this case that won't leverage celery at all.
 
At the moment our focus is on creating a fresh and new interface and on trying to make the project the most desirable as possible for new contributions. The 1.0 is approaching.

**Comment by Andrew-Chen-Wang** [comment]
Sure, no problem. Good luck and have fun with a great GSoC!

**Comment by Eshaan7** [comment]
Traefik compose files were added and we have #96 to discuss and track regarding serverless so we can close this issue.
