### ISSUE TITLE
XForceExchange - URL wrong cast

### ISSUE THREAD

**Issue by BHanq** [intelowlproject/IntelOwl#951]
## What happened
XForceExchange URL analyzer cast special character into %xx characters. Then the api, is wrongly called. And an error is raised. 

## Environment
1. OS: Ubuntu 20.0.4
2. IntelOwl version: 3.3.2

##  What did you expect to happen
Having an analysis for this : https://exchange.xforce.ibmcloud.com/url/http:~2F~2Fmoviesfoundonline.com

## How to reproduce your issue
Start an analysis on XForceExchangeAnalyser with an URL (like http://moviesfoundonline.com), the analysis will fail because the url is cast into special characters in string using the %xx escape 
## Error messages and logs
404 Client Error: Not Found for url: https://api.xforce.ibmcloud.com/url/malware/http%3A%2F%2Fmoviesfoundonline.com

## Why it happens
I think that the issue comes from the [XForceExchangeAnalyzer](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/analyzers_manager/observable_analyzers/xforce.py) at line 29, url is parsed using [quote_plus()](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus), thus it replace characters...

**Comment by mlodic** [comment]
thanks for reporting this. I checked and the error was the main URL that was missing the "/api" but still worked anyway sometimes....the right url is `"https://api.xforce.ibmcloud.com/api"`
The fix will be available next release.

**Comment by BHanq** [comment]
Are you sure it is not : https://exchange.xforce.ibmcloud.com/api/
Because in api.xforce.ibmcloud.com I have found nowhere in the documentation that missing /api. [Sample stays](https://api.xforce.ibmcloud.com/doc/#/URL/get_url__url_) : https://api.xforce.ibmcloud.com/url/www.ibm.com%2Fsmarterplanet in the docs

**Comment by BenjaminH-Sogeti** [comment]
@mlodic have you already done it or would you like help ?

**Comment by mlodic** [comment]
done this but not released yet :P I'll plan a new release soon, please follow the project so you get the update!

**Comment by BenjaminH-Sogeti** [comment]
Has it changed ? 

![image](https://user-images.githubusercontent.com/103488825/167794445-3e9f23a4-e9ef-4a24-82ea-d4b3f3ed4330.png)
![image](https://user-images.githubusercontent.com/103488825/167794534-72c3942e-a43a-42b1-b79a-144a064ffafe.png)

Following the actual xforce website API call should be like : 
# WWW
`curl -X GET --header 'Accept: application/json' -u {API_KEY:API_PASSWORD} 'https://exchange.xforce.ibmcloud.com/api/url/www.moviesfoundonline.com'`

# HTTP 
`curl -X GET --header 'Accept: application/json' -u {API_KEY:API_PASSWORD} 'https://exchange.xforce.ibmcloud.com/api/url/http://moviesfoundonline.com'`

**Comment by mlodic** [comment]
thanks for reporting this again!

I am sad cause I tested that manually. I retried that now and you are right, it does not work. 🤔 

I followed their [docs](https://api.xforce.ibmcloud.com/doc):
![image](https://user-images.githubusercontent.com/30625432/167802093-bfdaaf1c-1f33-44ae-91f0-0623537f7118.png)

Meanwhile, if you want to fix it locally (to avoid waiting for the next release), you can just apply the modification you can find in this commit by calling `git checkout xforce_fix`, shut down your instance and rerun it with a local build `python3 start.py test down && python3 start.py test up --build -d`. I have also added a "link" to the web GUI in the resutls

**Comment by mlodic** [comment]
on a second thought, I think that it is normal behavior. It just means that that URL was not found in their DB.

I should change the analyzer to do not fail in that case.

**Comment by mlodic** [comment]
If the result is 404, thanks to the new change in the branch `xforce_fix`, you will found a new key "found" that is set to False.

**Comment by BenjaminH-Sogeti** [comment]
Thanks a lot !

**Comment by mlodic** [comment]
consider this solved and shipped in the next release
