### ISSUE TITLE
[React new Frontend] Add GSoC Honeynet channel link + Github link to footer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#955]
Replicate the same behavior that we had in the Angular Frontend

**Comment by viveknshah** [comment]
Is there anywhere I can see the Angular version you are looking for mimicking here? 
Or is this where you are looking for the change : https://github.com/intelowlproject/IntelOwl/blob/master/frontend/src/layouts/AppFooter.jsx

**Comment by mlodic** [comment]
yep exactly there. It's not important to mimick the old way, we can just add it the a new one

**Comment by mlodic** [comment]
closed with #1238
