### ISSUE TITLE
[React New Frontend] provide navigable JSON result for each analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#959]
In the IntelOwl v3 version we have this navigable component that allows us to easily surf the JSON result of an analyzers

![image](https://user-images.githubusercontent.com/30625432/160890858-b5a65f6d-4ec5-486b-9f50-d75dcb11753a.png)

In IntelOwl v4, by default, we get all the JSON data at the same time. While this can be helpful, most of the time is not.
Example:
![image](https://user-images.githubusercontent.com/30625432/160891079-1c5fc6d7-00b9-4455-80ce-9307a192d9ea.png)

My idea is to replace that new component with something similar to the previous one available in the Angular GUI

**Comment by 0x0elliot** [comment]
We can use something like this for this task: https://mui.com/material-ui/react-tree-view/
Seems quite doable. I would like to try taking care of it. It's a bit packed these days so give me time till the weekend!

**Comment by mlodic** [comment]
Another idea pointed out by @BenjaminH-Sogeti could be a view like [this](https://bennadel.github.io/JSON-Explorer/dist/#eyJ0eXBlIjoiaG9vbWFuIiwibmFtZSI6IkJlbiIsImNoaWxkcmVuIjpbeyJ0eXBlIjoiZG9nbyIsIm5hbWUiOiJMdWN5IiwiYWdlIjo4LCJuaWNrbmFtZXMiOlsiTHVjeSBHb29zZXkiLCJHb29zZS1GYWNlIEtpbGxhJyIsIlBvb3BlciJdLCJpc0Fkb3JhYmxlIjp0cnVlfV0sImFnZSI6MzksIm1ldGFkYXRhIjoieyBcIl9pZFwiOiBcImMtMzQ5ZGszOVwiLCBcImNyZWF0ZWRBdFwiOiAxMjM0NS4zNDM5OSB9IiwiYWx0ZXJuYXRlRWdvIjpudWxsfQ==) as an additional option. We should check what we can find as pre-built in react packages

**Comment by 0x0elliot** [comment]
That's pretty cool as well! I will try to put together whatever gets the job done best :)

**Comment by mlodic** [comment]
Before closing this, @devmrfitz can you investigate please whether there is the chance to add a "search" tab like it was available in the previous JSON renderer?

![image](https://user-images.githubusercontent.com/30625432/176468331-f8d04d53-81ca-457f-be41-255089cca1ca.png)

Even if your addition is good, we are still losing some functionality. This can be particularly useful when the output contains a lot of data

**Comment by mlodic** [comment]
I also noticed that, while opening by default to the "data" keyword is useful, there is no chance of collapsing it back and hide it.
See:

![image](https://user-images.githubusercontent.com/30625432/176469033-1cf6885d-4ba0-455f-9a2f-951955812618.png)

Considering that there can be a lot of data, then it would be difficult to visualize the elements that are available after the `data`. Maybe we could just open only `report` keyword. Thoughts?

**Comment by devmrfitz** [comment]
> Before closing this, @devmrfitz can you investigate please whether there is the chance to add a "search" tab like it was available in the previous JSON renderer?
> 
> ![image](https://user-images.githubusercontent.com/30625432/176468331-f8d04d53-81ca-457f-be41-255089cca1ca.png)
> 
> Even if your addition is good, we are still losing some functionality. This can be particularly useful when the output contains a lot of data
@mlodic 
It seems `react-json-view` has an open feature request for a search. Do you have any alternate packages in mind, maybe the one which was being used in the previous version?

**Comment by mlodic** [comment]
Previous version was made by @eshaan7 and you can find the code here: https://github.com/intelowlproject/IntelOwl-ng

The older JSON viewer allowed to collapse/un-collapse everything: that was very useful. Without having any other way to visualize data right now, we cannot be satisfied with just the actual result, even if the viewer is cool

**Comment by devmrfitz** [comment]
> Without having any other way to visualize data right now, we cannot be satisfied with just the actual result, even if the viewer is cool

Didn't understand this. Could you explain?

**Comment by mlodic** [comment]
I meant that the viewer you added is cool but it lacks of functionality if compared with the old one. Right now we don't have other ways to visualize the data extracted from IntelOwl so we should try harder to provide the old functionality back to the viewer

**Comment by devmrfitz** [comment]
Makes sense. I'm actively trying to find a ReactJS equivalent of the Angular package used previously, but haven't been able to find any yet. I'll get back to you as soon as something better is found.

**Comment by devmrfitz** [comment]
@mlodic I found this but it's not regularly updated.
https://github.com/aspecto-io/searchable-react-json-view

**Comment by drosetti** [comment]
> @mlodic I found this but it's not regularly updated. https://github.com/aspecto-io/searchable-react-json-view

@devmrfitz I think you can proceed testing [searchable-react-json-view](https://github.com/aspecto-io/searchable-react-json-view).

As you said is not updated (last commit 19th july 2021) and this is not a good news, but also the "base" project is not updated (last commit 9th march 2021). I looked for other projects, but I only worst supported project or other forks of react-json-view.  

Reading the docs I discovered a useful field: `collapsed: When set to true, all nodes will be collapsed by default. Use an integer value to collapse at a particular depth.` This could allow us to show/hide all the dict elements, this is a function available in the v3 version and I think it can be useful restore it. Please test it.

**Comment by devmrfitz** [comment]
> As you said is not updated (last commit 19th july 2021) and this is not a good news, but also the "base" project is not updated (last commit 9th march 2021). I looked for other projects, but I only worst supported project or other forks of react-json-view.

Sure. I'll get on it. However, it also has just a single star.

> Reading the docs I discovered a useful field: collapsed

I've used this field to set the default collapse value to 2. Lemme check if it can be changed during runtime.

**Comment by devmrfitz** [comment]
@drosetti 

```
certego-ui$ npm i searchable-react-json-view
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @certego/certego-ui@0.1.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^15.5.4" from searchable-react-json-view@0.0.8
npm ERR! node_modules/searchable-react-json-view
npm ERR!   searchable-react-json-view@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
`searchable-react-json-view` has a version conflict with React itself

**Comment by drosetti** [comment]
Nice catch! We cannot use this library.

I think we can leave this issue open and wait a bit, at least until @mlodic return. There aren't lot of libraries to test, but also create this function (toggle and search) could require time

**Comment by drosetti** [comment]
< eading the docs I discovered a useful field: collapsed: When set to true, all nodes will be collapsed by default. Use an integer value to collapse at a particular depth. This could allow us to show/hide all the dict elements, this is a function available in the v3 version and I think it can be useful restore it. Please test it.

The  `collapsed` parameter has a strange behaviour: in case you open dict keys with the related arrow buttons the "show/hide all" stops working. I think this is a non-intuitive beahivour and we cannot use it.

**Comment by mlodic** [comment]
I'd say amen for this. Then we would need to accelerate in providing a simplified view of the JSON results.
