### ISSUE TITLE
Allow plugin secrets to be stored and managed from GUI

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#978]
> At the moment, the API keys can be inserted only before starting the project, as environment variables.
It would be useful to let the user set up those keys and the other required configuration directly from the GUI.
This would imply a lot of changes. Also, we have already planned to work on the configuration (https://github.com/intelowlproject/IntelOwl/issues/306) so this idea could be considered as a later development

-- @mlodic in #433.

**Comment by devmrfitz** [comment]
@drosetti  @0ssigeno @mlodic Do we intend to have global analyzer creds (like they are currently), or per-user credentials?

**Comment by 0ssigeno** [comment]
In my opinion, we could work in 2 steps: the first one, is to make the secret manageable by the GUI globally, so that we are just adding this new management possibility. After that, we can discuss if we want to have a per-user management, and we have any user case where this is needed.

**Comment by mlodic** [comment]
closed with #1238
