### ISSUE TITLE
Divide requirements.txt into development.txt and production.txt

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#98]
We could separate the `requirements.txt` file into small files such as development/local.txt and requirements/production.txt.

_Originally posted by @Andrew-Chen-Wang in https://github.com/intelowlproject/IntelOwl/issues/95#issuecomment-647153922_

**Comment by Andrew-Chen-Wang** [comment]
It'll help with Docker caching. If you change a production package, then you have to rebuild the entire pip install stage in your Dockerfile. It's for readability and for Docker benefits like small image sizes.

**Comment by mlodic** [comment]
Good idea! Thank you for your inputs!

**Comment by Eshaan7** [comment]
We could make this a part of #215.

**Comment by Eshaan7** [comment]
@0ssigeno do you think we could make this part of #289 ?

**Comment by 0ssigeno** [comment]
Yeah, sure
