### ISSUE TITLE
Base class for analyzers run function

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#99]
Under [script_analyzers/](https://github.com/intelowlproject/IntelOwl/tree/master/api_app/script_analyzers), we have too much duplicate code in each analyzer's `run()` function. For example, getting `additional_config_params`, verifying them, setting up report, catching and handling errors. Can't we take more of an Object oriented approach here ? 

This is just a very basic overview of what I have in mind:

```python
from abc import ABC, abstractmethod
import requests

class AnalyzerRunNotImplemented(Exception):
    detail = "run() is not implemented for analyzer {}"

class Analyzer(ABC):
    analyzer_name = None
    md5 = None
    observable_classification = None
    # and more variables
    ...

    @abstractmethod
    def run(self, *args, **kwargs):
        # this should be overwritten in 
        # child class
        raise AnalyzerRunNotImplemented(self.analyzer_name)

    def __init__(self, *args, **kwargs):
        # initialize shared variables
    
    def get_config(self, *args, **kwargs):
        # fetch additional_config_params
        # verify params, API keys, etc

    def set_report_and_cleanup(self, *args, **kwargs):
        # sets report logic
    def handle_error(self, *args, **kwargs):
        # handles error logic


class Shodan(Analyzer):
    analyzer_name = "shodan"
    observable_classification = "ip"
    url = "https://api.shodan.io/shodan/host/"
    
    def run(self):
        try:
            data = {"ip": self.observable_value}
            resp = requests.post(self.url, json=self.data)
            return super(self).set_report(resp)
        except Exception:
            return super(self).handle_error(resp)
```

Advantages:
- reduce a lot of duplicate code
- code looks more clean
- makes it easier for new contributors to integrate an analyzer.
- don't have to pass a bunch of variables to the run function, since we can just store them as member variables of the class.  `def run(analyzer_name, job_id, observable_name, observable_classification, additional_config_params)` - This does not look good.
- in some analyzers, the error/report handling is different - for those we can just overwrite the `set_report_and_cleanup` and `handle_error` functions too. But for all others, we don't need to. 
- We already have code for handling error, setting up report and all in [general.py](https://github.com/intelowlproject/IntelOwl/blob/a12ca7253c2642558be11e1fd005e1c1e7030f8e/api_app/script_analyzers/general.py#L122), we would mostly need to refactor it work with objects/classes.

**Comment by mlodic** [comment]
Absolutely. 100% agree
