### ISSUE TITLE
[Analyzer] DocGuard

### ISSUE THREAD

**Issue by SteAmeR** [intelowlproject/IntelOwl#996]
This issue related to PR https://github.com/intelowlproject/IntelOwl/pull/990
## Name
Docguard can analyze files in seconds using its groundbreaking analyzer engine and detect all known attack methods without any miss.

## Link
https://www.docguard.io/
https://app.docguard.io/

## Type of analyzer
file, observable
## Why should we use it
Gartner strongly suggests that Email Security Supplements are needed if an organization has a particular use case or a specific advanced threat type is prevalent. Additionally, Docguard should be considered as an additional layer of defense.

## Possible implementation
O365, Office Apps Add-ons, XSOAR, SIEM or any web-app supported apps.

**Comment by mlodic** [comment]
closed with v3.4.0
